import json
import time
from deep_translator import GoogleTranslator

# TOEFL Academic Word List - High Frequency Words
TOEFL_WORDS = {
    "0-60": [
        ("abandon", "verb", "To leave behind or give up completely", "The crew had to abandon the sinking ship."),
        ("ability", "noun", "The capacity to do something", "She has the ability to solve complex problems."),
        ("able", "adjective", "Having the power or skill to do something", "He is able to speak three languages."),
        ("about", "preposition", "Concerning or regarding", "The book is about ancient history."),
        ("above", "preposition", "At a higher level than", "The plane flew above the clouds."),
        ("abroad", "adverb", "In or to a foreign country", "She studied abroad for two years."),
        ("absence", "noun", "The state of being away from a place", "His absence was noticed by everyone."),
        ("absent", "adjective", "Not present in a place", "Several students were absent today."),
        ("absolute", "adjective", "Complete and total", "The king had absolute power."),
        ("absorb", "verb", "To take in or soak up", "Plants absorb water through their roots."),
        ("abstract", "adjective", "Existing in thought but not physical", "Love is an abstract concept."),
        ("academic", "adjective", "Related to education and scholarship", "She excels in academic subjects."),
        ("accept", "verb", "To receive willingly", "Please accept my sincere apology."),
        ("access", "noun", "The means to approach or enter", "Students have access to the library."),
        ("accident", "noun", "An unexpected event causing damage", "The accident blocked traffic for hours."),
        ("accommodate", "verb", "To provide space or lodging for", "The hotel can accommodate 200 guests."),
        ("accompany", "verb", "To go somewhere with someone", "May I accompany you to the event?"),
        ("accomplish", "verb", "To achieve or complete successfully", "She accomplished her goal."),
        ("according", "preposition", "As stated or indicated by", "According to the report, sales increased."),
        ("account", "noun", "A record or description of events", "He gave a detailed account of the trip."),
        ("accurate", "adjective", "Correct in all details", "The information must be accurate."),
        ("achieve", "verb", "To successfully reach a goal", "Hard work helps you achieve success."),
        ("achievement", "noun", "Something accomplished successfully", "Graduating was a great achievement."),
        ("acknowledge", "verb", "To accept or admit the existence of", "She acknowledged her mistake."),
        ("acquire", "verb", "To obtain or gain possession of", "He acquired a new skill."),
        ("across", "preposition", "From one side to the other", "They walked across the bridge."),
        ("act", "verb", "To take action or perform", "We must act quickly."),
        ("action", "noun", "The process of doing something", "Immediate action is required."),
        ("active", "adjective", "Engaging in physical activity", "She leads an active lifestyle."),
        ("activity", "noun", "A thing that a person does", "Swimming is a popular activity."),
        ("actual", "adjective", "Existing in fact; real", "The actual cost was higher than expected."),
        ("adapt", "verb", "To adjust to new conditions", "Animals adapt to their environment."),
        ("add", "verb", "To join something to something else", "Add salt to the soup."),
        ("addition", "noun", "The action of adding something", "The addition of a pool increased value."),
        ("additional", "adjective", "Added or extra", "Additional information is needed."),
        ("address", "noun", "The location of a building", "What is your home address?"),
        ("adequate", "adjective", "Sufficient for a purpose", "The food supply was adequate."),
        ("adjust", "verb", "To alter slightly to achieve a result", "Please adjust the volume."),
        ("administration", "noun", "The management of affairs", "The administration announced new policies."),
        ("admit", "verb", "To confess or acknowledge", "He admitted his fault."),
        ("adopt", "verb", "To take up or start to use", "They adopted a new approach."),
        ("adult", "noun", "A fully grown person", "Adults must supervise children."),
        ("advance", "verb", "To move forward", "Technology continues to advance."),
        ("advanced", "adjective", "Far on in progress", "She took an advanced course."),
        ("advantage", "noun", "A favorable condition", "Experience is an advantage."),
        ("adventure", "noun", "An exciting experience", "The trip was a great adventure."),
        ("advice", "noun", "Guidance offered by someone", "She gave me helpful advice."),
        ("advise", "verb", "To offer suggestions", "I advise you to study harder."),
        ("affair", "noun", "An event or matter", "Foreign affairs are complex."),
        ("affect", "verb", "To have an impact on", "Weather affects crop growth."),
        ("afford", "verb", "To have enough money for", "I cannot afford a new car."),
        ("afraid", "adjective", "Feeling fear", "She was afraid of the dark."),
        ("after", "preposition", "Following in time", "We will meet after lunch."),
        ("again", "adverb", "Once more", "Please say that again."),
        ("against", "preposition", "In opposition to", "They voted against the proposal."),
        ("age", "noun", "The length of time someone has lived", "What is your age?"),
        ("agency", "noun", "An organization providing services", "The agency handles travel bookings."),
        ("agent", "noun", "A person who acts on behalf of another", "The real estate agent sold the house."),
        ("agree", "verb", "To have the same opinion", "We agree on this matter."),
        ("agreement", "noun", "A mutual arrangement", "They signed an agreement."),
        ("agriculture", "noun", "The practice of farming", "Agriculture is vital for food supply."),
        ("ahead", "adverb", "Further forward in position", "The road ahead is clear."),
        ("aid", "noun", "Help or support", "The country received foreign aid."),
        ("aim", "noun", "A purpose or intention", "Her aim is to become a doctor."),
        ("air", "noun", "The invisible gases around us", "Fresh air is refreshing."),
        ("aircraft", "noun", "A vehicle that flies", "The aircraft landed safely."),
        ("airline", "noun", "A company providing air transport", "The airline offers cheap flights."),
        ("airport", "noun", "A place where aircraft land", "The airport was crowded."),
        ("alarm", "noun", "A warning signal", "The fire alarm went off."),
        ("alive", "adjective", "Living; not dead", "The patient is still alive."),
        ("all", "determiner", "The whole quantity", "All students must attend."),
        ("allow", "verb", "To permit", "Parents allow children to play."),
        ("almost", "adverb", "Nearly; not quite", "The project is almost complete."),
        ("alone", "adjective", "Without others", "She lives alone."),
        ("along", "preposition", "Moving in a constant direction", "Walk along the river."),
        ("already", "adverb", "Before now or a specified time", "I have already finished."),
        ("also", "adverb", "In addition", "He also speaks French."),
        ("alter", "verb", "To change in character", "Do not alter the document."),
        ("alternative", "noun", "Another choice", "Walking is an alternative to driving."),
        ("although", "conjunction", "Despite the fact that", "Although tired, she continued working."),
        ("always", "adverb", "At all times", "She always arrives on time."),
        ("amaze", "verb", "To surprise greatly", "The magic trick amazed everyone."),
        ("amount", "noun", "A quantity of something", "A large amount of money was spent."),
        ("analysis", "noun", "Detailed examination", "The analysis revealed new findings."),
        ("analyze", "verb", "To examine in detail", "Scientists analyze data carefully."),
        ("ancient", "adjective", "Belonging to the distant past", "Ancient civilizations fascinate historians."),
        ("anger", "noun", "A strong feeling of displeasure", "His anger was evident."),
        ("angle", "noun", "The space between two lines", "Measure the angle carefully."),
        ("angry", "adjective", "Feeling or showing anger", "She was angry about the decision."),
        ("animal", "noun", "A living organism", "Dogs are loyal animals."),
        ("announce", "verb", "To make a public statement", "The company announced new products."),
        ("annual", "adjective", "Occurring once a year", "The annual report was published."),
        ("another", "determiner", "One more; an additional", "Would you like another cup of tea?"),
        ("answer", "noun", "A response to a question", "The answer is correct."),
        ("anticipate", "verb", "To expect or predict", "We anticipate a large turnout."),
        ("anxiety", "noun", "A feeling of worry or unease", "Exam anxiety is common among students."),
        ("anxious", "adjective", "Feeling worried or nervous", "She was anxious about the interview."),
        ("any", "determiner", "One or some of something", "Do you have any questions?"),
        ("anybody", "pronoun", "Any person", "Is anybody home?"),
        ("anyone", "pronoun", "Any person at all", "Anyone can participate."),
        ("anything", "pronoun", "Any thing at all", "Is there anything I can help with?"),
    ],
    "60-80": [
        ("anywhere", "adverb", "In or to any place", "You can sit anywhere."),
        ("apart", "adverb", "Separated by a distance", "They live far apart."),
        ("apartment", "noun", "A set of rooms for living", "She rented a small apartment."),
        ("apparent", "adjective", "Clearly visible or understood", "The solution became apparent."),
        ("appeal", "noun", "A serious request", "The charity made an appeal for donations."),
        ("appear", "verb", "To come into sight", "Stars appear at night."),
        ("appearance", "noun", "The way someone looks", "First appearances can be deceiving."),
        ("application", "noun", "A formal request", "Submit your application by Friday."),
        ("apply", "verb", "To make a formal request", "She applied for the job."),
        ("appoint", "verb", "To assign a job or role", "They appointed a new manager."),
        ("appreciate", "verb", "To recognize the value of", "I appreciate your help."),
        ("approach", "noun", "A way of dealing with something", "We need a new approach."),
        ("appropriate", "adjective", "Suitable or proper", "Wear appropriate clothing."),
        ("approve", "verb", "To officially agree to", "The board approved the plan."),
        ("approximately", "adverb", "Close to an exact amount", "It costs approximately fifty dollars."),
        ("area", "noun", "A region or space", "The area is known for tourism."),
        ("argue", "verb", "To give reasons for or against", "They argued about politics."),
        ("argument", "noun", "A disagreement or debate", "The argument lasted for hours."),
        ("arise", "verb", "To come into being", "Problems may arise unexpectedly."),
        ("arm", "noun", "The upper limb of the body", "He broke his arm playing soccer."),
        ("army", "noun", "An organized military force", "The army defended the border."),
        ("around", "preposition", "On all sides of", "Trees grow around the lake."),
        ("arrange", "verb", "To put in order", "Please arrange the books alphabetically."),
        ("arrangement", "noun", "A plan or preparation", "We made arrangements for the trip."),
        ("arrest", "verb", "To seize by legal authority", "Police arrested the suspect."),
        ("arrival", "noun", "The act of arriving", "Announce your arrival in advance."),
        ("arrive", "verb", "To reach a destination", "The train will arrive at noon."),
        ("art", "noun", "Creative expression", "Art enriches our lives."),
        ("article", "noun", "A piece of writing", "I read an interesting article."),
        ("artificial", "adjective", "Made by humans; not natural", "Artificial flowers look real."),
        ("artist", "noun", "A person who creates art", "The artist displayed her paintings."),
        ("aspect", "noun", "A particular part or feature", "Consider every aspect of the issue."),
        ("assess", "verb", "To evaluate or estimate", "Teachers assess student progress."),
        ("assessment", "noun", "The act of evaluating", "The assessment was comprehensive."),
        ("asset", "noun", "A useful or valuable thing", "Knowledge is a valuable asset."),
        ("assign", "verb", "To allocate a task", "The teacher assigned homework."),
        ("assignment", "noun", "A task given to someone", "Complete the assignment by Monday."),
        ("assist", "verb", "To help or support", "Volunteers assist at the event."),
        ("assistance", "noun", "Help or support", "Thank you for your assistance."),
        ("assistant", "noun", "A person who helps", "The assistant organized the files."),
        ("associate", "verb", "To connect in the mind", "People associate summer with vacation."),
        ("association", "noun", "A group organized for a purpose", "The association holds annual meetings."),
        ("assume", "verb", "To suppose without proof", "Do not assume anything."),
        ("assumption", "noun", "Something taken for granted", "The assumption proved incorrect."),
        ("assure", "verb", "To tell positively", "I assure you it is safe."),
        ("atmosphere", "noun", "The air surrounding Earth", "The atmosphere protects us from radiation."),
        ("attach", "verb", "To fasten or join", "Attach the document to the email."),
        ("attack", "verb", "To act aggressively against", "The army launched an attack."),
        ("attempt", "verb", "To try to do something", "She attempted to climb the mountain."),
        ("attend", "verb", "To be present at", "Please attend the meeting."),
        ("attention", "noun", "Notice or awareness", "Pay attention to the instructions."),
        ("attitude", "noun", "A settled way of thinking", "A positive attitude helps."),
        ("attorney", "noun", "A lawyer", "The attorney represented the client."),
        ("attract", "verb", "To draw interest", "The show attracted large crowds."),
        ("attractive", "adjective", "Pleasing in appearance", "The offer is very attractive."),
        ("attribute", "verb", "To regard as caused by", "Success can be attributed to hard work."),
        ("audience", "noun", "People watching a performance", "The audience applauded loudly."),
        ("author", "noun", "A writer of a book", "The author signed copies of his book."),
        ("authority", "noun", "The power to give orders", "The police have authority to arrest."),
        ("available", "adjective", "Ready for use", "The room is available now."),
        ("average", "adjective", "Typical or ordinary", "The average score was 75."),
        ("avoid", "verb", "To keep away from", "Avoid eating too much sugar."),
        ("award", "noun", "A prize for achievement", "She received an award for excellence."),
        ("aware", "adjective", "Having knowledge of", "Be aware of your surroundings."),
        ("awareness", "noun", "Knowledge or perception", "Raise awareness about health issues."),
        ("away", "adverb", "At a distance", "The store is two miles away."),
        ("baby", "noun", "A very young child", "The baby is sleeping peacefully."),
        ("back", "noun", "The rear surface of the body", "He hurt his back lifting boxes."),
        ("background", "noun", "A persons past experiences", "Her background is in finance."),
        ("bad", "adjective", "Of poor quality", "The weather was bad yesterday."),
        ("badly", "adverb", "In a severe manner", "He was badly injured."),
        ("bag", "noun", "A container for carrying things", "She packed her bag for the trip."),
        ("balance", "noun", "An even distribution of weight", "Maintain balance while walking."),
        ("ball", "noun", "A round object used in games", "Kick the ball into the goal."),
        ("ban", "verb", "To officially prohibit", "The city banned smoking in parks."),
        ("band", "noun", "A group of musicians", "The band played rock music."),
        ("bank", "noun", "A financial institution", "Deposit money at the bank."),
        ("bar", "noun", "A long rigid piece", "The metal bar was heavy."),
        ("barrier", "noun", "Something that blocks passage", "Language can be a barrier."),
        ("base", "noun", "The bottom support", "The statue has a marble base."),
        ("basic", "adjective", "Forming an essential foundation", "Learn the basic rules first."),
        ("basically", "adverb", "In essence", "Basically, the plan is simple."),
        ("basis", "noun", "The underlying support", "Trust is the basis of friendship."),
        ("battery", "noun", "A device storing electrical energy", "The battery needs charging."),
        ("battle", "noun", "A fight between armed forces", "The battle lasted three days."),
        ("beach", "noun", "A sandy shore by the sea", "We spent the day at the beach."),
        ("bear", "verb", "To carry or support", "I cannot bear the pain anymore."),
        ("beat", "verb", "To strike repeatedly", "The drummer beat the drums."),
        ("beautiful", "adjective", "Pleasing to the senses", "The sunset was beautiful."),
        ("beauty", "noun", "A quality that pleases", "Natural beauty surrounds us."),
        ("become", "verb", "To begin to be", "She wants to become a doctor."),
        ("bed", "noun", "Furniture for sleeping", "Go to bed early tonight."),
        ("bedroom", "noun", "A room for sleeping", "The bedroom is upstairs."),
        ("before", "preposition", "Earlier than", "Finish your work before lunch."),
        ("begin", "verb", "To start", "Classes begin next week."),
        ("beginning", "noun", "The start of something", "This is just the beginning."),
        ("behavior", "noun", "The way one acts", "Good behavior is expected."),
        ("behind", "preposition", "At the back of", "The garden is behind the house."),
        ("belief", "noun", "An acceptance that something is true", "Religious beliefs vary widely."),
        ("believe", "verb", "To accept as true", "I believe in hard work."),
        ("belong", "verb", "To be a member of", "I belong to this club."),
    ],
    "80-100": [
        ("below", "preposition", "At a lower level than", "The temperature dropped below zero."),
        ("belt", "noun", "A strip worn around the waist", "Tighten your seat belt."),
        ("bench", "noun", "A long seat", "Sit on the park bench."),
        ("bend", "verb", "To curve or flex", "Bend your knees when lifting."),
        ("beneath", "preposition", "Directly under", "The treasure lies beneath the surface."),
        ("beneficial", "adjective", "Resulting in good", "Exercise is beneficial to health."),
        ("benefit", "noun", "An advantage or profit", "There are many benefits to reading."),
        ("beside", "preposition", "Next to", "Sit beside me."),
        ("besides", "preposition", "In addition to", "Besides English, she speaks French."),
        ("best", "adjective", "Of the highest quality", "This is the best solution."),
        ("better", "adjective", "Of higher quality", "Practice makes you better."),
        ("between", "preposition", "In the space separating two things", "Choose between these options."),
        ("beyond", "preposition", "Further than", "The village is beyond the mountains."),
        ("bias", "noun", "Prejudice in favor or against", "The study showed researcher bias."),
        ("big", "adjective", "Of considerable size", "The elephant is a big animal."),
        ("bill", "noun", "A statement of charges", "Pay the electricity bill."),
        ("billion", "number", "A thousand million", "The project costs billions of dollars."),
        ("bind", "verb", "To tie or fasten", "Bind the papers together."),
        ("biological", "adjective", "Relating to biology", "Biological research is advancing."),
        ("biology", "noun", "The study of living organisms", "She majored in biology."),
        ("bird", "noun", "A feathered animal", "The bird flew south for winter."),
        ("birth", "noun", "The emergence of a baby", "Celebrate the birth of a child."),
        ("bit", "noun", "A small piece or amount", "Wait a bit longer."),
        ("bite", "verb", "To cut with teeth", "Do not bite your nails."),
        ("black", "adjective", "The darkest color", "She wore a black dress."),
        ("blade", "noun", "The flat cutting edge", "The blade of the knife is sharp."),
        ("blame", "verb", "To assign responsibility for a fault", "Do not blame others for your mistakes."),
        ("blank", "adjective", "Not written or printed on", "Leave the form blank."),
        ("blind", "adjective", "Unable to see", "The blind man uses a cane."),
        ("block", "noun", "A solid piece of material", "A block of ice melted."),
        ("blood", "noun", "The red liquid in the body", "Blood carries oxygen to cells."),
        ("blow", "verb", "To move air", "The wind blows leaves around."),
        ("blue", "adjective", "The color of the sky", "The ocean looks blue."),
        ("board", "noun", "A flat piece of material", "Write on the board."),
        ("boat", "noun", "A watercraft", "We rented a boat for fishing."),
        ("body", "noun", "The physical structure of a person", "Exercise keeps your body healthy."),
        ("bomb", "noun", "An explosive device", "The bomb was safely defused."),
        ("bond", "noun", "A connection or tie", "Family bonds are important."),
        ("bone", "noun", "The hard tissue in the body", "Calcium strengthens bones."),
        ("book", "noun", "A written work", "I read a book every week."),
        ("boom", "noun", "A period of rapid growth", "The economic boom created jobs."),
        ("boot", "noun", "A type of footwear", "Wear boots in the rain."),
        ("border", "noun", "The edge or boundary", "They crossed the border."),
        ("born", "adjective", "Brought into existence", "She was born in Seoul."),
        ("borrow", "verb", "To take with permission to return", "May I borrow your pen?"),
        ("boss", "noun", "A person in charge", "The boss called a meeting."),
        ("both", "determiner", "Two together", "Both options are acceptable."),
        ("bother", "verb", "To annoy or disturb", "Do not bother me while I work."),
        ("bottle", "noun", "A container for liquids", "Fill the bottle with water."),
        ("bottom", "noun", "The lowest part", "Sign at the bottom of the page."),
        ("boundary", "noun", "A line marking limits", "Respect personal boundaries."),
        ("bowl", "noun", "A round deep dish", "Pour cereal into the bowl."),
        ("box", "noun", "A container with flat sides", "Pack your belongings in a box."),
        ("boy", "noun", "A male child", "The boy plays soccer."),
        ("brain", "noun", "The organ inside the head", "The brain controls body functions."),
        ("branch", "noun", "A part extending from the main body", "The bird sat on a branch."),
        ("brand", "noun", "A type of product", "This brand is popular."),
        ("brave", "adjective", "Showing courage", "The brave firefighter saved lives."),
        ("bread", "noun", "A baked food made from flour", "Fresh bread smells wonderful."),
        ("break", "verb", "To separate into pieces", "Do not break the glass."),
        ("breakfast", "noun", "The first meal of the day", "Eat a healthy breakfast."),
        ("breath", "noun", "Air taken into the lungs", "Take a deep breath."),
        ("breathe", "verb", "To take air into the lungs", "Breathe slowly and relax."),
        ("breed", "verb", "To produce offspring", "Farmers breed cattle."),
        ("brick", "noun", "A block used for building", "The house is made of brick."),
        ("bridge", "noun", "A structure over water", "The bridge connects two cities."),
        ("brief", "adjective", "Of short duration", "Give a brief summary."),
        ("briefly", "adverb", "For a short time", "He spoke briefly about the topic."),
        ("bright", "adjective", "Giving out much light", "The sun is bright today."),
        ("brilliant", "adjective", "Exceptionally clever", "She has a brilliant mind."),
        ("bring", "verb", "To carry to a place", "Bring your ID to the exam."),
        ("broad", "adjective", "Wide in extent", "The river is broad here."),
        ("broadcast", "verb", "To transmit by radio or TV", "The news was broadcast live."),
        ("brother", "noun", "A male sibling", "My brother is older than me."),
        ("brown", "adjective", "A color between red and yellow", "She has brown eyes."),
        ("brush", "noun", "A tool with bristles", "Use a brush to clean."),
        ("budget", "noun", "An estimate of income and expenses", "Stick to your budget."),
        ("build", "verb", "To construct", "They plan to build a house."),
        ("building", "noun", "A structure with walls and roof", "The building is 20 stories tall."),
        ("bunch", "noun", "A group of things", "A bunch of flowers looks beautiful."),
        ("burden", "noun", "A heavy load", "Do not be a burden to others."),
        ("burn", "verb", "To be on fire", "Do not burn yourself with hot water."),
        ("burst", "verb", "To break open suddenly", "The balloon burst loudly."),
        ("bury", "verb", "To put in the ground", "They buried the time capsule."),
        ("bus", "noun", "A large motor vehicle", "Take the bus to work."),
        ("business", "noun", "Commercial activity", "She started her own business."),
        ("busy", "adjective", "Actively engaged", "I am too busy to meet today."),
        ("but", "conjunction", "Used to introduce contrast", "I tried, but I failed."),
        ("butter", "noun", "A dairy product", "Spread butter on the toast."),
        ("button", "noun", "A small fastener", "Press the button to start."),
        ("buy", "verb", "To obtain in exchange for money", "I need to buy groceries."),
        ("buyer", "noun", "A person who purchases", "The buyer inspected the property."),
        ("cabinet", "noun", "A piece of furniture with shelves", "Store dishes in the cabinet."),
        ("cable", "noun", "A thick rope or wire", "The cable TV was installed."),
        ("cake", "noun", "A sweet baked dessert", "She baked a birthday cake."),
        ("calculate", "verb", "To determine mathematically", "Calculate the total cost."),
        ("calculation", "noun", "A mathematical determination", "Check your calculations carefully."),
        ("calendar", "noun", "A chart showing days and months", "Mark the date on the calendar."),
        ("call", "verb", "To contact by phone", "I will call you tomorrow."),
        ("calm", "adjective", "Not showing agitation", "Stay calm during emergencies."),
        ("camera", "noun", "A device for taking photographs", "The camera captured the moment."),
    ],
    "100+": [
        ("camp", "noun", "A place for temporary lodging", "Summer camp is fun for kids."),
        ("campaign", "noun", "An organized effort", "The marketing campaign was successful."),
        ("campus", "noun", "The grounds of a school", "The campus has many buildings."),
        ("cancel", "verb", "To decide not to proceed", "Cancel the appointment if necessary."),
        ("cancer", "noun", "A serious disease", "Research continues to find a cure for cancer."),
        ("candidate", "noun", "A person applying for a position", "The candidate has strong qualifications."),
        ("cap", "noun", "A type of hat", "Wear a cap in the sun."),
        ("capability", "noun", "The ability to do something", "The system has advanced capabilities."),
        ("capable", "adjective", "Having the ability", "She is capable of leading the team."),
        ("capacity", "noun", "The maximum amount", "The stadium has a capacity of 50000."),
        ("capital", "noun", "The main city of a country", "Seoul is the capital of South Korea."),
        ("captain", "noun", "The leader of a team", "The captain led the ship safely."),
        ("capture", "verb", "To take into custody", "The police captured the criminal."),
        ("car", "noun", "A motor vehicle", "She drives to work by car."),
        ("carbon", "noun", "A chemical element", "Carbon dioxide affects climate."),
        ("card", "noun", "A piece of stiff paper", "Send a birthday card."),
        ("care", "noun", "The provision of what is necessary", "Take care of your health."),
        ("career", "noun", "An occupation over a period", "She built a successful career."),
        ("careful", "adjective", "Done with attention", "Be careful when crossing the street."),
        ("carefully", "adverb", "With great attention", "Read the instructions carefully."),
        ("carrier", "noun", "A person or thing that carries", "The mail carrier delivers packages."),
        ("carry", "verb", "To support and move", "Carry the bags to the car."),
        ("case", "noun", "An instance or example", "In this case, we should proceed."),
        ("cash", "noun", "Money in coins or notes", "I prefer to pay in cash."),
        ("cast", "verb", "To throw or project", "The actor was cast in the lead role."),
        ("cat", "noun", "A small domesticated animal", "The cat sleeps on the couch."),
        ("catch", "verb", "To capture or seize", "Catch the ball with both hands."),
        ("category", "noun", "A class or division", "Books are organized by category."),
        ("cause", "noun", "A reason for an action", "Identify the cause of the problem."),
        ("ceiling", "noun", "The upper surface of a room", "Paint the ceiling white."),
        ("celebrate", "verb", "To observe a special occasion", "Celebrate your achievements."),
        ("celebration", "noun", "The act of celebrating", "The celebration lasted all night."),
        ("celebrity", "noun", "A famous person", "The celebrity signed autographs."),
        ("cell", "noun", "The basic unit of life", "Cells divide to create new cells."),
        ("center", "noun", "The middle point", "The statue stands in the center."),
        ("central", "adjective", "At the center", "The central location is convenient."),
        ("century", "noun", "A period of 100 years", "Technology advanced in the 21st century."),
        ("ceremony", "noun", "A formal event", "The wedding ceremony was beautiful."),
        ("certain", "adjective", "Known for sure", "I am certain about the facts."),
        ("certainly", "adverb", "Without doubt", "I will certainly attend."),
        ("chain", "noun", "A series of connected links", "The dog was on a chain."),
        ("chair", "noun", "A seat for one person", "Pull up a chair and sit down."),
        ("chairman", "noun", "The leader of a meeting", "The chairman called the meeting to order."),
        ("challenge", "noun", "A difficult task", "Learning a language is a challenge."),
        ("chamber", "noun", "A room used for a purpose", "The chamber was used for meetings."),
        ("champion", "noun", "A winner of a competition", "The champion defended the title."),
        ("championship", "noun", "A competition for the title", "The championship game was exciting."),
        ("chance", "noun", "A possibility of something happening", "Take a chance and try."),
        ("change", "verb", "To make different", "Change your approach if needed."),
        ("channel", "noun", "A medium for communication", "Switch to another TV channel."),
        ("chapter", "noun", "A main division of a book", "Read chapter five tonight."),
        ("character", "noun", "A person in a story", "The main character is brave."),
        ("characteristic", "noun", "A typical feature", "Honesty is her main characteristic."),
        ("characterize", "verb", "To describe the qualities of", "The era was characterized by change."),
        ("charge", "verb", "To demand payment", "The hotel charges extra for parking."),
        ("charity", "noun", "An organization helping those in need", "Donate to charity regularly."),
        ("chart", "noun", "A diagram showing information", "The chart displays sales data."),
        ("chase", "verb", "To pursue in order to catch", "The dog chased the cat."),
        ("cheap", "adjective", "Low in price", "The product is cheap but good quality."),
        ("check", "verb", "To examine for accuracy", "Check your answers before submitting."),
        ("chemical", "adjective", "Relating to chemistry", "Chemical reactions occur constantly."),
        ("chest", "noun", "The front of the body", "He felt pain in his chest."),
        ("chicken", "noun", "A domestic fowl", "We had chicken for dinner."),
        ("chief", "adjective", "Most important", "The chief concern is safety."),
        ("child", "noun", "A young human", "The child played in the park."),
        ("childhood", "noun", "The state of being a child", "Childhood memories are precious."),
        ("chip", "noun", "A small piece", "The computer chip is tiny but powerful."),
        ("chocolate", "noun", "A sweet food from cacao", "Dark chocolate is healthy in moderation."),
        ("choice", "noun", "An act of selecting", "Make the right choice."),
        ("choose", "verb", "To select from options", "Choose wisely."),
        ("church", "noun", "A building for worship", "They attend church on Sundays."),
        ("circle", "noun", "A round shape", "Draw a circle on the paper."),
        ("circumstance", "noun", "A condition connected with an event", "Under normal circumstances we would agree."),
        ("citizen", "noun", "A person who belongs to a country", "Every citizen has rights."),
        ("city", "noun", "A large town", "The city is crowded."),
        ("civil", "adjective", "Relating to citizens", "Civil rights are protected by law."),
        ("claim", "verb", "To assert or demand", "He claimed his innocence."),
        ("class", "noun", "A group of students", "The class starts at 9 AM."),
        ("classic", "adjective", "Of the highest quality over time", "Shakespeare wrote many classic plays."),
        ("classroom", "noun", "A room for teaching", "The classroom has 30 desks."),
        ("clean", "adjective", "Free from dirt", "Keep your room clean."),
        ("clear", "adjective", "Easy to understand", "The instructions are clear."),
        ("clearly", "adverb", "In a clear manner", "Speak clearly so everyone can hear."),
        ("client", "noun", "A customer", "The lawyer met with her client."),
        ("climate", "noun", "The weather conditions of an area", "Climate change affects everyone."),
        ("climb", "verb", "To go up", "Climb the stairs to the second floor."),
        ("clock", "noun", "A device that shows time", "The clock struck midnight."),
        ("close", "verb", "To shut", "Close the door quietly."),
        ("closely", "adverb", "In a close manner", "Watch the process closely."),
        ("clothes", "noun", "Items worn on the body", "Wash your clothes regularly."),
        ("cloud", "noun", "A mass of water vapor in the sky", "The cloud blocked the sun."),
        ("club", "noun", "An organization for people with common interests", "Join the book club."),
        ("coach", "noun", "A person who trains athletes", "The coach motivated the team."),
        ("coal", "noun", "A black solid fuel", "Coal was used to heat homes."),
        ("coalition", "noun", "An alliance for combined action", "The parties formed a coalition."),
        ("coast", "noun", "The edge of land near the sea", "We drove along the coast."),
        ("coat", "noun", "An outer garment", "Wear a coat in winter."),
        ("code", "noun", "A system of rules or symbols", "The programmer wrote efficient code."),
        ("coffee", "noun", "A hot beverage", "I drink coffee every morning."),
        ("cognitive", "adjective", "Relating to mental processes", "Cognitive skills improve with practice."),
    ]
}

def translate_text(text, target_lang):
    try:
        translator = GoogleTranslator(source='en', target=target_lang)
        return translator.translate(text)
    except Exception as e:
        print(f"Translation error for {target_lang}: {e}")
        return text

def generate_words():
    all_words = []
    word_id = 1
    
    for level, words in TOEFL_WORDS.items():
        print(f"Processing level {level}...")
        for word_data in words:
            word, pos, definition, example = word_data
            
            # Translate
            ko_def = translate_text(definition, 'ko')
            ko_ex = translate_text(example, 'ko')
            
            ja_def = translate_text(definition, 'ja')
            ja_ex = translate_text(example, 'ja')
            
            zh_def = translate_text(definition, 'zh-CN')
            zh_ex = translate_text(example, 'zh-CN')
            
            word_entry = {
                "id": word_id,
                "word": word,
                "level": level,
                "partOfSpeech": pos,
                "definition": definition,
                "example": example,
                "category": "Academic",
                "translations": {
                    "ko": {"definition": ko_def, "example": ko_ex},
                    "ja": {"definition": ja_def, "example": ja_ex},
                    "zh": {"definition": zh_def, "example": zh_ex}
                }
            }
            all_words.append(word_entry)
            word_id += 1
            
            if word_id % 20 == 0:
                print(f"Processed {word_id} words...")
                time.sleep(0.5)  # Rate limiting
    
    return all_words

if __name__ == "__main__":
    print("Starting word generation...")
    words = generate_words()
    
    with open('assets/data/words.json', 'w', encoding='utf-8') as f:
        json.dump(words, f, ensure_ascii=False, indent=2)
    
    # Create level files
    for level in ["0-60", "60-80", "80-100", "100+"]:
        level_words = [w for w in words if w["level"] == level]
        filename = f"assets/data/{level.replace('+', 'plus').replace('-', '_')}_words.json"
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(level_words, f, ensure_ascii=False, indent=2)
        print(f"Created {filename} with {len(level_words)} words")
    
    print(f"Total: {len(words)} words generated!")
