# 100+ Level Words Part 3 (401-600)
WORDS_100_PLUS_PART3 = [
    ("coy", "adjective", "Reluctant to make a commitment", "A coy response."),
    ("cozen", "verb", "To trick or deceive", "Cozen into agreement."),
    ("crass", "adjective", "Lacking sensitivity", "A crass remark."),
    ("craven", "adjective", "Cowardly", "A craven act."),
    ("credence", "noun", "Belief in something as true", "Give credence to."),
    ("credulous", "adjective", "Too ready to believe", "A credulous person."),
    ("creed", "noun", "A set of beliefs", "A religious creed."),
    ("crescendo", "noun", "The loudest point", "Reach a crescendo."),
    ("crestfallen", "adjective", "Sad and disappointed", "Look crestfallen."),
    ("criterion", "noun", "A standard for judgment", "Meet the criterion."),
    ("cryptic", "adjective", "Having hidden meaning", "A cryptic message."),
    ("crystallize", "verb", "To make definite", "Ideas crystallize."),
    ("culinary", "adjective", "Relating to cooking", "Culinary skills."),
    ("culminate", "verb", "To reach a climax", "Culminate in success."),
    ("culpable", "adjective", "Deserving blame", "Culpable negligence."),
    ("cumbersome", "adjective", "Heavy and awkward", "A cumbersome process."),
    ("cumulative", "adjective", "Increasing by addition", "Cumulative effect."),
    ("curmudgeon", "noun", "A bad-tempered person", "An old curmudgeon."),
    ("cursory", "adjective", "Hasty and superficial", "A cursory glance."),
    ("curtail", "verb", "To reduce", "Curtail expenses."),
    ("cynical", "adjective", "Believing the worst of people", "A cynical view."),
    ("dais", "noun", "A low platform", "Stand on the dais."),
    ("dalliance", "noun", "A casual romantic affair", "A brief dalliance."),
    ("dapper", "adjective", "Neat in dress", "A dapper gentleman."),
    ("daunting", "adjective", "Seeming difficult", "A daunting task."),
    ("dawdle", "verb", "To waste time", "Don't dawdle."),
    ("deadlock", "noun", "A standstill", "Reach a deadlock."),
    ("dearth", "noun", "A scarcity", "A dearth of information."),
    ("debacle", "noun", "A sudden disaster", "A complete debacle."),
    ("debase", "verb", "To reduce in quality", "Debase the currency."),
    ("debilitate", "verb", "To weaken", "Debilitating illness."),
    ("debunk", "verb", "To expose as false", "Debunk myths."),
    ("decadence", "noun", "Moral deterioration", "Cultural decadence."),
    ("decimate", "verb", "To destroy a large part of", "Decimate the population."),
    ("decipher", "verb", "To decode", "Decipher the code."),
    ("declaim", "verb", "To speak rhetorically", "Declaim against injustice."),
    ("decorous", "adjective", "Dignified and proper", "Decorous behavior."),
    ("decorum", "noun", "Dignified behavior", "Maintain decorum."),
    ("decree", "noun", "An official order", "Issue a decree."),
    ("decrepit", "adjective", "Worn out by age", "A decrepit building."),
    ("decry", "verb", "To publicly denounce", "Decry violence."),
    ("deduce", "verb", "To arrive at by reasoning", "Deduce the answer."),
    ("deface", "verb", "To spoil the appearance", "Deface public property."),
    ("defamation", "noun", "Damaging good reputation", "Sue for defamation."),
    ("default", "noun", "Failure to act", "Win by default."),
    ("defer", "verb", "To put off", "Defer judgment."),
    ("deference", "noun", "Humble submission", "Show deference."),
    ("deferential", "adjective", "Showing respect", "A deferential tone."),
    ("defiant", "adjective", "Openly resistant", "A defiant attitude."),
    ("defile", "verb", "To make dirty", "Defile sacred ground."),
    ("definitive", "adjective", "Decisive", "A definitive answer."),
    ("deft", "adjective", "Skillful", "A deft touch."),
    ("defunct", "adjective", "No longer existing", "A defunct company."),
    ("degrade", "verb", "To treat disrespectfully", "Degrade human dignity."),
    ("deify", "verb", "To worship as a god", "Deify celebrities."),
    ("deign", "verb", "To do something beneath one's dignity", "Deign to respond."),
    ("delectable", "adjective", "Delicious", "A delectable meal."),
    ("delegate", "verb", "To entrust to another", "Delegate responsibility."),
    ("delete", "verb", "To remove", "Delete the file."),
    ("deleterious", "adjective", "Causing harm", "Deleterious effects."),
    ("deliberate", "adjective", "Done consciously", "A deliberate act."),
    ("delineate", "verb", "To describe precisely", "Delineate boundaries."),
    ("delirium", "noun", "An acutely disturbed state", "In a state of delirium."),
    ("delude", "verb", "To deceive", "Delude yourself."),
    ("deluge", "noun", "A severe flood", "A deluge of complaints."),
    ("delusion", "noun", "A false belief", "A dangerous delusion."),
    ("delve", "verb", "To research intensively", "Delve into history."),
    ("demagogue", "noun", "A leader who appeals to emotions", "A political demagogue."),
    ("demean", "verb", "To lower in dignity", "Demean oneself."),
    ("demeanor", "noun", "Outward behavior", "A calm demeanor."),
    ("demise", "noun", "A person's death", "The demise of the company."),
    ("demolish", "verb", "To destroy completely", "Demolish the building."),
    ("demonstrable", "adjective", "Capable of being shown", "Demonstrable facts."),
    ("demote", "verb", "To lower in rank", "Demoted for poor performance."),
    ("demur", "verb", "To raise objections", "Demur at the suggestion."),
    ("demure", "adjective", "Reserved and modest", "A demure smile."),
    ("denigrate", "verb", "To criticize unfairly", "Denigrate achievements."),
    ("denizen", "noun", "An inhabitant", "A denizen of the deep."),
    ("denounce", "verb", "To publicly declare wrong", "Denounce corruption."),
    ("depict", "verb", "To represent in art", "Depict a scene."),
    ("deplete", "verb", "To use up", "Deplete resources."),
    ("deplore", "verb", "To feel strong disapproval", "Deplore violence."),
    ("deploy", "verb", "To move into position", "Deploy troops."),
    ("depose", "verb", "To remove from power", "Depose the dictator."),
    ("depravity", "noun", "Moral corruption", "Acts of depravity."),
    ("deprecate", "verb", "To express disapproval", "Deprecate the practice."),
    ("depreciate", "verb", "To diminish in value", "Assets depreciate."),
    ("depredation", "noun", "An act of attacking", "Environmental depredation."),
    ("derelict", "adjective", "Abandoned", "A derelict building."),
    ("deride", "verb", "To express contempt for", "Deride the proposal."),
    ("derivative", "adjective", "Imitative", "Derivative work."),
    ("dermatology", "noun", "Study of skin diseases", "Consult dermatology."),
    ("derogatory", "adjective", "Showing disrespect", "Derogatory remarks."),
    ("descend", "verb", "To move downward", "Descend the stairs."),
    ("descent", "noun", "An act of descending", "A steep descent."),
    ("desecrate", "verb", "To treat disrespectfully", "Desecrate a grave."),
    ("desiccate", "verb", "To dry out completely", "Desiccated fruit."),
    ("designate", "verb", "To appoint", "Designate a successor."),
    ("desolate", "adjective", "Bleak and empty", "A desolate landscape."),
    ("despicable", "adjective", "Deserving hatred", "A despicable act."),
    ("despise", "verb", "To feel contempt for", "Despise dishonesty."),
    ("despondent", "adjective", "In low spirits", "Feel despondent."),
    ("despot", "noun", "A tyrannical ruler", "A cruel despot."),
    ("destine", "verb", "To intend for a purpose", "Destined for greatness."),
    ("destitute", "adjective", "Extremely poor", "Left destitute."),
    ("desultory", "adjective", "Lacking purpose", "Desultory conversation."),
    ("detain", "verb", "To keep in custody", "Detain for questioning."),
    ("deter", "verb", "To discourage", "Deter crime."),
    ("deteriorate", "verb", "To become worse", "Health deteriorated."),
    ("determinate", "adjective", "Having exact limits", "A determinate sentence."),
    ("detest", "verb", "To dislike intensely", "Detest violence."),
    ("detract", "verb", "To diminish the worth of", "Detract from merit."),
    ("detrimental", "adjective", "Tending to cause harm", "Detrimental effects."),
    ("devastate", "verb", "To destroy or ruin", "Devastated by the news."),
    ("deviate", "verb", "To depart from the norm", "Deviate from the plan."),
    ("devious", "adjective", "Showing a skillful use of trickery", "A devious plan."),
    ("devise", "verb", "To plan or invent", "Devise a strategy."),
    ("devoid", "adjective", "Entirely lacking", "Devoid of emotion."),
    ("devolve", "verb", "To transfer to a successor", "Devolve power."),
    ("devout", "adjective", "Having deep religious feeling", "A devout believer."),
    ("dexterous", "adjective", "Showing skill", "Dexterous hands."),
    ("diabolical", "adjective", "Characteristic of the devil", "A diabolical plan."),
    ("diagnose", "verb", "To identify the nature of an illness", "Diagnose the disease."),
    ("dialect", "noun", "A form of a language", "A regional dialect."),
    ("dichotomy", "noun", "A division into two parts", "A false dichotomy."),
    ("dictate", "verb", "To lay down authoritatively", "Dictate terms."),
    ("didactic", "adjective", "Intended to teach", "A didactic approach."),
    ("diffident", "adjective", "Modest and shy", "A diffident manner."),
    ("diffuse", "verb", "To spread widely", "Diffuse information."),
    ("digress", "verb", "To depart from the main subject", "Don't digress."),
    ("dilapidated", "adjective", "In a state of ruin", "A dilapidated house."),
    ("dilate", "verb", "To make wider", "Pupils dilate."),
    ("dilatory", "adjective", "Slow to act", "Dilatory tactics."),
    ("dilemma", "noun", "A difficult choice", "Face a dilemma."),
    ("diligent", "adjective", "Showing care and effort", "A diligent worker."),
    ("dilute", "verb", "To make weaker", "Dilute the solution."),
    ("diminish", "verb", "To make less", "Diminish importance."),
    ("diminution", "noun", "A reduction", "A diminution of power."),
    ("din", "noun", "A loud noise", "The din of traffic."),
    ("dire", "adjective", "Extremely serious", "Dire consequences."),
    ("dirge", "noun", "A mournful song", "Sing a dirge."),
    ("disaffected", "adjective", "Dissatisfied", "Disaffected voters."),
    ("disband", "verb", "To break up", "Disband the group."),
    ("discard", "verb", "To throw away", "Discard old clothes."),
    ("discern", "verb", "To perceive", "Discern the truth."),
    ("discerning", "adjective", "Having good judgment", "A discerning eye."),
    ("discharge", "verb", "To release from duty", "Discharge from the army."),
    ("disciple", "noun", "A follower", "A devoted disciple."),
    ("discipline", "noun", "Training to obey rules", "Strict discipline."),
    ("disclaim", "verb", "To deny responsibility", "Disclaim any knowledge."),
    ("disclose", "verb", "To make known", "Disclose information."),
    ("discombobulate", "verb", "To confuse", "Completely discombobulated."),
    ("discomfit", "verb", "To make uneasy", "Discomfited by criticism."),
    ("disconcert", "verb", "To unsettle", "Disconcerted by the question."),
    ("discord", "noun", "Disagreement", "Sow discord."),
    ("discordant", "adjective", "Disagreeing", "Discordant views."),
    ("discount", "verb", "To disregard as unimportant", "Discount the possibility."),
    ("discourse", "noun", "Written or spoken communication", "Political discourse."),
    ("discredit", "verb", "To damage the reputation of", "Discredit opponents."),
    ("discreet", "adjective", "Careful not to attract attention", "A discreet inquiry."),
    ("discrepancy", "noun", "An inconsistency", "A discrepancy in accounts."),
    ("discrete", "adjective", "Individually separate", "Discrete components."),
    ("discretion", "noun", "The quality of being discreet", "Use discretion."),
    ("discriminate", "verb", "To recognize a distinction", "Discriminate between options."),
    ("discursive", "adjective", "Digressing from subject to subject", "A discursive essay."),
    ("disdain", "noun", "The feeling that someone is unworthy", "Treat with disdain."),
    ("disenfranchise", "verb", "To deprive of a right", "Disenfranchised voters."),
    ("disengage", "verb", "To separate", "Disengage from conflict."),
    ("disfigure", "verb", "To spoil the appearance", "Disfigured by scars."),
    ("disgruntled", "adjective", "Angry or dissatisfied", "A disgruntled employee."),
    ("disillusion", "verb", "To free from illusion", "Disillusioned with politics."),
    ("disingenuous", "adjective", "Not candid or sincere", "A disingenuous claim."),
    ("disintegrate", "verb", "To break into small parts", "The coalition disintegrated."),
    ("disinterested", "adjective", "Not influenced by personal interest", "A disinterested party."),
    ("disjointed", "adjective", "Lacking coherence", "A disjointed narrative."),
    ("dislodge", "verb", "To knock out of position", "Dislodge the stone."),
    ("dismal", "adjective", "Depressing", "A dismal failure."),
    ("dismantle", "verb", "To take apart", "Dismantle the machine."),
    ("dismay", "noun", "Concern and distress", "To my dismay."),
    ("dismiss", "verb", "To send away", "Dismiss from employment."),
    ("disparage", "verb", "To regard as being of little worth", "Disparage achievements."),
    ("disparate", "adjective", "Essentially different", "Disparate views."),
    ("disparity", "noun", "A great difference", "Income disparity."),
    ("dispassionate", "adjective", "Not influenced by emotion", "A dispassionate analysis."),
    ("dispatch", "verb", "To send off quickly", "Dispatch a message."),
    ("dispel", "verb", "To drive away", "Dispel doubts."),
    ("dispense", "verb", "To distribute", "Dispense medication."),
    ("disperse", "verb", "To scatter", "The crowd dispersed."),
    ("displace", "verb", "To take the place of", "Displace workers."),
    ("disposition", "noun", "A person's inherent qualities", "A cheerful disposition."),
    ("disproportion", "noun", "A lack of proportion", "A disproportion of wealth."),
    ("disprove", "verb", "To prove to be false", "Disprove the theory."),
    ("dispute", "verb", "To argue about", "Dispute the claim."),
    ("disquiet", "noun", "A feeling of anxiety", "Public disquiet."),
    ("disregard", "verb", "To pay no attention to", "Disregard warnings."),
    ("disrepute", "noun", "A state of bad reputation", "Fall into disrepute."),
    ("dissect", "verb", "To cut apart for examination", "Dissect an argument."),
    ("dissemble", "verb", "To conceal true feelings", "Dissemble emotions."),
    ("disseminate", "verb", "To spread widely", "Disseminate information."),
    ("dissension", "noun", "Disagreement", "Internal dissension."),
    ("dissent", "noun", "Disagreement with official opinion", "Express dissent."),
    ("dissertation", "noun", "A long essay", "Write a dissertation."),
    ("dissident", "noun", "A person who opposes official policy", "A political dissident."),
    ("dissipate", "verb", "To disperse or scatter", "Clouds dissipated."),
    ("dissociate", "verb", "To disconnect", "Dissociate from the group."),
    ("dissolute", "adjective", "Indulging in immoral activities", "A dissolute lifestyle."),
    ("dissonance", "noun", "Lack of harmony", "Cognitive dissonance."),
    ("dissuade", "verb", "To persuade not to do", "Dissuade from action."),
    ("distend", "verb", "To swell from pressure", "A distended stomach."),
    ("distill", "verb", "To extract the essential meaning", "Distill the essence."),
    ("distinct", "adjective", "Recognizably different", "A distinct advantage."),
    ("distinction", "noun", "A difference", "A fine distinction."),
    ("distinctive", "adjective", "Characteristic", "A distinctive style."),
    ("distinguish", "verb", "To recognize as different", "Distinguish between options."),
    ("distort", "verb", "To give a misleading account", "Distort the facts."),
    ("distract", "verb", "To divert attention", "Distracted by noise."),
    ("distraught", "adjective", "Deeply upset", "Distraught with worry."),
    ("diurnal", "adjective", "Of or during the day", "Diurnal animals."),
    ("diverge", "verb", "To separate from a main route", "Opinions diverge."),
    ("divergent", "adjective", "Tending to be different", "Divergent views."),
    ("diverse", "adjective", "Showing variety", "A diverse population."),
    ("divest", "verb", "To deprive of power", "Divest of authority."),
    ("divine", "adjective", "Of God", "Divine intervention."),
    ("divulge", "verb", "To make known", "Divulge secrets."),
    ("docile", "adjective", "Ready to accept instruction", "A docile student."),
    ("doctrine", "noun", "A belief held by a group", "Political doctrine."),
    ("document", "verb", "To record in detail", "Document the process."),
    ("dodder", "verb", "To tremble while walking", "Doddering steps."),
    ("dogma", "noun", "A principle laid down by an authority", "Religious dogma."),
    ("dogmatic", "adjective", "Expressing opinions as facts", "A dogmatic approach."),
    ("doldrums", "noun", "A state of inactivity", "In the doldrums."),
    ("doleful", "adjective", "Expressing sorrow", "A doleful expression."),
    ("domain", "noun", "A sphere of activity", "The public domain."),
    ("domicile", "noun", "A place of residence", "Establish domicile."),
    ("dormant", "adjective", "Temporarily inactive", "A dormant volcano."),
    ("dote", "verb", "To be excessively fond of", "Dote on grandchildren."),
    ("dour", "adjective", "Stern and gloomy", "A dour expression."),
    ("draconian", "adjective", "Excessively harsh", "Draconian measures."),
    ("drastic", "adjective", "Likely to have strong effect", "Drastic action."),
    ("drawback", "noun", "A disadvantage", "A serious drawback."),
    ("dread", "verb", "To fear greatly", "Dread the outcome."),
    ("drivel", "noun", "Nonsense", "Complete drivel."),
    ("droll", "adjective", "Amusing in an odd way", "A droll sense of humor."),
    ("drone", "verb", "To make a continuous low sound", "The engine droned."),
    ("dross", "noun", "Something worthless", "Separate gold from dross."),
    ("drought", "noun", "A prolonged period without rain", "A severe drought."),
    ("dubious", "adjective", "Hesitating or doubting", "A dubious claim."),
    ("ductile", "adjective", "Able to be drawn into wire", "Ductile metal."),
    ("dud", "noun", "A thing that fails", "The movie was a dud."),
    ("dulcet", "adjective", "Sweet and soothing", "Dulcet tones."),
    ("dupe", "verb", "To deceive", "Duped into believing."),
    ("duplicity", "noun", "Deceitfulness", "Political duplicity."),
    ("durable", "adjective", "Able to withstand wear", "Durable goods."),
    ("duress", "noun", "Threats or violence used to coerce", "Under duress."),
    ("dwindle", "verb", "To diminish gradually", "Resources dwindled."),
    ("dynamic", "adjective", "Characterized by constant change", "A dynamic environment."),
    ("dynasty", "noun", "A line of hereditary rulers", "A political dynasty."),
    ("dysfunction", "noun", "Abnormality of functioning", "Family dysfunction."),
    ("dystopia", "noun", "An imagined state of great suffering", "A dystopian society."),
]
