# 100+ Level Words Part 1 (1-200) - Expert Academic Vocabulary
WORDS_100_PLUS_PART1 = [
    ("abase", "verb", "To lower in rank or esteem", "Refuse to abase yourself."),
    ("abate", "verb", "To become less intense", "The storm abated."),
    ("abdicate", "verb", "To renounce a throne", "The king abdicated."),
    ("aberrant", "adjective", "Departing from an accepted standard", "Aberrant behavior."),
    ("abet", "verb", "To encourage wrongdoing", "Aid and abet a crime."),
    ("abeyance", "noun", "A state of temporary suspension", "Held in abeyance."),
    ("abhorrent", "adjective", "Inspiring disgust", "Abhorrent practices."),
    ("abide", "verb", "To accept or act in accordance", "Abide by the rules."),
    ("ablution", "noun", "The act of washing oneself", "Perform ablutions."),
    ("abnegate", "verb", "To renounce or reject", "Abnegate responsibility."),
    ("abode", "noun", "A place of residence", "A humble abode."),
    ("aborigine", "noun", "An original inhabitant", "Australian aborigines."),
    ("abound", "verb", "To exist in large numbers", "Fish abound in the lake."),
    ("abrasion", "noun", "A scraped area on skin", "A minor abrasion."),
    ("abrogate", "verb", "To abolish by authority", "Abrogate the treaty."),
    ("abscond", "verb", "To leave hurriedly to escape", "Abscond with the funds."),
    ("absolve", "verb", "To free from blame", "Absolve of guilt."),
    ("abstain", "verb", "To refrain from", "Abstain from alcohol."),
    ("abstemious", "adjective", "Self-disciplined in eating", "An abstemious lifestyle."),
    ("abstruse", "adjective", "Difficult to understand", "Abstruse theories."),
    ("accede", "verb", "To agree to a demand", "Accede to requests."),
    ("accentuate", "verb", "To emphasize", "Accentuate the positive."),
    ("acclamation", "noun", "Loud approval", "Won by acclamation."),
    ("accolade", "noun", "An award or honor", "Receive accolades."),
    ("accord", "noun", "An agreement", "Sign an accord."),
    ("accost", "verb", "To approach boldly", "Accosted by strangers."),
    ("accretion", "noun", "Growth by gradual addition", "Accretion of power."),
    ("acerbic", "adjective", "Sharp and forthright", "Acerbic wit."),
    ("acquiesce", "verb", "To accept reluctantly", "Acquiesce to demands."),
    ("acrimony", "noun", "Bitterness in speech", "Acrimony between rivals."),
    ("actuate", "verb", "To cause to act", "Actuated by greed."),
    ("acuity", "noun", "Sharpness of perception", "Visual acuity."),
    ("adage", "noun", "A proverb or saying", "An old adage."),
    ("adamantine", "adjective", "Unbreakable", "Adamantine resolve."),
    ("adduce", "verb", "To cite as evidence", "Adduce proof."),
    ("adjudicate", "verb", "To make a formal judgment", "Adjudicate disputes."),
    ("adjunct", "noun", "Something added", "An adjunct professor."),
    ("admonition", "noun", "A firm warning", "Heed the admonition."),
    ("adroit", "adjective", "Clever or skillful", "Adroit maneuvering."),
    ("adulation", "noun", "Excessive praise", "Public adulation."),
    ("adulterate", "verb", "To make impure", "Adulterate the product."),
    ("adversarial", "adjective", "Involving conflict", "An adversarial relationship."),
    ("aesthetic", "adjective", "Concerned with beauty", "Aesthetic appreciation."),
    ("affable", "adjective", "Friendly and approachable", "An affable host."),
    ("affectation", "noun", "Pretentious behavior", "Without affectation."),
    ("affiliate", "verb", "To associate with", "Affiliate with a group."),
    ("affinity", "noun", "A natural liking", "An affinity for art."),
    ("affluence", "noun", "Wealth", "Live in affluence."),
    ("aggrandize", "verb", "To increase power or status", "Self-aggrandize."),
    ("aggregate", "noun", "A whole formed of parts", "In the aggregate."),
    ("aggrieve", "verb", "To cause distress", "Aggrieved parties."),
    ("aghast", "adjective", "Filled with horror", "Stood aghast."),
    ("agnostic", "noun", "One who doubts God's existence", "Identify as agnostic."),
    ("alchemy", "noun", "Medieval chemistry", "The alchemy of success."),
    ("alacrity", "noun", "Brisk eagerness", "Accept with alacrity."),
    ("albeit", "conjunction", "Although", "Albeit slowly."),
    ("alienate", "verb", "To cause to feel isolated", "Alienate supporters."),
    ("allay", "verb", "To diminish fear", "Allay suspicions."),
    ("allege", "verb", "To claim without proof", "Allege wrongdoing."),
    ("allegiance", "noun", "Loyalty", "Pledge allegiance."),
    ("allegory", "noun", "A symbolic narrative", "A political allegory."),
    ("alleviate", "verb", "To make less severe", "Alleviate suffering."),
    ("allocate", "verb", "To distribute", "Allocate resources."),
    ("allot", "verb", "To give a share", "Allot time."),
    ("allude", "verb", "To make an indirect reference", "Allude to past events."),
    ("allure", "noun", "Attractiveness", "The allure of fame."),
    ("allusion", "noun", "An indirect reference", "A biblical allusion."),
    ("amalgamate", "verb", "To combine", "Amalgamate companies."),
    ("ambiguity", "noun", "Uncertainty of meaning", "Avoid ambiguity."),
    ("ambivalent", "adjective", "Having mixed feelings", "Feel ambivalent."),
    ("ameliorate", "verb", "To make better", "Ameliorate conditions."),
    ("amenable", "adjective", "Open to suggestion", "Amenable to change."),
    ("amend", "verb", "To make changes", "Amend the law."),
    ("amenity", "noun", "A useful feature", "Modern amenities."),
    ("amiable", "adjective", "Friendly", "An amiable person."),
    ("amicable", "adjective", "Done in a friendly way", "An amicable settlement."),
    ("amnesty", "noun", "An official pardon", "Grant amnesty."),
    ("amorphous", "adjective", "Without shape", "An amorphous mass."),
    ("anachronism", "noun", "Something out of its time", "A technological anachronism."),
    ("analogous", "adjective", "Comparable", "Analogous situations."),
    ("anarchy", "noun", "Absence of government", "Political anarchy."),
    ("anathema", "noun", "Something greatly disliked", "Violence is anathema."),
    ("ancillary", "adjective", "Providing support", "Ancillary services."),
    ("anecdote", "noun", "A short story", "Share an anecdote."),
    ("animosity", "noun", "Strong hostility", "Deep animosity."),
    ("annex", "verb", "To attach or add", "Annex territory."),
    ("annihilate", "verb", "To destroy completely", "Annihilate opposition."),
    ("annotate", "verb", "To add notes", "Annotate the text."),
    ("anomaly", "noun", "Something that deviates from normal", "A statistical anomaly."),
    ("antagonize", "verb", "To cause hostility", "Don't antagonize them."),
    ("antecedent", "noun", "A thing that existed before", "Historical antecedents."),
    ("anterior", "adjective", "At the front", "The anterior section."),
    ("anthology", "noun", "A collection of works", "A poetry anthology."),
    ("anthropology", "noun", "The study of human societies", "Study anthropology."),
    ("antiquated", "adjective", "Old-fashioned", "Antiquated technology."),
    ("antithesis", "noun", "The exact opposite", "The antithesis of truth."),
    ("apathetic", "adjective", "Showing no interest", "An apathetic response."),
    ("apex", "noun", "The highest point", "The apex of power."),
    ("aplomb", "noun", "Self-assurance", "Handle with aplomb."),
    ("apocryphal", "adjective", "Of doubtful authenticity", "An apocryphal story."),
    ("apotheosis", "noun", "The highest point of glory", "The apotheosis of achievement."),
    ("appall", "verb", "To greatly dismay", "Appalled by the news."),
    ("appease", "verb", "To pacify", "Appease the critics."),
    ("append", "verb", "To add to the end", "Append a note."),
    ("apprehension", "noun", "Anxiety or arrest", "Filled with apprehension."),
    ("apprise", "verb", "To inform", "Apprise of the situation."),
    ("approbation", "noun", "Approval or praise", "Seek approbation."),
    ("appropriate", "verb", "To take for one's use", "Appropriate funds."),
    ("aptitude", "noun", "Natural ability", "An aptitude for math."),
    ("arbitrary", "adjective", "Based on random choice", "An arbitrary decision."),
    ("arbitrate", "verb", "To judge in a dispute", "Arbitrate the conflict."),
    ("arcane", "adjective", "Understood by few", "Arcane knowledge."),
    ("archaic", "adjective", "Very old", "Archaic language."),
    ("archetype", "noun", "A perfect example", "The archetype of heroism."),
    ("ardent", "adjective", "Enthusiastic", "An ardent supporter."),
    ("arduous", "adjective", "Difficult and tiring", "An arduous task."),
    ("aristocracy", "noun", "The ruling class", "The aristocracy."),
    ("arrogate", "verb", "To claim without right", "Arrogate power."),
    ("articulate", "verb", "To express clearly", "Articulate your thoughts."),
    ("artifice", "noun", "Clever skill", "Political artifice."),
    ("ascertain", "verb", "To find out for certain", "Ascertain the truth."),
    ("ascetic", "adjective", "Practicing self-denial", "An ascetic life."),
    ("ascribe", "verb", "To attribute to", "Ascribe credit."),
    ("asinine", "adjective", "Extremely stupid", "An asinine comment."),
    ("aspersion", "noun", "An attack on reputation", "Cast aspersions."),
    ("aspire", "verb", "To have ambition", "Aspire to greatness."),
    ("assail", "verb", "To attack violently", "Assail with criticism."),
    ("assent", "noun", "Agreement", "Give assent."),
    ("assert", "verb", "To state confidently", "Assert your rights."),
    ("assiduous", "adjective", "Showing great care", "Assiduous attention."),
    ("assimilate", "verb", "To absorb", "Assimilate information."),
    ("assuage", "verb", "To make less intense", "Assuage fears."),
    ("astute", "adjective", "Having sharp judgment", "An astute observer."),
    ("atone", "verb", "To make amends", "Atone for mistakes."),
    ("atrophy", "noun", "Gradual decline", "Muscle atrophy."),
    ("attenuate", "verb", "To reduce in force", "Attenuate the signal."),
    ("attribute", "verb", "To regard as caused by", "Attribute success to hard work."),
    ("attrition", "noun", "Gradual wearing down", "War of attrition."),
    ("audacious", "adjective", "Bold and daring", "An audacious plan."),
    ("augment", "verb", "To make greater", "Augment income."),
    ("auspicious", "adjective", "Favorable", "An auspicious beginning."),
    ("austere", "adjective", "Severe and strict", "Austere conditions."),
    ("authenticate", "verb", "To prove genuine", "Authenticate documents."),
    ("authoritarian", "adjective", "Favoring strict obedience", "Authoritarian rule."),
    ("autocratic", "adjective", "Having absolute power", "An autocratic leader."),
    ("autonomous", "adjective", "Self-governing", "An autonomous region."),
    ("avarice", "noun", "Extreme greed", "Driven by avarice."),
    ("averse", "adjective", "Strongly opposed", "Averse to risk."),
    ("aversion", "noun", "A strong dislike", "An aversion to heights."),
    ("avert", "verb", "To prevent", "Avert disaster."),
    ("avid", "adjective", "Having a keen interest", "An avid reader."),
    ("avow", "verb", "To declare openly", "Avow support."),
    ("axiom", "noun", "A self-evident truth", "A mathematical axiom."),
    ("baleful", "adjective", "Threatening harm", "A baleful glare."),
    ("banal", "adjective", "Lacking originality", "A banal comment."),
    ("bane", "noun", "A cause of harm", "The bane of existence."),
    ("banter", "noun", "Playful exchange", "Friendly banter."),
    ("bastion", "noun", "A stronghold", "A bastion of democracy."),
    ("bedlam", "noun", "Uproar and confusion", "Complete bedlam."),
    ("befuddle", "verb", "To confuse", "Befuddled by the question."),
    ("beget", "verb", "To produce", "Violence begets violence."),
    ("beguile", "verb", "To charm or deceive", "Beguile with flattery."),
    ("behoove", "verb", "To be appropriate", "It behooves you to listen."),
    ("belabor", "verb", "To explain excessively", "Don't belabor the point."),
    ("beleaguer", "verb", "To harass", "Beleaguered by problems."),
    ("belie", "verb", "To fail to give a true impression", "Actions belie words."),
    ("belittle", "verb", "To disparage", "Belittle achievements."),
    ("bellicose", "adjective", "Warlike", "Bellicose rhetoric."),
    ("belligerent", "adjective", "Hostile", "A belligerent attitude."),
    ("bemoan", "verb", "To express discontent", "Bemoan the loss."),
    ("benchmark", "noun", "A standard", "Set a benchmark."),
    ("benefactor", "noun", "A person who gives help", "A generous benefactor."),
    ("beneficent", "adjective", "Generous and doing good", "Beneficent actions."),
    ("benevolent", "adjective", "Well-meaning", "A benevolent ruler."),
    ("benign", "adjective", "Gentle and kind", "A benign tumor."),
    ("bequeath", "verb", "To leave in a will", "Bequeath an estate."),
    ("berate", "verb", "To scold angrily", "Berate someone harshly."),
    ("bereft", "adjective", "Deprived of", "Bereft of hope."),
    ("beset", "verb", "To trouble", "Beset with problems."),
    ("besiege", "verb", "To surround", "Besieged by reporters."),
    ("besmirch", "verb", "To damage reputation", "Besmirch honor."),
    ("bestow", "verb", "To confer", "Bestow an award."),
    ("betoken", "verb", "To be a sign of", "Betoken change."),
    ("betray", "verb", "To be disloyal", "Betray trust."),
    ("bifurcate", "verb", "To divide into two", "The road bifurcates."),
    ("bigot", "noun", "An intolerant person", "A religious bigot."),
    ("bilateral", "adjective", "Having two sides", "Bilateral agreement."),
    ("bivouac", "noun", "A temporary camp", "Set up bivouac."),
    ("blandishment", "noun", "Flattering speech", "Resist blandishments."),
    ("blasphemy", "noun", "Speaking irreverently about God", "Accused of blasphemy."),
    ("blatant", "adjective", "Completely obvious", "Blatant disregard."),
    ("blight", "noun", "A thing that spoils", "Urban blight."),
    ("blithe", "adjective", "Carefree", "Blithe indifference."),
    ("bluster", "verb", "To talk aggressively", "Bluster and threaten."),
    ("bogus", "adjective", "Not genuine", "Bogus claims."),
    ("boisterous", "adjective", "Noisy and energetic", "Boisterous laughter."),
]
