# 60-80 Level Words Part 1 (1-300)
WORDS_60_80_PART1 = [
    ("exceed", "verb", "To go beyond a limit", "Do not exceed the speed limit."),
    ("excellent", "adjective", "Extremely good", "She did an excellent job."),
    ("except", "preposition", "Not including", "Everyone came except John."),
    ("exception", "noun", "Something that does not follow a rule", "There are exceptions to every rule."),
    ("exchange", "noun", "An act of giving and receiving", "Cultural exchange is valuable."),
    ("excite", "verb", "To cause strong feelings", "The news excited everyone."),
    ("excitement", "noun", "A feeling of enthusiasm", "The excitement was contagious."),
    ("exciting", "adjective", "Causing excitement", "The game was exciting."),
    ("exclude", "verb", "To leave out", "Do not exclude anyone from the group."),
    ("exclusive", "adjective", "Not shared with others", "An exclusive interview was granted."),
    ("excuse", "noun", "A reason given to justify a fault", "That is not a valid excuse."),
    ("execute", "verb", "To carry out a plan", "Execute the strategy carefully."),
    ("executive", "noun", "A senior manager", "The executive made the decision."),
    ("exercise", "noun", "Physical activity", "Daily exercise is important."),
    ("exhibit", "verb", "To display publicly", "The museum exhibits ancient artifacts."),
    ("exhibition", "noun", "A public display", "The art exhibition opened today."),
    ("exist", "verb", "To be present or occur", "Dinosaurs no longer exist."),
    ("existence", "noun", "The state of existing", "The existence of aliens is debated."),
    ("existing", "adjective", "Currently present", "Improve existing systems."),
    ("expand", "verb", "To increase in size", "The company plans to expand."),
    ("expansion", "noun", "The action of expanding", "Economic expansion continued."),
    ("expect", "verb", "To regard as likely to happen", "I expect you to arrive on time."),
    ("expectation", "noun", "A belief about the future", "Set realistic expectations."),
    ("expense", "noun", "The cost of something", "Travel expenses are covered."),
    ("expensive", "adjective", "Costing a lot of money", "The car is too expensive."),
    ("experience", "noun", "Practical contact with something", "She has years of experience."),
    ("experienced", "adjective", "Having knowledge from practice", "He is an experienced teacher."),
    ("experiment", "noun", "A scientific procedure", "The experiment was successful."),
    ("experimental", "adjective", "Based on untested ideas", "This is an experimental treatment."),
    ("expert", "noun", "A person with special knowledge", "Consult an expert in the field."),
    ("expertise", "noun", "Expert skill or knowledge", "Her expertise is in marketing."),
    ("explain", "verb", "To make clear", "Please explain the process."),
    ("explanation", "noun", "A statement that makes something clear", "Give a detailed explanation."),
    ("explicit", "adjective", "Stated clearly", "The instructions were explicit."),
    ("explore", "verb", "To travel through unfamiliar areas", "Explore new possibilities."),
    ("explosion", "noun", "A violent release of energy", "The explosion was heard miles away."),
    ("export", "verb", "To send goods to another country", "The country exports rice."),
    ("expose", "verb", "To make visible", "The report exposed corruption."),
    ("exposure", "noun", "The state of being exposed", "Sun exposure can be harmful."),
    ("express", "verb", "To convey in words", "Express your feelings clearly."),
    ("expression", "noun", "The act of expressing", "Facial expressions reveal emotions."),
    ("extend", "verb", "To make longer", "Extend the deadline by one week."),
    ("extension", "noun", "The action of extending", "Request an extension if needed."),
    ("extensive", "adjective", "Covering a large area", "Extensive research was conducted."),
    ("extent", "noun", "The degree to which something happens", "To what extent do you agree?"),
    ("external", "adjective", "Coming from outside", "External factors affected the result."),
    ("extra", "adjective", "Additional", "Order extra supplies."),
    ("extraordinary", "adjective", "Very unusual or remarkable", "She has extraordinary talent."),
    ("extreme", "adjective", "To the highest degree", "Avoid extreme temperatures."),
    ("extremely", "adverb", "To a very great degree", "The test was extremely difficult."),
    ("eye", "noun", "The organ of sight", "She has blue eyes."),
    ("fabric", "noun", "Cloth or textile material", "The fabric is soft."),
    ("face", "noun", "The front of the head", "Wash your face."),
    ("facility", "noun", "A place for a particular purpose", "The sports facility is new."),
    ("fact", "noun", "Something known to be true", "State the facts clearly."),
    ("factor", "noun", "A circumstance contributing to a result", "Consider all factors."),
    ("factory", "noun", "A building for manufacturing", "The factory produces cars."),
    ("faculty", "noun", "The teaching staff", "The faculty met yesterday."),
    ("fade", "verb", "To gradually become less visible", "Colors fade in the sun."),
    ("fail", "verb", "To be unsuccessful", "Do not fear to fail."),
    ("failure", "noun", "Lack of success", "Learn from failure."),
    ("fair", "adjective", "Treating people equally", "The judge was fair."),
    ("fairly", "adverb", "In a fair manner", "Distribute resources fairly."),
    ("faith", "noun", "Complete trust", "Have faith in yourself."),
    ("fall", "verb", "To drop down", "Leaves fall in autumn."),
    ("false", "adjective", "Not true", "The statement is false."),
    ("fame", "noun", "The state of being famous", "Fame came quickly."),
    ("familiar", "adjective", "Well known", "The face looks familiar."),
    ("family", "noun", "A group of related people", "Family is important."),
    ("famous", "adjective", "Known by many people", "The singer is famous worldwide."),
    ("fan", "noun", "An enthusiastic supporter", "She is a big fan of the team."),
    ("fancy", "adjective", "Elaborate or decorative", "The restaurant is fancy."),
    ("far", "adverb", "At a great distance", "How far is the station?"),
    ("farm", "noun", "An area of land for growing crops", "The farm produces vegetables."),
    ("farmer", "noun", "A person who runs a farm", "The farmer planted seeds."),
    ("fashion", "noun", "A popular style", "Fashion trends change quickly."),
    ("fast", "adjective", "Moving quickly", "The car is very fast."),
    ("fat", "adjective", "Having excess body weight", "Reduce fat in your diet."),
    ("fate", "noun", "The development of events outside control", "Fate brought them together."),
    ("father", "noun", "A male parent", "My father is a doctor."),
    ("fault", "noun", "Responsibility for a mistake", "It was my fault."),
    ("favor", "noun", "An act of kindness", "Can you do me a favor?"),
    ("favorite", "adjective", "Preferred above all others", "Pizza is my favorite food."),
    ("fear", "noun", "An unpleasant emotion caused by danger", "Fear of failure is common."),
    ("feature", "noun", "A distinctive attribute", "The phone has many features."),
    ("federal", "adjective", "Relating to a central government", "Federal laws apply nationwide."),
    ("fee", "noun", "A payment for services", "The registration fee is $50."),
    ("feed", "verb", "To give food to", "Feed the animals twice a day."),
    ("feedback", "noun", "Information about reactions", "Give constructive feedback."),
    ("feel", "verb", "To be aware of through touch", "I feel happy today."),
    ("feeling", "noun", "An emotional state", "Express your feelings."),
    ("fellow", "noun", "A man or boy", "He is a good fellow."),
    ("female", "adjective", "Of the sex that can bear offspring", "Female athletes compete."),
    ("fence", "noun", "A barrier enclosing an area", "Build a fence around the yard."),
    ("festival", "noun", "A day of celebration", "The music festival was great."),
    ("few", "determiner", "A small number of", "Few people attended."),
    ("fiber", "noun", "A thread-like structure", "Eat foods high in fiber."),
    ("fiction", "noun", "Literature describing imaginary events", "She writes fiction novels."),
    ("field", "noun", "An area of open land", "The field is full of flowers."),
    ("fifth", "ordinal", "Number five in a sequence", "She finished fifth in the race."),
    ("fifty", "number", "The number 50", "He is fifty years old."),
    ("fight", "verb", "To take part in a violent struggle", "Fight for your rights."),
    ("fighter", "noun", "A person who fights", "The fighter won the match."),
    ("figure", "noun", "A number or amount", "Check the figures carefully."),
    ("file", "noun", "A folder for documents", "Save the file to your computer."),
    ("fill", "verb", "To make full", "Fill the glass with water."),
    ("film", "noun", "A movie", "The film won several awards."),
    ("final", "adjective", "Coming at the end", "This is my final answer."),
    ("finally", "adverb", "After a long time", "We finally arrived."),
    ("finance", "noun", "The management of money", "Study finance at university."),
    ("financial", "adjective", "Relating to finance", "Financial planning is important."),
    ("find", "verb", "To discover", "Find the answer to the question."),
    ("finding", "noun", "A conclusion from research", "The findings were published."),
    ("fine", "adjective", "Of high quality", "The weather is fine today."),
    ("finger", "noun", "A digit of the hand", "She pointed her finger."),
    ("finish", "verb", "To complete", "Finish your homework."),
    ("fire", "noun", "Combustion producing light and heat", "The fire spread quickly."),
    ("firm", "noun", "A business company", "She works for a law firm."),
    ("first", "ordinal", "Coming before all others", "He came first in the race."),
    ("fish", "noun", "An aquatic animal", "Fish swim in the ocean."),
    ("fishing", "noun", "The activity of catching fish", "Fishing is relaxing."),
    ("fit", "adjective", "In good physical condition", "Stay fit through exercise."),
    ("fitness", "noun", "The condition of being fit", "Physical fitness is important."),
    ("five", "number", "The number 5", "She has five cats."),
    ("fix", "verb", "To repair", "Fix the broken window."),
    ("flag", "noun", "A piece of cloth used as a symbol", "Raise the flag."),
    ("flame", "noun", "A hot glowing body of ignited gas", "The candle flame flickered."),
    ("flash", "noun", "A sudden brief burst of light", "A flash of lightning lit the sky."),
    ("flat", "adjective", "Having a level surface", "The land is flat here."),
    ("flavor", "noun", "The taste of food", "The soup has great flavor."),
    ("flee", "verb", "To run away", "They had to flee the country."),
    ("flesh", "noun", "The soft substance of the body", "The wound exposed flesh."),
    ("flexibility", "noun", "The quality of being flexible", "Job flexibility is valued."),
    ("flexible", "adjective", "Capable of bending easily", "The schedule is flexible."),
    ("flight", "noun", "The act of flying", "The flight was delayed."),
    ("float", "verb", "To rest on the surface of a liquid", "The boat floats on water."),
    ("flood", "noun", "An overflow of water", "The flood damaged homes."),
    ("floor", "noun", "The lower surface of a room", "Clean the floor."),
    ("flow", "verb", "To move steadily", "Water flows downstream."),
    ("flower", "noun", "The reproductive part of a plant", "The flower bloomed beautifully."),
    ("fly", "verb", "To move through the air", "Birds fly south in winter."),
    ("focus", "verb", "To concentrate attention", "Focus on your goals."),
    ("fold", "verb", "To bend something over itself", "Fold the paper in half."),
    ("folk", "noun", "People in general", "Folk music is traditional."),
    ("follow", "verb", "To go after", "Follow the instructions carefully."),
    ("following", "adjective", "Coming after", "Answer the following questions."),
    ("food", "noun", "Any substance consumed for nutrition", "Food is essential for life."),
    ("foot", "noun", "The lower extremity of the leg", "My foot hurts."),
    ("football", "noun", "A sport played with a ball", "Football is popular worldwide."),
    ("for", "preposition", "Indicating purpose", "This gift is for you."),
    ("force", "noun", "Strength or energy", "The force of the wind was strong."),
    ("forecast", "noun", "A prediction of future events", "Check the weather forecast."),
    ("foreign", "adjective", "Of another country", "Learn a foreign language."),
    ("forest", "noun", "A large area covered with trees", "The forest is dense."),
    ("forever", "adverb", "For all future time", "I will love you forever."),
    ("forget", "verb", "To fail to remember", "Do not forget your keys."),
    ("forgive", "verb", "To stop feeling angry", "Forgive and forget."),
    ("form", "noun", "The shape of something", "Fill out the form."),
    ("formal", "adjective", "Done in accordance with rules", "Wear formal attire."),
    ("format", "noun", "The way something is arranged", "Use the correct format."),
    ("formation", "noun", "The action of forming", "Cloud formation is interesting."),
    ("former", "adjective", "Having been previously", "The former president spoke."),
    ("formula", "noun", "A rule expressed in symbols", "Use the mathematical formula."),
    ("forth", "adverb", "Forward in time or space", "Go forth and succeed."),
    ("fortune", "noun", "Luck or chance", "She made a fortune in business."),
    ("forty", "number", "The number 40", "He is forty years old."),
    ("forward", "adverb", "Toward the front", "Move forward slowly."),
    ("found", "verb", "To establish an institution", "They founded the company in 1990."),
    ("foundation", "noun", "The basis of something", "Education is the foundation of success."),
    ("founder", "noun", "A person who establishes something", "The founder retired last year."),
    ("four", "number", "The number 4", "There are four seasons."),
    ("fourth", "ordinal", "Number four in a sequence", "She finished fourth."),
    ("frame", "noun", "A rigid structure surrounding something", "Put the picture in a frame."),
    ("framework", "noun", "A basic structure", "Create a framework for the project."),
    ("free", "adjective", "Not under control of another", "The admission is free."),
    ("freedom", "noun", "The state of being free", "Fight for freedom."),
    ("frequency", "noun", "The rate of occurrence", "Increase the frequency of updates."),
    ("frequent", "adjective", "Occurring often", "Frequent breaks improve productivity."),
    ("frequently", "adverb", "Regularly or often", "She frequently travels abroad."),
    ("fresh", "adjective", "Recently made or obtained", "Buy fresh vegetables."),
    ("friend", "noun", "A person you know well and like", "She is my best friend."),
    ("friendly", "adjective", "Kind and pleasant", "The staff was friendly."),
    ("friendship", "noun", "The state of being friends", "Their friendship lasted years."),
    ("from", "preposition", "Indicating origin", "I am from Korea."),
    ("front", "noun", "The forward part", "Sit at the front of the class."),
    ("fruit", "noun", "The sweet product of a plant", "Eat more fruit."),
    ("frustrate", "verb", "To cause feelings of upset", "The delay frustrated passengers."),
    ("frustration", "noun", "The feeling of being upset", "Express your frustration calmly."),
    ("fuel", "noun", "Material used to produce energy", "The car needs fuel."),
    ("fulfill", "verb", "To carry out or satisfy", "Fulfill your promises."),
    ("full", "adjective", "Containing as much as possible", "The glass is full."),
    ("fully", "adverb", "Completely", "I fully understand the situation."),
    ("fun", "noun", "Enjoyment or amusement", "We had so much fun."),
    ("function", "noun", "An activity natural to a purpose", "What is the function of this button?"),
    ("fund", "noun", "A sum of money for a purpose", "The research fund was approved."),
    ("fundamental", "adjective", "Forming a necessary base", "These are fundamental principles."),
    ("funding", "noun", "Money provided for a purpose", "Secure funding for the project."),
    ("funeral", "noun", "A ceremony for the dead", "The funeral was held yesterday."),
    ("funny", "adjective", "Causing laughter", "The joke was funny."),
    ("furniture", "noun", "Movable articles in a room", "Buy new furniture."),
    ("furthermore", "adverb", "In addition", "Furthermore, the cost is reasonable."),
    ("future", "noun", "The time that will come", "Plan for the future."),
    ("gain", "verb", "To obtain or acquire", "Gain experience through practice."),
    ("gallery", "noun", "A room for displaying art", "Visit the art gallery."),
    ("game", "noun", "A form of competitive activity", "Play a board game."),
    ("gap", "noun", "A space or opening", "Bridge the gap between theory and practice."),
    ("garage", "noun", "A building for storing vehicles", "Park the car in the garage."),
    ("garden", "noun", "A piece of ground for growing plants", "She works in the garden."),
    ("gas", "noun", "A substance in the air", "Fill the tank with gas."),
    ("gate", "noun", "A movable barrier in a fence", "Close the gate behind you."),
    ("gather", "verb", "To come together", "People gathered in the square."),
    ("gay", "adjective", "Homosexual", "Gay rights are important."),
    ("gaze", "verb", "To look steadily", "She gazed at the stars."),
    ("gear", "noun", "Equipment for an activity", "Bring camping gear."),
    ("gender", "noun", "The state of being male or female", "Gender equality is essential."),
    ("gene", "noun", "A unit of heredity", "Genes determine traits."),
    ("general", "adjective", "Affecting all or most", "The general consensus was positive."),
    ("generally", "adverb", "In most cases", "Generally speaking, the plan is good."),
    ("generate", "verb", "To produce or create", "Generate new ideas."),
    ("generation", "noun", "All people born at a similar time", "The younger generation is tech-savvy."),
    ("generous", "adjective", "Willing to give", "She is generous with her time."),
    ("genetic", "adjective", "Relating to genes", "Genetic research is advancing."),
    ("genre", "noun", "A category of art or literature", "What genre of music do you like?"),
    ("gentle", "adjective", "Mild and kind", "She has a gentle personality."),
    ("gentleman", "noun", "A polite man", "He is a true gentleman."),
    ("gently", "adverb", "In a gentle manner", "Handle it gently."),
    ("genuine", "adjective", "Truly what it is said to be", "This is a genuine leather bag."),
    ("geographic", "adjective", "Relating to geography", "Geographic features vary."),
    ("get", "verb", "To receive or obtain", "Get the book from the shelf."),
    ("ghost", "noun", "A spirit of a dead person", "Do you believe in ghosts?"),
    ("giant", "adjective", "Very large", "The giant tree fell."),
    ("gift", "noun", "Something given voluntarily", "She received a gift."),
    ("girl", "noun", "A female child", "The girl is playing."),
    ("girlfriend", "noun", "A female romantic partner", "He introduced his girlfriend."),
    ("give", "verb", "To transfer possession", "Give the book to me."),
    ("given", "preposition", "Taking into account", "Given the circumstances, we agreed."),
    ("glad", "adjective", "Pleased and happy", "I am glad you came."),
    ("glance", "verb", "To look briefly", "She glanced at her watch."),
    ("glass", "noun", "A hard transparent material", "The glass broke."),
    ("global", "adjective", "Relating to the whole world", "Global warming is a crisis."),
    ("globe", "noun", "The earth", "Travel around the globe."),
    ("glory", "noun", "High renown or honor", "The team achieved glory."),
    ("go", "verb", "To move from one place to another", "Let's go to the park."),
    ("goal", "noun", "An aim or desired result", "Set clear goals."),
    ("god", "noun", "A superhuman being", "Many cultures believe in a god."),
    ("gold", "noun", "A precious yellow metal", "Gold prices rose."),
    ("golden", "adjective", "Made of or resembling gold", "The golden sunset was beautiful."),
    ("golf", "noun", "A sport played with clubs and balls", "He plays golf on weekends."),
    ("good", "adjective", "Of high quality", "She did a good job."),
    ("goods", "noun", "Merchandise or possessions", "The goods arrived today."),
    ("govern", "verb", "To conduct the policy of", "Laws govern society."),
    ("government", "noun", "The governing body of a nation", "The government announced reforms."),
    ("governor", "noun", "An official who governs", "The governor signed the bill."),
    ("grab", "verb", "To seize suddenly", "Grab your coat and let's go."),
    ("grace", "noun", "Smoothness of movement", "She dances with grace."),
    ("grade", "noun", "A level of quality", "What grade did you get?"),
    ("gradually", "adverb", "In a gradual way", "The situation improved gradually."),
    ("graduate", "verb", "To complete a course of study", "She will graduate next year."),
    ("grain", "noun", "A small hard seed", "Rice is a staple grain."),
    ("grand", "adjective", "Magnificent or imposing", "The grand palace impressed visitors."),
    ("grandfather", "noun", "The father of one's parent", "My grandfather is 85 years old."),
    ("grandmother", "noun", "The mother of one's parent", "My grandmother bakes cookies."),
    ("grant", "verb", "To give or allow", "Grant permission to proceed."),
    ("grass", "noun", "Vegetation of short plants", "Cut the grass."),
    ("gray", "adjective", "Of a color between black and white", "The sky was gray."),
    ("great", "adjective", "Of considerable size or extent", "It was a great success."),
    ("greatest", "adjective", "Superlative of great", "She is the greatest player."),
    ("green", "adjective", "The color of grass", "The leaves are green."),
    ("greet", "verb", "To give a word of welcome", "Greet guests warmly."),
    ("ground", "noun", "The surface of the earth", "Sit on the ground."),
    ("group", "noun", "A number of people together", "The group discussed the topic."),
    ("grow", "verb", "To increase in size", "Plants grow in spring."),
    ("growing", "adjective", "Increasing", "There is growing concern."),
    ("growth", "noun", "The process of growing", "Economic growth slowed."),
    ("guarantee", "verb", "To promise with certainty", "We guarantee quality."),
    ("guard", "noun", "A person who watches over", "The guard stood at the entrance."),
    ("guess", "verb", "To estimate without information", "Guess the number."),
    ("guest", "noun", "A person invited to an event", "Welcome the guests."),
    ("guidance", "noun", "Advice or information", "Seek guidance from experts."),
    ("guide", "noun", "A person who shows the way", "The guide led the tour."),
    ("guideline", "noun", "A general rule", "Follow the guidelines."),
    ("guilty", "adjective", "Responsible for wrongdoing", "He was found guilty."),
    ("gun", "noun", "A weapon that fires bullets", "Gun control is debated."),
    ("guy", "noun", "A man", "He is a nice guy."),
    ("habit", "noun", "A regular practice", "Develop good habits."),
    ("habitat", "noun", "The natural home of an organism", "Protect wildlife habitats."),
    ("hair", "noun", "Strands growing from the skin", "She has long hair."),
    ("half", "noun", "One of two equal parts", "Cut the apple in half."),
    ("hall", "noun", "A large room for gatherings", "The concert hall was full."),
    ("hand", "noun", "The end part of the arm", "Wash your hands."),
    ("handle", "verb", "To manage or deal with", "Handle the situation carefully."),
    ("hang", "verb", "To suspend from above", "Hang the picture on the wall."),
    ("happen", "verb", "To take place", "What happened yesterday?"),
    ("happening", "noun", "An event or occurrence", "Strange happenings occurred."),
    ("happiness", "noun", "The state of being happy", "Happiness is important."),
    ("happy", "adjective", "Feeling pleasure", "She is happy today."),
    ("harbor", "noun", "A place for ships to dock", "The harbor is busy."),
    ("hard", "adjective", "Solid and firm", "The exam was hard."),
    ("hardly", "adverb", "Scarcely; barely", "I can hardly believe it."),
    ("harm", "noun", "Physical injury", "Do no harm."),
    ("harmful", "adjective", "Causing harm", "Smoking is harmful."),
    ("hat", "noun", "A covering for the head", "Wear a hat in the sun."),
    ("hate", "verb", "To feel intense dislike", "I hate being late."),
    ("have", "verb", "To possess", "I have a car."),
    ("he", "pronoun", "Used to refer to a male", "He is my brother."),
    ("head", "noun", "The upper part of the body", "She nodded her head."),
    ("headline", "noun", "The title of a news article", "The headline was shocking."),
    ("headquarters", "noun", "The main office", "Visit the company headquarters."),
    ("health", "noun", "The state of being well", "Health is wealth."),
    ("healthy", "adjective", "In good health", "Eat healthy food."),
]
