# 0-60 Level Words Part 2 (201-400)
WORDS_0_60_PART2 = [
    ("behavior", "noun", "The way one acts", "Good behavior is expected."),
    ("behind", "preposition", "At the back of", "The garden is behind the house."),
    ("belief", "noun", "An acceptance that something is true", "Religious beliefs vary widely."),
    ("believe", "verb", "To accept as true", "I believe in hard work."),
    ("belong", "verb", "To be a member of", "I belong to this club."),
    ("below", "preposition", "At a lower level than", "The temperature dropped below zero."),
    ("benefit", "noun", "An advantage or profit", "There are many benefits to reading."),
    ("beside", "preposition", "Next to", "Sit beside me."),
    ("besides", "preposition", "In addition to", "Besides English, she speaks French."),
    ("best", "adjective", "Of the highest quality", "This is the best solution."),
    ("better", "adjective", "Of higher quality", "Practice makes you better."),
    ("between", "preposition", "In the space separating two things", "Choose between these options."),
    ("beyond", "preposition", "Further than", "The village is beyond the mountains."),
    ("big", "adjective", "Of considerable size", "The elephant is a big animal."),
    ("bill", "noun", "A statement of charges", "Pay the electricity bill."),
    ("billion", "number", "A thousand million", "The project costs billions of dollars."),
    ("bind", "verb", "To tie or fasten", "Bind the papers together."),
    ("bird", "noun", "A feathered animal", "The bird flew south for winter."),
    ("birth", "noun", "The emergence of a baby", "Celebrate the birth of a child."),
    ("bit", "noun", "A small piece or amount", "Wait a bit longer."),
    ("bite", "verb", "To cut with teeth", "Do not bite your nails."),
    ("black", "adjective", "The darkest color", "She wore a black dress."),
    ("blame", "verb", "To assign responsibility for a fault", "Do not blame others for your mistakes."),
    ("blank", "adjective", "Not written or printed on", "Leave the form blank."),
    ("blind", "adjective", "Unable to see", "The blind man uses a cane."),
    ("block", "noun", "A solid piece of material", "A block of ice melted."),
    ("blood", "noun", "The red liquid in the body", "Blood carries oxygen to cells."),
    ("blow", "verb", "To move air", "The wind blows leaves around."),
    ("blue", "adjective", "The color of the sky", "The ocean looks blue."),
    ("board", "noun", "A flat piece of material", "Write on the board."),
    ("boat", "noun", "A watercraft", "We rented a boat for fishing."),
    ("body", "noun", "The physical structure of a person", "Exercise keeps your body healthy."),
    ("bomb", "noun", "An explosive device", "The bomb was safely defused."),
    ("bond", "noun", "A connection or tie", "Family bonds are important."),
    ("bone", "noun", "The hard tissue in the body", "Calcium strengthens bones."),
    ("book", "noun", "A written work", "I read a book every week."),
    ("border", "noun", "The edge or boundary", "They crossed the border."),
    ("born", "adjective", "Brought into existence", "She was born in Seoul."),
    ("borrow", "verb", "To take with permission to return", "May I borrow your pen?"),
    ("boss", "noun", "A person in charge", "The boss called a meeting."),
    ("both", "determiner", "Two together", "Both options are acceptable."),
    ("bother", "verb", "To annoy or disturb", "Do not bother me while I work."),
    ("bottle", "noun", "A container for liquids", "Fill the bottle with water."),
    ("bottom", "noun", "The lowest part", "Sign at the bottom of the page."),
    ("boundary", "noun", "A line marking limits", "Respect personal boundaries."),
    ("bowl", "noun", "A round deep dish", "Pour cereal into the bowl."),
    ("box", "noun", "A container with flat sides", "Pack your belongings in a box."),
    ("boy", "noun", "A male child", "The boy plays soccer."),
    ("brain", "noun", "The organ inside the head", "The brain controls body functions."),
    ("branch", "noun", "A part extending from the main body", "The bird sat on a branch."),
    ("brand", "noun", "A type of product", "This brand is popular."),
    ("brave", "adjective", "Showing courage", "The brave firefighter saved lives."),
    ("bread", "noun", "A baked food made from flour", "Fresh bread smells wonderful."),
    ("break", "verb", "To separate into pieces", "Do not break the glass."),
    ("breakfast", "noun", "The first meal of the day", "Eat a healthy breakfast."),
    ("breath", "noun", "Air taken into the lungs", "Take a deep breath."),
    ("breathe", "verb", "To take air into the lungs", "Breathe slowly and relax."),
    ("bridge", "noun", "A structure over water", "The bridge connects two cities."),
    ("brief", "adjective", "Of short duration", "Give a brief summary."),
    ("bright", "adjective", "Giving out much light", "The sun is bright today."),
    ("brilliant", "adjective", "Exceptionally clever", "She has a brilliant mind."),
    ("bring", "verb", "To carry to a place", "Bring your ID to the exam."),
    ("broad", "adjective", "Wide in extent", "The river is broad here."),
    ("broadcast", "verb", "To transmit by radio or TV", "The news was broadcast live."),
    ("brother", "noun", "A male sibling", "My brother is older than me."),
    ("brown", "adjective", "A color between red and yellow", "She has brown eyes."),
    ("budget", "noun", "An estimate of income and expenses", "Stick to your budget."),
    ("build", "verb", "To construct", "They plan to build a house."),
    ("building", "noun", "A structure with walls and roof", "The building is 20 stories tall."),
    ("burden", "noun", "A heavy load", "Do not be a burden to others."),
    ("burn", "verb", "To be on fire", "Do not burn yourself with hot water."),
    ("bus", "noun", "A large motor vehicle", "Take the bus to work."),
    ("business", "noun", "Commercial activity", "She started her own business."),
    ("busy", "adjective", "Actively engaged", "I am too busy to meet today."),
    ("but", "conjunction", "Used to introduce contrast", "I tried, but I failed."),
    ("buy", "verb", "To obtain in exchange for money", "I need to buy groceries."),
    ("buyer", "noun", "A person who purchases", "The buyer inspected the property."),
    ("cabinet", "noun", "A piece of furniture with shelves", "Store dishes in the cabinet."),
    ("calculate", "verb", "To determine mathematically", "Calculate the total cost."),
    ("calendar", "noun", "A chart showing days and months", "Mark the date on the calendar."),
    ("call", "verb", "To contact by phone", "I will call you tomorrow."),
    ("calm", "adjective", "Not showing agitation", "Stay calm during emergencies."),
    ("camera", "noun", "A device for taking photographs", "The camera captured the moment."),
    ("camp", "noun", "A place for temporary lodging", "Summer camp is fun for kids."),
    ("campaign", "noun", "An organized effort", "The marketing campaign was successful."),
    ("campus", "noun", "The grounds of a school", "The campus has many buildings."),
    ("cancel", "verb", "To decide not to proceed", "Cancel the appointment if necessary."),
    ("candidate", "noun", "A person applying for a position", "The candidate has strong qualifications."),
    ("capable", "adjective", "Having the ability", "She is capable of leading the team."),
    ("capacity", "noun", "The maximum amount", "The stadium has a capacity of 50000."),
    ("capital", "noun", "The main city of a country", "Seoul is the capital of South Korea."),
    ("captain", "noun", "The leader of a team", "The captain led the ship safely."),
    ("capture", "verb", "To take into custody", "The police captured the criminal."),
    ("car", "noun", "A motor vehicle", "She drives to work by car."),
    ("card", "noun", "A piece of stiff paper", "Send a birthday card."),
    ("care", "noun", "The provision of what is necessary", "Take care of your health."),
    ("career", "noun", "An occupation over a period", "She built a successful career."),
    ("careful", "adjective", "Done with attention", "Be careful when crossing the street."),
    ("carefully", "adverb", "With great attention", "Read the instructions carefully."),
    ("carry", "verb", "To support and move", "Carry the bags to the car."),
    ("case", "noun", "An instance or example", "In this case, we should proceed."),
    ("cash", "noun", "Money in coins or notes", "I prefer to pay in cash."),
    ("cat", "noun", "A small domesticated animal", "The cat sleeps on the couch."),
    ("catch", "verb", "To capture or seize", "Catch the ball with both hands."),
    ("category", "noun", "A class or division", "Books are organized by category."),
    ("cause", "noun", "A reason for an action", "Identify the cause of the problem."),
    ("celebrate", "verb", "To observe a special occasion", "Celebrate your achievements."),
    ("cell", "noun", "The basic unit of life", "Cells divide to create new cells."),
    ("center", "noun", "The middle point", "The statue stands in the center."),
    ("central", "adjective", "At the center", "The central location is convenient."),
    ("century", "noun", "A period of 100 years", "Technology advanced in the 21st century."),
    ("ceremony", "noun", "A formal event", "The wedding ceremony was beautiful."),
    ("certain", "adjective", "Known for sure", "I am certain about the facts."),
    ("certainly", "adverb", "Without doubt", "I will certainly attend."),
    ("chain", "noun", "A series of connected links", "The dog was on a chain."),
    ("chair", "noun", "A seat for one person", "Pull up a chair and sit down."),
    ("challenge", "noun", "A difficult task", "Learning a language is a challenge."),
    ("champion", "noun", "A winner of a competition", "The champion defended the title."),
    ("chance", "noun", "A possibility of something happening", "Take a chance and try."),
    ("change", "verb", "To make different", "Change your approach if needed."),
    ("channel", "noun", "A medium for communication", "Switch to another TV channel."),
    ("chapter", "noun", "A main division of a book", "Read chapter five tonight."),
    ("character", "noun", "A person in a story", "The main character is brave."),
    ("characteristic", "noun", "A typical feature", "Honesty is her main characteristic."),
    ("charge", "verb", "To demand payment", "The hotel charges extra for parking."),
    ("charity", "noun", "An organization helping those in need", "Donate to charity regularly."),
    ("chart", "noun", "A diagram showing information", "The chart displays sales data."),
    ("cheap", "adjective", "Low in price", "The product is cheap but good quality."),
    ("check", "verb", "To examine for accuracy", "Check your answers before submitting."),
    ("chemical", "adjective", "Relating to chemistry", "Chemical reactions occur constantly."),
    ("chest", "noun", "The front of the body", "He felt pain in his chest."),
    ("chicken", "noun", "A domestic fowl", "We had chicken for dinner."),
    ("chief", "adjective", "Most important", "The chief concern is safety."),
    ("child", "noun", "A young human", "The child played in the park."),
    ("childhood", "noun", "The state of being a child", "Childhood memories are precious."),
    ("choice", "noun", "An act of selecting", "Make the right choice."),
    ("choose", "verb", "To select from options", "Choose wisely."),
    ("church", "noun", "A building for worship", "They attend church on Sundays."),
    ("circle", "noun", "A round shape", "Draw a circle on the paper."),
    ("circumstance", "noun", "A condition connected with an event", "Under normal circumstances we would agree."),
    ("citizen", "noun", "A person who belongs to a country", "Every citizen has rights."),
    ("city", "noun", "A large town", "The city is crowded."),
    ("civil", "adjective", "Relating to citizens", "Civil rights are protected by law."),
    ("claim", "verb", "To assert or demand", "He claimed his innocence."),
    ("class", "noun", "A group of students", "The class starts at 9 AM."),
    ("classic", "adjective", "Of the highest quality over time", "Shakespeare wrote many classic plays."),
    ("classroom", "noun", "A room for teaching", "The classroom has 30 desks."),
    ("clean", "adjective", "Free from dirt", "Keep your room clean."),
    ("clear", "adjective", "Easy to understand", "The instructions are clear."),
    ("clearly", "adverb", "In a clear manner", "Speak clearly so everyone can hear."),
    ("client", "noun", "A customer", "The lawyer met with her client."),
    ("climate", "noun", "The weather conditions of an area", "Climate change affects everyone."),
    ("climb", "verb", "To go up", "Climb the stairs to the second floor."),
    ("clock", "noun", "A device that shows time", "The clock struck midnight."),
    ("close", "verb", "To shut", "Close the door quietly."),
    ("closely", "adverb", "In a close manner", "Watch the process closely."),
    ("clothes", "noun", "Items worn on the body", "Wash your clothes regularly."),
    ("cloud", "noun", "A mass of water vapor in the sky", "The cloud blocked the sun."),
    ("club", "noun", "An organization for people with common interests", "Join the book club."),
    ("coach", "noun", "A person who trains athletes", "The coach motivated the team."),
    ("coast", "noun", "The edge of land near the sea", "We drove along the coast."),
    ("coat", "noun", "An outer garment", "Wear a coat in winter."),
    ("code", "noun", "A system of rules or symbols", "The programmer wrote efficient code."),
    ("coffee", "noun", "A hot beverage", "I drink coffee every morning."),
    ("cold", "adjective", "Of or at a low temperature", "The winter is very cold here."),
    ("collect", "verb", "To gather together", "She collects stamps as a hobby."),
    ("collection", "noun", "A group of things gathered together", "He has a large book collection."),
    ("college", "noun", "An educational institution", "She graduated from college last year."),
    ("color", "noun", "A property of light", "What is your favorite color?"),
    ("column", "noun", "A vertical division of a page", "Read the first column carefully."),
    ("combination", "noun", "A joining of different things", "The combination of colors is beautiful."),
    ("combine", "verb", "To join together", "Combine the ingredients in a bowl."),
    ("come", "verb", "To move toward", "Please come to my office."),
    ("comfort", "noun", "A state of ease", "The chair provides great comfort."),
    ("comfortable", "adjective", "Providing comfort", "The bed is very comfortable."),
    ("command", "noun", "An order or instruction", "The general gave the command to advance."),
    ("comment", "noun", "A remark or observation", "She made a helpful comment."),
    ("commercial", "adjective", "Related to commerce", "The commercial district is busy."),
    ("commission", "noun", "A fee for services", "The agent earned a commission."),
    ("commit", "verb", "To carry out or pledge", "He committed to finishing the project."),
    ("commitment", "noun", "The state of being dedicated", "Her commitment to work is admirable."),
    ("committee", "noun", "A group appointed for a purpose", "The committee will meet tomorrow."),
    ("common", "adjective", "Occurring frequently", "Colds are common in winter."),
    ("communicate", "verb", "To share information", "We communicate via email."),
    ("communication", "noun", "The exchange of information", "Good communication is essential."),
    ("community", "noun", "A group of people living together", "The community organized a cleanup."),
    ("company", "noun", "A business organization", "She works for a large company."),
    ("compare", "verb", "To examine for similarities", "Compare the two products carefully."),
    ("comparison", "noun", "The act of comparing", "In comparison, this option is better."),
    ("compete", "verb", "To strive against others", "Athletes compete for medals."),
    ("competition", "noun", "A contest between rivals", "The competition was fierce."),
    ("competitive", "adjective", "Relating to competition", "The market is very competitive."),
    ("complain", "verb", "To express dissatisfaction", "Customers complain about the service."),
    ("complaint", "noun", "An expression of dissatisfaction", "File a complaint with the manager."),
    ("complete", "adjective", "Having all parts", "The set is complete."),
    ("completely", "adverb", "Totally; entirely", "The task is completely finished."),
]
