# 0-60 Level Words Part 1 (1-200)
WORDS_0_60_PART1 = [
    ("abandon", "verb", "To leave behind or give up completely", "The crew had to abandon the sinking ship."),
    ("ability", "noun", "The capacity to do something", "She has the ability to solve complex problems."),
    ("able", "adjective", "Having the power or skill to do something", "He is able to speak three languages."),
    ("about", "preposition", "Concerning or regarding", "The book is about ancient history."),
    ("above", "preposition", "At a higher level than", "The plane flew above the clouds."),
    ("abroad", "adverb", "In or to a foreign country", "She studied abroad for two years."),
    ("absence", "noun", "The state of being away", "His absence was noticed by everyone."),
    ("absent", "adjective", "Not present in a place", "Several students were absent today."),
    ("absolute", "adjective", "Complete and total", "The king had absolute power."),
    ("absorb", "verb", "To take in or soak up", "Plants absorb water through their roots."),
    ("abstract", "adjective", "Existing in thought but not physical", "Love is an abstract concept."),
    ("academic", "adjective", "Related to education", "She excels in academic subjects."),
    ("accept", "verb", "To receive willingly", "Please accept my sincere apology."),
    ("access", "noun", "The means to approach or enter", "Students have access to the library."),
    ("accident", "noun", "An unexpected event causing damage", "The accident blocked traffic."),
    ("accommodate", "verb", "To provide space for", "The hotel can accommodate 200 guests."),
    ("accompany", "verb", "To go somewhere with someone", "May I accompany you to the event?"),
    ("accomplish", "verb", "To achieve successfully", "She accomplished her goal."),
    ("according", "preposition", "As stated by", "According to the report, sales increased."),
    ("account", "noun", "A record of events", "He gave a detailed account of the trip."),
    ("accurate", "adjective", "Correct in all details", "The information must be accurate."),
    ("achieve", "verb", "To successfully reach a goal", "Hard work helps you achieve success."),
    ("achievement", "noun", "Something accomplished successfully", "Graduating was a great achievement."),
    ("acknowledge", "verb", "To accept or admit", "She acknowledged her mistake."),
    ("acquire", "verb", "To obtain or gain", "He acquired a new skill."),
    ("across", "preposition", "From one side to the other", "They walked across the bridge."),
    ("act", "verb", "To take action or perform", "We must act quickly."),
    ("action", "noun", "The process of doing something", "Immediate action is required."),
    ("active", "adjective", "Engaging in activity", "She leads an active lifestyle."),
    ("activity", "noun", "A thing that a person does", "Swimming is a popular activity."),
    ("actual", "adjective", "Existing in fact", "The actual cost was higher."),
    ("adapt", "verb", "To adjust to new conditions", "Animals adapt to their environment."),
    ("add", "verb", "To join to something else", "Add salt to the soup."),
    ("addition", "noun", "The action of adding", "The addition of a pool increased value."),
    ("additional", "adjective", "Added or extra", "Additional information is needed."),
    ("address", "noun", "The location of a building", "What is your home address?"),
    ("adequate", "adjective", "Sufficient for a purpose", "The food supply was adequate."),
    ("adjust", "verb", "To alter slightly", "Please adjust the volume."),
    ("administration", "noun", "The management of affairs", "The administration announced new policies."),
    ("admit", "verb", "To confess or acknowledge", "He admitted his fault."),
    ("adopt", "verb", "To take up or start to use", "They adopted a new approach."),
    ("adult", "noun", "A fully grown person", "Adults must supervise children."),
    ("advance", "verb", "To move forward", "Technology continues to advance."),
    ("advanced", "adjective", "Far on in progress", "She took an advanced course."),
    ("advantage", "noun", "A favorable condition", "Experience is an advantage."),
    ("adventure", "noun", "An exciting experience", "The trip was a great adventure."),
    ("advice", "noun", "Guidance offered by someone", "She gave me helpful advice."),
    ("advise", "verb", "To offer suggestions", "I advise you to study harder."),
    ("affair", "noun", "An event or matter", "Foreign affairs are complex."),
    ("affect", "verb", "To have an impact on", "Weather affects crop growth."),
    ("afford", "verb", "To have enough money for", "I cannot afford a new car."),
    ("afraid", "adjective", "Feeling fear", "She was afraid of the dark."),
    ("after", "preposition", "Following in time", "We will meet after lunch."),
    ("again", "adverb", "Once more", "Please say that again."),
    ("against", "preposition", "In opposition to", "They voted against the proposal."),
    ("age", "noun", "The length of time lived", "What is your age?"),
    ("agency", "noun", "An organization providing services", "The agency handles travel bookings."),
    ("agent", "noun", "A person who acts for another", "The real estate agent sold the house."),
    ("agree", "verb", "To have the same opinion", "We agree on this matter."),
    ("agreement", "noun", "A mutual arrangement", "They signed an agreement."),
    ("agriculture", "noun", "The practice of farming", "Agriculture is vital for food supply."),
    ("ahead", "adverb", "Further forward", "The road ahead is clear."),
    ("aid", "noun", "Help or support", "The country received foreign aid."),
    ("aim", "noun", "A purpose or intention", "Her aim is to become a doctor."),
    ("air", "noun", "The invisible gases around us", "Fresh air is refreshing."),
    ("aircraft", "noun", "A vehicle that flies", "The aircraft landed safely."),
    ("airline", "noun", "A company providing air transport", "The airline offers cheap flights."),
    ("airport", "noun", "A place where aircraft land", "The airport was crowded."),
    ("alarm", "noun", "A warning signal", "The fire alarm went off."),
    ("alive", "adjective", "Living; not dead", "The patient is still alive."),
    ("all", "determiner", "The whole quantity", "All students must attend."),
    ("allow", "verb", "To permit", "Parents allow children to play."),
    ("almost", "adverb", "Nearly; not quite", "The project is almost complete."),
    ("alone", "adjective", "Without others", "She lives alone."),
    ("along", "preposition", "Moving in a direction", "Walk along the river."),
    ("already", "adverb", "Before now", "I have already finished."),
    ("also", "adverb", "In addition", "He also speaks French."),
    ("alter", "verb", "To change in character", "Do not alter the document."),
    ("alternative", "noun", "Another choice", "Walking is an alternative to driving."),
    ("although", "conjunction", "Despite the fact that", "Although tired, she continued working."),
    ("always", "adverb", "At all times", "She always arrives on time."),
    ("amaze", "verb", "To surprise greatly", "The magic trick amazed everyone."),
    ("amount", "noun", "A quantity of something", "A large amount of money was spent."),
    ("analysis", "noun", "Detailed examination", "The analysis revealed new findings."),
    ("analyze", "verb", "To examine in detail", "Scientists analyze data carefully."),
    ("ancient", "adjective", "Belonging to the distant past", "Ancient civilizations fascinate historians."),
    ("anger", "noun", "A strong feeling of displeasure", "His anger was evident."),
    ("angle", "noun", "The space between two lines", "Measure the angle carefully."),
    ("angry", "adjective", "Feeling anger", "She was angry about the decision."),
    ("animal", "noun", "A living organism", "Dogs are loyal animals."),
    ("announce", "verb", "To make a public statement", "The company announced new products."),
    ("annual", "adjective", "Occurring once a year", "The annual report was published."),
    ("another", "determiner", "One more", "Would you like another cup of tea?"),
    ("answer", "noun", "A response to a question", "The answer is correct."),
    ("anticipate", "verb", "To expect or predict", "We anticipate a large turnout."),
    ("anxiety", "noun", "A feeling of worry", "Exam anxiety is common among students."),
    ("anxious", "adjective", "Feeling worried", "She was anxious about the interview."),
    ("any", "determiner", "One or some of something", "Do you have any questions?"),
    ("anybody", "pronoun", "Any person", "Is anybody home?"),
    ("anyone", "pronoun", "Any person at all", "Anyone can participate."),
    ("anything", "pronoun", "Any thing at all", "Is there anything I can help with?"),
    ("anywhere", "adverb", "In or to any place", "You can sit anywhere."),
    ("apart", "adverb", "Separated by a distance", "They live far apart."),
    ("apartment", "noun", "A set of rooms for living", "She rented a small apartment."),
    ("apparent", "adjective", "Clearly visible", "The solution became apparent."),
    ("appeal", "noun", "A serious request", "The charity made an appeal for donations."),
    ("appear", "verb", "To come into sight", "Stars appear at night."),
    ("appearance", "noun", "The way someone looks", "First appearances can be deceiving."),
    ("application", "noun", "A formal request", "Submit your application by Friday."),
    ("apply", "verb", "To make a formal request", "She applied for the job."),
    ("appoint", "verb", "To assign a job or role", "They appointed a new manager."),
    ("appreciate", "verb", "To recognize the value of", "I appreciate your help."),
    ("approach", "noun", "A way of dealing with something", "We need a new approach."),
    ("appropriate", "adjective", "Suitable or proper", "Wear appropriate clothing."),
    ("approve", "verb", "To officially agree to", "The board approved the plan."),
    ("approximately", "adverb", "Close to an exact amount", "It costs approximately fifty dollars."),
    ("area", "noun", "A region or space", "The area is known for tourism."),
    ("argue", "verb", "To give reasons for or against", "They argued about politics."),
    ("argument", "noun", "A disagreement or debate", "The argument lasted for hours."),
    ("arise", "verb", "To come into being", "Problems may arise unexpectedly."),
    ("arm", "noun", "The upper limb of the body", "He broke his arm playing soccer."),
    ("army", "noun", "An organized military force", "The army defended the border."),
    ("around", "preposition", "On all sides of", "Trees grow around the lake."),
    ("arrange", "verb", "To put in order", "Please arrange the books alphabetically."),
    ("arrangement", "noun", "A plan or preparation", "We made arrangements for the trip."),
    ("arrest", "verb", "To seize by legal authority", "Police arrested the suspect."),
    ("arrival", "noun", "The act of arriving", "Announce your arrival in advance."),
    ("arrive", "verb", "To reach a destination", "The train will arrive at noon."),
    ("art", "noun", "Creative expression", "Art enriches our lives."),
    ("article", "noun", "A piece of writing", "I read an interesting article."),
    ("artificial", "adjective", "Made by humans", "Artificial flowers look real."),
    ("artist", "noun", "A person who creates art", "The artist displayed her paintings."),
    ("aspect", "noun", "A particular part or feature", "Consider every aspect of the issue."),
    ("assess", "verb", "To evaluate or estimate", "Teachers assess student progress."),
    ("assessment", "noun", "The act of evaluating", "The assessment was comprehensive."),
    ("asset", "noun", "A useful or valuable thing", "Knowledge is a valuable asset."),
    ("assign", "verb", "To allocate a task", "The teacher assigned homework."),
    ("assignment", "noun", "A task given to someone", "Complete the assignment by Monday."),
    ("assist", "verb", "To help or support", "Volunteers assist at the event."),
    ("assistance", "noun", "Help or support", "Thank you for your assistance."),
    ("assistant", "noun", "A person who helps", "The assistant organized the files."),
    ("associate", "verb", "To connect in the mind", "People associate summer with vacation."),
    ("association", "noun", "A group organized for a purpose", "The association holds annual meetings."),
    ("assume", "verb", "To suppose without proof", "Do not assume anything."),
    ("assumption", "noun", "Something taken for granted", "The assumption proved incorrect."),
    ("assure", "verb", "To tell positively", "I assure you it is safe."),
    ("atmosphere", "noun", "The air surrounding Earth", "The atmosphere protects us from radiation."),
    ("attach", "verb", "To fasten or join", "Attach the document to the email."),
    ("attack", "verb", "To act aggressively against", "The army launched an attack."),
    ("attempt", "verb", "To try to do something", "She attempted to climb the mountain."),
    ("attend", "verb", "To be present at", "Please attend the meeting."),
    ("attention", "noun", "Notice or awareness", "Pay attention to the instructions."),
    ("attitude", "noun", "A settled way of thinking", "A positive attitude helps."),
    ("attorney", "noun", "A lawyer", "The attorney represented the client."),
    ("attract", "verb", "To draw interest", "The show attracted large crowds."),
    ("attractive", "adjective", "Pleasing in appearance", "The offer is very attractive."),
    ("attribute", "verb", "To regard as caused by", "Success can be attributed to hard work."),
    ("audience", "noun", "People watching a performance", "The audience applauded loudly."),
    ("author", "noun", "A writer of a book", "The author signed copies of his book."),
    ("authority", "noun", "The power to give orders", "The police have authority to arrest."),
    ("available", "adjective", "Ready for use", "The room is available now."),
    ("average", "adjective", "Typical or ordinary", "The average score was 75."),
    ("avoid", "verb", "To keep away from", "Avoid eating too much sugar."),
    ("award", "noun", "A prize for achievement", "She received an award for excellence."),
    ("aware", "adjective", "Having knowledge of", "Be aware of your surroundings."),
    ("awareness", "noun", "Knowledge or perception", "Raise awareness about health issues."),
    ("away", "adverb", "At a distance", "The store is two miles away."),
    ("baby", "noun", "A very young child", "The baby is sleeping peacefully."),
    ("back", "noun", "The rear surface of the body", "He hurt his back lifting boxes."),
    ("background", "noun", "A person's past experiences", "Her background is in finance."),
    ("bad", "adjective", "Of poor quality", "The weather was bad yesterday."),
    ("badly", "adverb", "In a severe manner", "He was badly injured."),
    ("bag", "noun", "A container for carrying things", "She packed her bag for the trip."),
    ("balance", "noun", "An even distribution of weight", "Maintain balance while walking."),
    ("ball", "noun", "A round object used in games", "Kick the ball into the goal."),
    ("ban", "verb", "To officially prohibit", "The city banned smoking in parks."),
    ("band", "noun", "A group of musicians", "The band played rock music."),
    ("bank", "noun", "A financial institution", "Deposit money at the bank."),
    ("bar", "noun", "A long rigid piece", "The metal bar was heavy."),
    ("barrier", "noun", "Something that blocks passage", "Language can be a barrier."),
    ("base", "noun", "The bottom support", "The statue has a marble base."),
    ("basic", "adjective", "Forming an essential foundation", "Learn the basic rules first."),
    ("basically", "adverb", "In essence", "Basically, the plan is simple."),
    ("basis", "noun", "The underlying support", "Trust is the basis of friendship."),
    ("battery", "noun", "A device storing electrical energy", "The battery needs charging."),
    ("battle", "noun", "A fight between armed forces", "The battle lasted three days."),
    ("beach", "noun", "A sandy shore by the sea", "We spent the day at the beach."),
    ("bear", "verb", "To carry or support", "I cannot bear the pain anymore."),
    ("beat", "verb", "To strike repeatedly", "The drummer beat the drums."),
    ("beautiful", "adjective", "Pleasing to the senses", "The sunset was beautiful."),
    ("beauty", "noun", "A quality that pleases", "Natural beauty surrounds us."),
    ("become", "verb", "To begin to be", "She wants to become a doctor."),
    ("bed", "noun", "Furniture for sleeping", "Go to bed early tonight."),
    ("bedroom", "noun", "A room for sleeping", "The bedroom is upstairs."),
    ("before", "preposition", "Earlier than", "Finish your work before lunch."),
    ("begin", "verb", "To start", "Classes begin next week."),
    ("beginning", "noun", "The start of something", "This is just the beginning."),
]
