# 60-80 Level Words Part 2 (301-600)
WORDS_60_80_PART2 = [
    ("hear", "verb", "To perceive sound", "I can hear music."),
    ("hearing", "noun", "The ability to hear", "His hearing is excellent."),
    ("heart", "noun", "The organ that pumps blood", "The heart beats faster during exercise."),
    ("heat", "noun", "The quality of being hot", "The heat was unbearable."),
    ("heaven", "noun", "A place of eternal happiness", "Heaven is peaceful."),
    ("heavy", "adjective", "Of great weight", "The box is heavy."),
    ("height", "noun", "The measurement from base to top", "What is your height?"),
    ("helicopter", "noun", "An aircraft with rotating blades", "The helicopter landed on the roof."),
    ("hell", "noun", "A place of suffering", "The traffic was hell."),
    ("hello", "interjection", "A greeting", "Hello, how are you?"),
    ("help", "verb", "To assist", "Can you help me?"),
    ("helpful", "adjective", "Giving help", "The staff was helpful."),
    ("her", "pronoun", "Belonging to a female", "This is her book."),
    ("here", "adverb", "In this place", "Come here please."),
    ("heritage", "noun", "Valued traditions passed down", "Preserve cultural heritage."),
    ("hero", "noun", "A person admired for courage", "The firefighter is a hero."),
    ("herself", "pronoun", "Used for emphasis", "She did it herself."),
    ("hesitate", "verb", "To pause before acting", "Do not hesitate to ask."),
    ("hide", "verb", "To conceal from view", "Hide the gift."),
    ("high", "adjective", "Extending far up", "The mountain is high."),
    ("highlight", "verb", "To emphasize", "Highlight the key points."),
    ("highly", "adverb", "To a high degree", "She is highly qualified."),
    ("highway", "noun", "A main road", "Drive carefully on the highway."),
    ("hill", "noun", "A raised area of land", "Climb the hill."),
    ("him", "pronoun", "Used to refer to a male", "Give it to him."),
    ("himself", "pronoun", "Used for emphasis", "He hurt himself."),
    ("hip", "noun", "The joint between leg and torso", "She injured her hip."),
    ("hire", "verb", "To employ for wages", "The company will hire 20 people."),
    ("his", "pronoun", "Belonging to a male", "This is his car."),
    ("historian", "noun", "An expert in history", "The historian wrote a book."),
    ("historic", "adjective", "Famous in history", "This is a historic moment."),
    ("historical", "adjective", "Relating to history", "Historical records are important."),
    ("history", "noun", "The study of past events", "Learn from history."),
    ("hit", "verb", "To strike forcefully", "He hit the ball."),
    ("hold", "verb", "To grasp in the hand", "Hold my hand."),
    ("holder", "noun", "A person who holds something", "The ticket holder may enter."),
    ("hole", "noun", "An opening or hollow space", "Fill the hole in the ground."),
    ("holiday", "noun", "A day of celebration", "Happy holiday!"),
    ("holy", "adjective", "Dedicated to a religious purpose", "Visit the holy site."),
    ("home", "noun", "A place where one lives", "Home is where the heart is."),
    ("homeless", "adjective", "Without a home", "Help the homeless."),
    ("honest", "adjective", "Free from deceit", "Be honest with me."),
    ("honor", "noun", "High respect", "It is an honor to meet you."),
    ("hope", "noun", "A feeling of expectation", "Never lose hope."),
    ("hopefully", "adverb", "In a hopeful manner", "Hopefully, it will work."),
    ("horizon", "noun", "The line where earth meets sky", "The sun set on the horizon."),
    ("horror", "noun", "An intense feeling of fear", "Horror movies scare me."),
    ("horse", "noun", "A large four-legged animal", "She rides a horse."),
    ("hospital", "noun", "A place for medical treatment", "Go to the hospital."),
    ("host", "noun", "A person who receives guests", "The host welcomed everyone."),
    ("hot", "adjective", "Having a high temperature", "The soup is hot."),
    ("hotel", "noun", "A place for travelers to stay", "Book a hotel room."),
    ("hour", "noun", "A period of 60 minutes", "Wait for one hour."),
    ("house", "noun", "A building for living", "They bought a new house."),
    ("household", "noun", "A house and its occupants", "Household expenses increased."),
    ("housing", "noun", "Buildings for people to live in", "Affordable housing is needed."),
    ("how", "adverb", "In what way", "How do you do it?"),
    ("however", "adverb", "Nevertheless", "However, we must try."),
    ("huge", "adjective", "Extremely large", "The whale is huge."),
    ("human", "adjective", "Relating to people", "Human rights are universal."),
    ("humor", "noun", "The quality of being amusing", "He has a good sense of humor."),
    ("hundred", "number", "The number 100", "A hundred years ago."),
    ("hunger", "noun", "A feeling of needing food", "Fight world hunger."),
    ("hungry", "adjective", "Feeling the need to eat", "I am hungry."),
    ("hunt", "verb", "To chase and kill animals", "They hunt deer in the forest."),
    ("hunter", "noun", "A person who hunts", "The hunter tracked the animal."),
    ("hurry", "verb", "To move or act quickly", "Hurry up, we are late!"),
    ("hurt", "verb", "To cause pain", "My leg hurts."),
    ("husband", "noun", "A married man", "Her husband works abroad."),
    ("hypothesis", "noun", "A proposed explanation", "Test the hypothesis."),
    ("ice", "noun", "Frozen water", "Put ice in the drink."),
    ("idea", "noun", "A thought or suggestion", "That is a great idea."),
    ("ideal", "adjective", "Perfect or most suitable", "This is the ideal solution."),
    ("identical", "adjective", "Exactly the same", "The twins look identical."),
    ("identify", "verb", "To recognize or establish", "Identify the problem first."),
    ("identity", "noun", "Who a person is", "Protect your identity online."),
    ("ideology", "noun", "A system of ideas", "Political ideology varies."),
    ("ignore", "verb", "To refuse to notice", "Do not ignore the warning."),
    ("ill", "adjective", "Not in good health", "She felt ill."),
    ("illegal", "adjective", "Against the law", "Illegal activities are punished."),
    ("illness", "noun", "A disease or period of sickness", "Recover from illness."),
    ("illustrate", "verb", "To explain with examples", "Illustrate your point clearly."),
    ("illustration", "noun", "A picture explaining something", "The book has many illustrations."),
    ("image", "noun", "A visual representation", "The image is clear."),
    ("imagination", "noun", "The ability to form mental images", "Use your imagination."),
    ("imagine", "verb", "To form a mental image", "Imagine a better future."),
    ("immediate", "adjective", "Occurring at once", "Take immediate action."),
    ("immediately", "adverb", "At once", "Call me immediately."),
    ("immigrant", "noun", "A person who moves to another country", "Immigrants contribute to society."),
    ("immigration", "noun", "The act of immigrating", "Immigration laws changed."),
    ("impact", "noun", "A strong effect", "The impact was significant."),
    ("implement", "verb", "To put into effect", "Implement the new policy."),
    ("implementation", "noun", "The act of implementing", "Implementation takes time."),
    ("implication", "noun", "A possible consequence", "Consider the implications."),
    ("imply", "verb", "To suggest without stating", "What did you imply?"),
    ("import", "verb", "To bring goods from another country", "We import coffee."),
    ("importance", "noun", "The state of being important", "Understand the importance."),
    ("important", "adjective", "Of great significance", "This is important information."),
    ("impose", "verb", "To force something on someone", "Impose strict rules."),
    ("impossible", "adjective", "Not able to occur", "Nothing is impossible."),
    ("impress", "verb", "To make someone feel admiration", "She impressed the interviewer."),
    ("impression", "noun", "An idea or feeling", "First impressions matter."),
    ("impressive", "adjective", "Evoking admiration", "The performance was impressive."),
    ("improve", "verb", "To make better", "Improve your skills daily."),
    ("improvement", "noun", "The act of improving", "There was significant improvement."),
    ("in", "preposition", "Inside a space", "Put it in the box."),
    ("incentive", "noun", "Something that motivates", "Offer incentives for good work."),
    ("incident", "noun", "An event or occurrence", "Report the incident immediately."),
    ("include", "verb", "To contain as part of a whole", "The price includes tax."),
    ("including", "preposition", "Containing as part of", "Everyone came, including the boss."),
    ("income", "noun", "Money received regularly", "Her income increased."),
    ("incorporate", "verb", "To include as part of something", "Incorporate feedback into the design."),
    ("increase", "verb", "To make or become larger", "Sales increased this month."),
    ("increasingly", "adverb", "More and more", "It is increasingly difficult."),
    ("incredible", "adjective", "Impossible to believe", "The view was incredible."),
    ("incredibly", "adverb", "To a great degree", "She is incredibly talented."),
    ("indeed", "adverb", "In truth", "Indeed, you are correct."),
    ("independence", "noun", "The state of being independent", "Independence Day is July 4th."),
    ("independent", "adjective", "Free from outside control", "She is financially independent."),
    ("index", "noun", "An alphabetical list", "Check the book's index."),
    ("Indian", "adjective", "Relating to India", "Indian cuisine is flavorful."),
    ("indicate", "verb", "To point out", "The sign indicates the exit."),
    ("indication", "noun", "A sign or piece of information", "There was no indication of trouble."),
    ("individual", "noun", "A single person", "Every individual matters."),
    ("industrial", "adjective", "Relating to industry", "Industrial production increased."),
    ("industry", "noun", "Economic activity", "The tech industry is growing."),
    ("infant", "noun", "A very young child", "Care for the infant carefully."),
    ("infection", "noun", "The invasion of the body by organisms", "Prevent infection by washing hands."),
    ("inflation", "noun", "A general increase in prices", "Inflation affects purchasing power."),
    ("influence", "noun", "The power to affect others", "She has great influence."),
    ("inform", "verb", "To give information to", "Please inform me of any changes."),
    ("information", "noun", "Facts provided about something", "Gather all necessary information."),
    ("ingredient", "noun", "A component of a mixture", "List all ingredients."),
    ("initial", "adjective", "Occurring at the beginning", "The initial response was positive."),
    ("initially", "adverb", "At first", "I was initially skeptical."),
    ("initiative", "noun", "The ability to act independently", "Take the initiative."),
    ("injury", "noun", "Physical harm or damage", "The injury healed quickly."),
    ("inner", "adjective", "Located inside", "Find your inner strength."),
    ("innocent", "adjective", "Not guilty", "He was proven innocent."),
    ("innovation", "noun", "A new method or idea", "Innovation drives progress."),
    ("innovative", "adjective", "Introducing new ideas", "The company is innovative."),
    ("input", "noun", "What is put in", "We need your input."),
    ("inquiry", "noun", "An act of asking", "Submit an inquiry."),
    ("insect", "noun", "A small arthropod animal", "Insects are everywhere in summer."),
    ("insert", "verb", "To place inside", "Insert the card into the slot."),
    ("inside", "preposition", "Within", "Stay inside the building."),
    ("insight", "noun", "The capacity to understand", "Gain insight into the problem."),
    ("insist", "verb", "To demand firmly", "She insisted on paying."),
    ("inspect", "verb", "To look at closely", "Inspect the goods upon arrival."),
    ("inspection", "noun", "A careful examination", "The inspection revealed defects."),
    ("inspector", "noun", "A person who inspects", "The inspector checked the building."),
    ("inspiration", "noun", "The process of being mentally stimulated", "Find inspiration in nature."),
    ("inspire", "verb", "To fill with the urge to do something", "Her story inspired me."),
    ("install", "verb", "To place in position for use", "Install the software."),
    ("installation", "noun", "The action of installing", "Installation takes one hour."),
    ("instance", "noun", "An example", "In this instance, we succeeded."),
    ("instant", "adjective", "Happening immediately", "Get instant results."),
    ("instantly", "adverb", "At once", "The message arrived instantly."),
    ("instead", "adverb", "As an alternative", "Use this instead."),
    ("institution", "noun", "An established organization", "Educational institutions are important."),
    ("institutional", "adjective", "Relating to institutions", "Institutional reform is needed."),
    ("instruction", "noun", "Detailed information on procedure", "Follow the instructions."),
    ("instructor", "noun", "A person who teaches", "The instructor explained the lesson."),
    ("instrument", "noun", "A tool for precise work", "Play a musical instrument."),
    ("insurance", "noun", "A practice of protection against loss", "Buy health insurance."),
    ("intellectual", "adjective", "Relating to the intellect", "Intellectual discussions are stimulating."),
    ("intelligence", "noun", "The ability to acquire knowledge", "Artificial intelligence is advancing."),
    ("intelligent", "adjective", "Having high intelligence", "She is very intelligent."),
    ("intend", "verb", "To have as a plan", "I intend to finish today."),
    ("intense", "adjective", "Of extreme force or degree", "The competition was intense."),
    ("intensity", "noun", "The quality of being intense", "Increase the intensity."),
    ("intention", "noun", "A thing intended", "His intention was good."),
    ("interaction", "noun", "Reciprocal action", "Social interaction is important."),
    ("interest", "noun", "A feeling of curiosity", "Take interest in your work."),
    ("interested", "adjective", "Showing curiosity", "I am interested in history."),
    ("interesting", "adjective", "Arousing curiosity", "The book is interesting."),
    ("internal", "adjective", "Of or inside something", "Internal affairs are handled separately."),
    ("international", "adjective", "Existing between nations", "International cooperation is essential."),
    ("Internet", "noun", "A global computer network", "The Internet connects the world."),
    ("interpret", "verb", "To explain the meaning of", "Interpret the data carefully."),
    ("interpretation", "noun", "An explanation of meaning", "Your interpretation is valid."),
    ("intervention", "noun", "The action of intervening", "Government intervention was needed."),
    ("interview", "noun", "A formal meeting for assessment", "The interview went well."),
    ("into", "preposition", "Expressing movement inside", "Go into the room."),
    ("introduce", "verb", "To make known by name", "Let me introduce myself."),
    ("introduction", "noun", "The action of introducing", "Read the introduction first."),
    ("invasion", "noun", "An unwelcome intrusion", "The invasion was unexpected."),
    ("invest", "verb", "To put money into something for profit", "Invest in stocks wisely."),
    ("investigate", "verb", "To carry out research", "Investigate the cause of the problem."),
    ("investigation", "noun", "A formal inquiry", "The investigation is ongoing."),
    ("investigator", "noun", "A person who investigates", "The investigator found evidence."),
    ("investment", "noun", "The action of investing", "Investment in education pays off."),
    ("investor", "noun", "A person who invests", "The investor bought shares."),
    ("invitation", "noun", "A request to attend", "Send an invitation."),
    ("invite", "verb", "To ask someone to come", "Invite your friends to the party."),
    ("involve", "verb", "To include as a necessary part", "The project involves teamwork."),
    ("involved", "adjective", "Participating in something", "Everyone was involved."),
    ("involvement", "noun", "The act of involving", "Community involvement is valuable."),
    ("Iranian", "adjective", "Relating to Iran", "Iranian art is beautiful."),
    ("Iraqi", "adjective", "Relating to Iraq", "Iraqi history is ancient."),
    ("Irish", "adjective", "Relating to Ireland", "Irish culture is rich."),
    ("iron", "noun", "A strong metal", "The gate is made of iron."),
    ("Islamic", "adjective", "Relating to Islam", "Islamic architecture is impressive."),
    ("island", "noun", "A piece of land surrounded by water", "The island is tropical."),
    ("Israeli", "adjective", "Relating to Israel", "Israeli technology is advanced."),
    ("issue", "noun", "An important topic", "Address the issue directly."),
    ("it", "pronoun", "Used to refer to a thing", "It is raining."),
    ("Italian", "adjective", "Relating to Italy", "Italian food is delicious."),
    ("item", "noun", "An individual thing", "Check each item carefully."),
    ("its", "determiner", "Belonging to it", "The company changed its policy."),
    ("itself", "pronoun", "Used for emphasis", "The machine turns itself off."),
    ("jacket", "noun", "A short coat", "Wear a jacket outside."),
    ("jail", "noun", "A place of confinement", "He was sent to jail."),
    ("Japanese", "adjective", "Relating to Japan", "Japanese culture is fascinating."),
    ("jet", "noun", "An aircraft powered by jet engines", "The jet flew overhead."),
    ("Jewish", "adjective", "Relating to Jews", "Jewish traditions are ancient."),
    ("job", "noun", "A paid position of employment", "She got a new job."),
    ("join", "verb", "To link or connect", "Join the club."),
    ("joint", "adjective", "Shared by two or more", "Make a joint decision."),
    ("joke", "noun", "Something said to cause laughter", "He told a funny joke."),
    ("journal", "noun", "A newspaper or magazine", "Read the academic journal."),
    ("journalist", "noun", "A person who writes for newspapers", "The journalist reported the news."),
    ("journey", "noun", "An act of traveling", "The journey took two days."),
    ("joy", "noun", "A feeling of great happiness", "The news brought joy."),
    ("judge", "noun", "A public official who decides cases", "The judge made a ruling."),
    ("judgment", "noun", "The ability to make decisions", "Use good judgment."),
    ("juice", "noun", "A drink made from fruit", "Drink orange juice."),
    ("jump", "verb", "To spring off the ground", "Jump over the fence."),
    ("junior", "adjective", "For younger people", "She is a junior employee."),
    ("jury", "noun", "A group of people who decide a verdict", "The jury reached a decision."),
    ("just", "adverb", "Exactly", "That is just what I needed."),
    ("justice", "noun", "Fair behavior or treatment", "Justice must be served."),
    ("justify", "verb", "To show to be right", "Justify your answer."),
    ("keen", "adjective", "Very interested or eager", "She is keen to learn."),
    ("keep", "verb", "To retain possession of", "Keep the change."),
    ("key", "noun", "A small metal instrument for a lock", "Find the key to success."),
    ("kick", "verb", "To strike with the foot", "Kick the ball."),
    ("kid", "noun", "A child", "The kids are playing outside."),
    ("kill", "verb", "To cause death", "Do not kill animals for sport."),
    ("killer", "noun", "A person who kills", "The killer was caught."),
    ("killing", "noun", "An act of killing", "The killing shocked the community."),
    ("kind", "noun", "A type or variety", "What kind of music do you like?"),
    ("king", "noun", "A male ruler", "The king ruled wisely."),
    ("kingdom", "noun", "A country ruled by a king", "The kingdom prospered."),
    ("kiss", "verb", "To touch with the lips", "She kissed her child goodbye."),
    ("kitchen", "noun", "A room for cooking", "Cook in the kitchen."),
    ("knee", "noun", "The joint between thigh and leg", "He hurt his knee."),
    ("knife", "noun", "A cutting instrument", "Use a sharp knife."),
    ("knock", "verb", "To strike a surface to attract attention", "Knock on the door."),
    ("know", "verb", "To be aware of", "I know the answer."),
    ("knowledge", "noun", "Information and skills acquired", "Knowledge is power."),
    ("lab", "noun", "A laboratory", "Work in the science lab."),
    ("label", "noun", "A tag identifying something", "Read the label carefully."),
    ("labor", "noun", "Work especially physical work", "Manual labor is demanding."),
    ("laboratory", "noun", "A room for scientific research", "The laboratory is well-equipped."),
    ("lack", "noun", "The state of being without", "Lack of sleep affects health."),
    ("lady", "noun", "A woman", "The lady is waiting."),
    ("lake", "noun", "A large body of water", "Swim in the lake."),
    ("land", "noun", "The part of earth not covered by water", "Buy a piece of land."),
    ("landscape", "noun", "All the features of an area", "The landscape is beautiful."),
    ("language", "noun", "A system of communication", "Learn a new language."),
    ("lap", "noun", "The flat area formed by thighs when sitting", "The cat sat on her lap."),
    ("large", "adjective", "Of great size", "The house is large."),
    ("largely", "adverb", "To a great extent", "The success was largely due to teamwork."),
    ("last", "adjective", "Coming after all others", "This is the last chance."),
    ("late", "adjective", "After the expected time", "Sorry I am late."),
    ("later", "adverb", "At a time after the present", "See you later."),
    ("latest", "adjective", "Most recent", "Read the latest news."),
    ("Latin", "adjective", "Relating to ancient Rome", "Latin is the root of many languages."),
    ("latter", "adjective", "The second of two things", "The latter option is better."),
    ("laugh", "verb", "To express amusement", "She laughed at the joke."),
    ("laughter", "noun", "The act of laughing", "Laughter is the best medicine."),
    ("launch", "verb", "To start or set in motion", "Launch the new product."),
    ("law", "noun", "A system of rules", "Obey the law."),
    ("lawn", "noun", "An area of mowed grass", "Mow the lawn."),
    ("lawsuit", "noun", "A claim brought to a court", "File a lawsuit."),
    ("lawyer", "noun", "A person who practices law", "Consult a lawyer."),
    ("lay", "verb", "To put down", "Lay the book on the table."),
    ("layer", "noun", "A thickness of material", "Add another layer of paint."),
    ("lead", "verb", "To guide or direct", "Lead the team to victory."),
    ("leader", "noun", "A person who leads", "She is a great leader."),
    ("leadership", "noun", "The action of leading", "Show strong leadership."),
    ("leading", "adjective", "Most important", "The leading cause is known."),
    ("leaf", "noun", "A flat green part of a plant", "The leaf fell from the tree."),
    ("league", "noun", "A group of sports teams", "The basketball league starts soon."),
    ("lean", "verb", "To incline from the vertical", "Lean against the wall."),
    ("learn", "verb", "To gain knowledge", "Learn something new every day."),
    ("learning", "noun", "The acquisition of knowledge", "Learning is a lifelong process."),
    ("least", "determiner", "Smallest in amount", "At least try your best."),
    ("leather", "noun", "Material made from animal skin", "The bag is made of leather."),
    ("leave", "verb", "To go away from", "Leave the room quietly."),
    ("lecture", "noun", "An educational talk", "Attend the lecture."),
]
