# 80-100 Level Words Part 2 (251-500)
WORDS_80_100_PART2 = [
    ("ardent", "adjective", "Very enthusiastic", "An ardent supporter."),
    ("ardor", "noun", "Great enthusiasm", "Work with ardor."),
    ("arduous", "adjective", "Involving difficult effort", "An arduous journey."),
    ("arena", "noun", "A place for sports events", "A sports arena."),
    ("arguable", "adjective", "Open to disagreement", "An arguable point."),
    ("arguably", "adverb", "It may be argued", "Arguably the best."),
    ("arise", "verb", "To emerge or originate", "Problems arise unexpectedly."),
    ("aristocracy", "noun", "The highest social class", "The aristocracy ruled."),
    ("aristocrat", "noun", "A member of the aristocracy", "An aristocrat by birth."),
    ("arithmetic", "noun", "The branch of math dealing with numbers", "Basic arithmetic."),
    ("armament", "noun", "Military weapons", "Reduce armaments."),
    ("aroma", "noun", "A pleasant smell", "The aroma of coffee."),
    ("arouse", "verb", "To evoke a feeling", "Arouse suspicion."),
    ("arraign", "verb", "To call before a court", "Arraign the defendant."),
    ("array", "noun", "An impressive display", "An array of options."),
    ("arrogance", "noun", "Having an exaggerated sense of importance", "Display arrogance."),
    ("arrogant", "adjective", "Having excessive pride", "An arrogant attitude."),
    ("articulate", "adjective", "Having the ability to speak clearly", "An articulate speaker."),
    ("artifact", "noun", "An object made by a human", "An ancient artifact."),
    ("artificial", "adjective", "Made by humans", "Artificial intelligence."),
    ("artillery", "noun", "Large-caliber guns", "Heavy artillery."),
    ("artisan", "noun", "A skilled craftsperson", "A local artisan."),
    ("ascend", "verb", "To go up", "Ascend the stairs."),
    ("ascendancy", "noun", "Occupation of a position of dominance", "Rise to ascendancy."),
    ("ascent", "noun", "A climb or walk upward", "A steep ascent."),
    ("ascertain", "verb", "To find out for certain", "Ascertain the facts."),
    ("ascetic", "adjective", "Characterized by severe self-discipline", "An ascetic lifestyle."),
    ("ascribe", "verb", "To attribute something to", "Ascribe success to hard work."),
    ("ashamed", "adjective", "Feeling shame", "Ashamed of behavior."),
    ("aside", "adverb", "To one side", "Put it aside."),
    ("aspiration", "noun", "A hope or ambition", "Career aspirations."),
    ("aspire", "verb", "To have a strong desire", "Aspire to greatness."),
    ("assail", "verb", "To attack violently", "Assail with criticism."),
    ("assassinate", "verb", "To murder a public figure", "Assassinate the leader."),
    ("assault", "noun", "A physical attack", "An assault on democracy."),
    ("assemble", "verb", "To gather together", "Assemble the team."),
    ("assembly", "noun", "A group gathered together", "A school assembly."),
    ("assent", "noun", "Agreement or approval", "Give your assent."),
    ("assert", "verb", "To state confidently", "Assert your rights."),
    ("assertion", "noun", "A confident statement", "A bold assertion."),
    ("assertive", "adjective", "Having confidence", "Be more assertive."),
    ("assess", "verb", "To evaluate", "Assess the situation."),
    ("assessment", "noun", "The act of assessing", "Risk assessment."),
    ("asset", "noun", "A useful or valuable thing", "A valuable asset."),
    ("assiduous", "adjective", "Showing great care", "Assiduous research."),
    ("assign", "verb", "To allocate a task", "Assign homework."),
    ("assignment", "noun", "A task allocated", "Complete the assignment."),
    ("assimilate", "verb", "To absorb information", "Assimilate new knowledge."),
    ("assimilation", "noun", "The process of assimilating", "Cultural assimilation."),
    ("assist", "verb", "To help", "Assist with the project."),
    ("assistance", "noun", "The act of helping", "Financial assistance."),
    ("assistant", "noun", "A helper", "A personal assistant."),
    ("associate", "verb", "To connect in the mind", "Associate words with images."),
    ("association", "noun", "A connection or organization", "A trade association."),
    ("assume", "verb", "To suppose to be the case", "Assume the worst."),
    ("assumption", "noun", "Something taken for granted", "A false assumption."),
    ("assurance", "noun", "A positive declaration", "Give assurance."),
    ("assure", "verb", "To tell positively", "I assure you it's true."),
    ("astonish", "verb", "To surprise greatly", "The results astonished us."),
    ("astonishing", "adjective", "Extremely surprising", "An astonishing discovery."),
    ("astound", "verb", "To shock or surprise", "Astound the audience."),
    ("astounding", "adjective", "Surprisingly impressive", "Astounding results."),
    ("astray", "adverb", "Away from the correct path", "Lead astray."),
    ("astute", "adjective", "Having sharp judgment", "An astute observation."),
    ("asylum", "noun", "A place of refuge", "Seek asylum."),
    ("asymmetric", "adjective", "Not identical on both sides", "Asymmetric design."),
    ("atrocity", "noun", "An extremely wicked act", "War atrocities."),
    ("attach", "verb", "To fasten or join", "Attach the file."),
    ("attachment", "noun", "An extra part attached", "Email attachment."),
    ("attain", "verb", "To succeed in achieving", "Attain your goals."),
    ("attainment", "noun", "The act of achieving", "Academic attainment."),
    ("attempt", "verb", "To try", "Attempt the challenge."),
    ("attend", "verb", "To be present at", "Attend the meeting."),
    ("attendance", "noun", "The act of attending", "Check attendance."),
    ("attendant", "noun", "A person providing a service", "A flight attendant."),
    ("attention", "noun", "The act of paying notice", "Pay attention."),
    ("attentive", "adjective", "Paying close attention", "An attentive listener."),
    ("attest", "verb", "To provide proof", "Attest to the truth."),
    ("attestation", "noun", "Evidence or proof", "Require attestation."),
    ("attire", "noun", "Clothes", "Formal attire required."),
    ("attitude", "noun", "A way of thinking", "A positive attitude."),
    ("attorney", "noun", "A lawyer", "Hire an attorney."),
    ("attract", "verb", "To draw interest", "Attract attention."),
    ("attraction", "noun", "The action of attracting", "Tourist attraction."),
    ("attractive", "adjective", "Pleasing to look at", "An attractive offer."),
    ("attribute", "noun", "A quality or feature", "A key attribute."),
    ("attribution", "noun", "The act of attributing", "Proper attribution."),
    ("attrition", "noun", "Gradual reduction in strength", "Staff attrition."),
    ("atypical", "adjective", "Not typical", "Atypical behavior."),
    ("auction", "noun", "A public sale", "Bid at the auction."),
    ("audacious", "adjective", "Showing bold willingness", "An audacious plan."),
    ("audacity", "noun", "Bold or arrogant behavior", "The audacity to ask."),
    ("audible", "adjective", "Able to be heard", "An audible sigh."),
    ("audience", "noun", "A group of listeners", "Address the audience."),
    ("audit", "noun", "An official inspection", "A financial audit."),
    ("audition", "noun", "A trial performance", "Attend an audition."),
    ("auditor", "noun", "A person who audits", "An independent auditor."),
    ("augment", "verb", "To make greater in size", "Augment your income."),
    ("auspicious", "adjective", "Favorable", "An auspicious start."),
    ("austere", "adjective", "Severe or strict", "Austere conditions."),
    ("austerity", "noun", "Sternness or severity", "Economic austerity."),
    ("authentic", "adjective", "Of undisputed origin", "An authentic painting."),
    ("authenticate", "verb", "To prove genuine", "Authenticate the document."),
    ("authenticity", "noun", "The quality of being authentic", "Question authenticity."),
    ("author", "noun", "A writer of a book", "A famous author."),
    ("authoritative", "adjective", "Able to be trusted", "An authoritative source."),
    ("authority", "noun", "The power to give orders", "Have authority over."),
    ("authorization", "noun", "Official permission", "Require authorization."),
    ("authorize", "verb", "To give official permission", "Authorize the payment."),
    ("autobiography", "noun", "A self-written account of one's life", "Write an autobiography."),
    ("autocracy", "noun", "Government by one person", "A political autocracy."),
    ("autocrat", "noun", "A ruler with absolute power", "The autocrat decreed."),
    ("automate", "verb", "To convert to automatic operation", "Automate the process."),
    ("autonomous", "adjective", "Self-governing", "An autonomous region."),
    ("autonomy", "noun", "The right to self-government", "Grant autonomy."),
    ("auxiliary", "adjective", "Providing supplementary support", "Auxiliary staff."),
    ("avail", "noun", "Use or benefit", "To no avail."),
    ("availability", "noun", "The state of being available", "Check availability."),
    ("available", "adjective", "Able to be used", "Rooms available."),
    ("avalanche", "noun", "A mass of snow falling rapidly", "An avalanche warning."),
    ("avant-garde", "adjective", "New and experimental", "Avant-garde art."),
    ("avarice", "noun", "Extreme greed", "Motivated by avarice."),
    ("avenge", "verb", "To inflict harm in return", "Avenge a wrong."),
    ("avenue", "noun", "A wide street", "Walk down the avenue."),
    ("average", "adjective", "The usual standard", "Above average."),
    ("averse", "adjective", "Having a strong dislike", "Averse to risk."),
    ("aversion", "noun", "A strong dislike", "An aversion to crowds."),
    ("avert", "verb", "To prevent or turn away", "Avert disaster."),
    ("avid", "adjective", "Having a keen interest", "An avid reader."),
    ("avoid", "verb", "To keep away from", "Avoid conflict."),
    ("avoidable", "adjective", "Capable of being avoided", "An avoidable mistake."),
    ("avoidance", "noun", "The action of avoiding", "Tax avoidance."),
    ("await", "verb", "To wait for", "Await instructions."),
    ("awake", "adjective", "Not asleep", "Wide awake."),
    ("awaken", "verb", "To stop sleeping", "Awaken at dawn."),
    ("award", "noun", "A prize given for achievement", "Win an award."),
    ("aware", "adjective", "Having knowledge of", "Be aware of risks."),
    ("awareness", "noun", "Knowledge or perception", "Raise awareness."),
    ("awe", "noun", "A feeling of reverence", "In awe of nature."),
    ("awesome", "adjective", "Inspiring great admiration", "An awesome sight."),
    ("awful", "adjective", "Very bad", "An awful experience."),
    ("awkward", "adjective", "Causing difficulty or embarrassment", "An awkward situation."),
    ("axiom", "noun", "A statement accepted as true", "A mathematical axiom."),
    ("axis", "noun", "An imaginary line around which something rotates", "The Earth's axis."),
    ("backdrop", "noun", "The background to a scene", "Against a historic backdrop."),
    ("backfire", "verb", "To have an opposite effect", "The plan backfired."),
    ("background", "noun", "A person's past experiences", "A diverse background."),
    ("backlash", "noun", "A strong negative reaction", "Public backlash."),
    ("backlog", "noun", "An accumulation of uncompleted work", "A huge backlog."),
    ("backup", "noun", "Support or reserve", "Create a backup."),
    ("backward", "adjective", "Directed toward the back", "Take a backward step."),
    ("badge", "noun", "A small emblem", "Wear a name badge."),
    ("baffle", "verb", "To totally bewilder", "The mystery baffled us."),
    ("bail", "noun", "Money paid to release a prisoner", "Post bail."),
    ("bait", "noun", "Something used to lure", "Use bait for fishing."),
    ("balance", "noun", "A state of equilibrium", "Maintain balance."),
    ("balanced", "adjective", "Keeping proper proportions", "A balanced diet."),
    ("bald", "adjective", "Having no hair", "A bald head."),
    ("ballot", "noun", "A process of voting", "Cast a ballot."),
    ("ban", "verb", "To officially prohibit", "Ban smoking indoors."),
    ("banal", "adjective", "Lacking originality", "A banal comment."),
    ("bandwagon", "noun", "A popular activity", "Jump on the bandwagon."),
    ("bane", "noun", "A cause of great distress", "The bane of existence."),
    ("banish", "verb", "To send away as punishment", "Banish from the kingdom."),
    ("bankrupt", "adjective", "Unable to pay debts", "Declare bankrupt."),
    ("bankruptcy", "noun", "The state of being bankrupt", "File for bankruptcy."),
    ("banner", "noun", "A long strip of cloth with a message", "Hang a banner."),
    ("banquet", "noun", "An elaborate meal", "A wedding banquet."),
    ("bar", "noun", "A place serving drinks", "Meet at the bar."),
    ("barbaric", "adjective", "Savagely cruel", "Barbaric practices."),
    ("bare", "adjective", "Not clothed or covered", "Bare essentials."),
    ("barely", "adverb", "Only just", "Barely survived."),
    ("bargain", "noun", "An agreement between parties", "Make a bargain."),
    ("barrage", "noun", "A concentrated outpouring", "A barrage of questions."),
    ("barren", "adjective", "Not able to produce vegetation", "Barren land."),
    ("barrier", "noun", "Something that blocks", "A language barrier."),
    ("barter", "verb", "To exchange goods without money", "Barter for supplies."),
    ("baseline", "noun", "A starting point for comparison", "Establish a baseline."),
    ("basin", "noun", "A bowl or enclosed area", "A river basin."),
    ("basis", "noun", "The foundation for something", "On a daily basis."),
    ("batch", "noun", "A group of items", "A batch of cookies."),
    ("battlefield", "noun", "A place where a battle is fought", "The historic battlefield."),
    ("beacon", "noun", "A light serving as a signal", "A beacon of hope."),
    ("beam", "noun", "A ray of light", "A beam of sunlight."),
    ("bear", "verb", "To carry or support", "Bear the weight."),
    ("bearing", "noun", "A person's way of standing", "A confident bearing."),
    ("beast", "noun", "An animal", "A wild beast."),
    ("beat", "verb", "To strike repeatedly", "Beat the drum."),
    ("beckon", "verb", "To signal with a gesture", "Beckon someone over."),
    ("befall", "verb", "To happen to someone", "Tragedy befell them."),
    ("beforehand", "adverb", "In advance", "Prepare beforehand."),
    ("beg", "verb", "To ask earnestly", "Beg for forgiveness."),
    ("behalf", "noun", "In the interest of someone", "On behalf of others."),
    ("behave", "verb", "To act in a certain way", "Behave properly."),
    ("behavior", "noun", "The way one acts", "Good behavior."),
    ("behold", "verb", "To see or observe", "Behold the beauty."),
    ("belated", "adjective", "Coming later than expected", "Belated birthday wishes."),
    ("belief", "noun", "An acceptance that something is true", "Strong belief."),
    ("believable", "adjective", "Able to be believed", "A believable story."),
    ("believe", "verb", "To accept as true", "I believe you."),
    ("believer", "noun", "A person who believes", "A true believer."),
    ("belittle", "verb", "To make seem unimportant", "Don't belittle others."),
    ("belligerent", "adjective", "Hostile and aggressive", "A belligerent attitude."),
    ("beloved", "adjective", "Dearly loved", "My beloved family."),
    ("benchmark", "noun", "A standard for comparison", "Set a benchmark."),
    ("bend", "verb", "To shape into a curve", "Bend the wire."),
    ("beneath", "preposition", "Under", "Beneath the surface."),
    ("benefactor", "noun", "A person who gives help", "A generous benefactor."),
    ("beneficial", "adjective", "Resulting in good", "Beneficial effects."),
    ("beneficiary", "noun", "A person who receives benefit", "The beneficiary of the will."),
    ("benefit", "noun", "An advantage", "Health benefits."),
    ("benevolence", "noun", "The quality of being well-meaning", "An act of benevolence."),
    ("benevolent", "adjective", "Well meaning and kindly", "A benevolent ruler."),
    ("benign", "adjective", "Gentle and kind", "A benign tumor."),
    ("bent", "adjective", "Having a strong inclination", "Bent on revenge."),
    ("bequeath", "verb", "To leave to someone in a will", "Bequeath an estate."),
    ("bequest", "noun", "A gift left in a will", "A generous bequest."),
    ("berate", "verb", "To scold or criticize angrily", "Berate someone harshly."),
    ("bereave", "verb", "To deprive of a loved one", "Bereaved by the loss."),
    ("beseech", "verb", "To implore", "Beseech for mercy."),
    ("beset", "verb", "To trouble persistently", "Beset by problems."),
    ("besides", "preposition", "In addition to", "Besides work, I exercise."),
    ("besiege", "verb", "To surround with armed forces", "Besiege the castle."),
    ("bestow", "verb", "To confer an honor", "Bestow an award."),
    ("betray", "verb", "To be disloyal to", "Betray trust."),
    ("betrayal", "noun", "The act of betraying", "A shocking betrayal."),
    ("beyond", "preposition", "At the far side of", "Beyond expectation."),
    ("bias", "noun", "Prejudice in favor of something", "Avoid bias."),
    ("biased", "adjective", "Unfairly prejudiced", "A biased opinion."),
    ("bibliography", "noun", "A list of books referred to", "Include a bibliography."),
    ("bid", "verb", "To offer a price", "Bid at the auction."),
    ("bilateral", "adjective", "Having two sides", "Bilateral agreement."),
    ("bind", "verb", "To tie or fasten", "Bind the books."),
    ("binding", "adjective", "Imposing an obligation", "A binding contract."),
    ("biography", "noun", "An account of someone's life", "Write a biography."),
    ("bizarre", "adjective", "Very strange", "A bizarre incident."),
    ("blade", "noun", "The flat cutting edge of a knife", "A sharp blade."),
    ("blame", "verb", "To assign responsibility for a fault", "Don't blame others."),
    ("bland", "adjective", "Lacking flavor or excitement", "Bland food."),
    ("blank", "adjective", "Not written on", "A blank page."),
    ("blanket", "noun", "A large piece of woolen cloth", "Cover with a blanket."),
    ("blasphemy", "noun", "Speaking irreverently about sacred things", "Accused of blasphemy."),
    ("blast", "noun", "An explosion", "A powerful blast."),
    ("blatant", "adjective", "Completely obvious", "A blatant lie."),
    ("blaze", "noun", "A very large fire", "The blaze spread quickly."),
    ("bleak", "adjective", "Lacking hope", "A bleak future."),
    ("bleed", "verb", "To lose blood", "The wound is bleeding."),
    ("blend", "verb", "To mix together", "Blend the ingredients."),
    ("bless", "verb", "To make holy", "Bless this house."),
    ("blessing", "noun", "God's favor", "A blessing in disguise."),
    ("blight", "noun", "A plant disease", "Urban blight."),
    ("blind", "adjective", "Unable to see", "Blind trust."),
    ("bliss", "noun", "Perfect happiness", "Marital bliss."),
    ("blissful", "adjective", "Extremely happy", "A blissful moment."),
    ("blitz", "noun", "An intensive campaign", "A marketing blitz."),
    ("bloc", "noun", "A group of countries or parties", "A voting bloc."),
    ("block", "verb", "To prevent movement through", "Block the road."),
    ("blockade", "noun", "A sealing off of a place", "A naval blockade."),
    ("bloom", "verb", "To produce flowers", "Flowers bloom in spring."),
    ("blossom", "noun", "A flower on a tree", "Cherry blossoms."),
    ("blot", "noun", "A spot or stain", "A blot on reputation."),
    ("blow", "verb", "To move by wind", "The wind blows."),
    ("blueprint", "noun", "A technical drawing", "A blueprint for success."),
    ("blunder", "noun", "A stupid mistake", "A costly blunder."),
    ("blunt", "adjective", "Not sharp", "A blunt knife."),
    ("blur", "verb", "To make unclear", "Blur the lines."),
    ("blush", "verb", "To develop a pink color in the face", "She blushed with embarrassment."),
    ("boast", "verb", "To talk with excessive pride", "Don't boast about it."),
    ("bogus", "adjective", "Not genuine", "A bogus claim."),
    ("boil", "verb", "To reach the boiling point", "Boil the water."),
    ("bold", "adjective", "Showing courage", "A bold move."),
    ("bolster", "verb", "To support or strengthen", "Bolster confidence."),
    ("bolt", "noun", "A metal pin used for fastening", "Tighten the bolt."),
    ("bomb", "noun", "An explosive device", "Defuse the bomb."),
    ("bombard", "verb", "To attack continuously", "Bombard with questions."),
    ("bond", "noun", "A force of attraction", "A strong bond."),
    ("bondage", "noun", "The state of being a slave", "Freedom from bondage."),
    ("bonus", "noun", "An extra payment", "Receive a bonus."),
    ("boom", "noun", "A period of rapid growth", "An economic boom."),
    ("boost", "verb", "To help or encourage", "Boost morale."),
    ("booth", "noun", "A small enclosure", "A phone booth."),
    ("border", "noun", "A line separating areas", "Cross the border."),
    ("bore", "verb", "To make someone feel weary", "The lecture bored me."),
    ("boredom", "noun", "The state of being bored", "Die of boredom."),
    ("boring", "adjective", "Not interesting", "A boring movie."),
    ("borrow", "verb", "To take with intent to return", "Borrow a book."),
    ("boss", "noun", "A person in charge", "Ask your boss."),
    ("botanical", "adjective", "Relating to plants", "A botanical garden."),
]
