# 80-100 Level Words Part 1 (1-250) - Advanced Academic Vocabulary
WORDS_80_100_PART1 = [
    ("aberration", "noun", "A departure from what is normal", "This result is an aberration."),
    ("abhor", "verb", "To regard with disgust", "I abhor cruelty to animals."),
    ("abject", "adjective", "Extremely bad or miserable", "Living in abject poverty."),
    ("ablaze", "adjective", "On fire", "The building was ablaze."),
    ("abolish", "verb", "To formally put an end to", "Abolish outdated laws."),
    ("abomination", "noun", "Something that causes disgust", "The pollution was an abomination."),
    ("abrasive", "adjective", "Showing little concern for others", "His abrasive manner offends people."),
    ("abreast", "adverb", "Side by side and facing the same way", "Walk two abreast."),
    ("abridge", "verb", "To shorten without losing meaning", "Abridge the document."),
    ("abrupt", "adjective", "Sudden and unexpected", "An abrupt change in weather."),
    ("absolution", "noun", "Formal release from guilt", "Seek absolution for sins."),
    ("absolve", "verb", "To declare free from blame", "Absolve someone of responsibility."),
    ("abstain", "verb", "To restrain oneself from doing something", "Abstain from voting."),
    ("abstinence", "noun", "The practice of restraining", "Total abstinence from alcohol."),
    ("abstract", "adjective", "Existing in thought only", "Abstract concepts are difficult."),
    ("abstruse", "adjective", "Difficult to understand", "The theory is abstruse."),
    ("absurd", "adjective", "Wildly unreasonable", "An absurd suggestion."),
    ("abundance", "noun", "A very large quantity", "An abundance of resources."),
    ("abundant", "adjective", "Existing in large quantities", "Abundant evidence supports it."),
    ("abuse", "noun", "Cruel treatment", "Stop the abuse immediately."),
    ("abysmal", "adjective", "Extremely bad", "Abysmal performance."),
    ("accede", "verb", "To agree to a demand", "Accede to the request."),
    ("accentuate", "verb", "To make more noticeable", "Accentuate the positive."),
    ("accessible", "adjective", "Able to be reached", "The building is wheelchair accessible."),
    ("acclaim", "noun", "Enthusiastic approval", "The book received critical acclaim."),
    ("acclimate", "verb", "To become accustomed to a new climate", "Acclimate to the altitude."),
    ("accommodate", "verb", "To provide lodging", "The hotel can accommodate 200 guests."),
    ("accomplice", "noun", "A partner in crime", "He was an accomplice in the robbery."),
    ("accord", "noun", "An official agreement", "A peace accord was signed."),
    ("accost", "verb", "To approach aggressively", "A stranger accosted me."),
    ("accountable", "adjective", "Required to explain actions", "Hold them accountable."),
    ("accreditation", "noun", "Official recognition", "University accreditation."),
    ("accredit", "verb", "To give official authorization", "Accredit the institution."),
    ("accrue", "verb", "To accumulate over time", "Interest will accrue monthly."),
    ("accumulate", "verb", "To gather together", "Accumulate wealth slowly."),
    ("accuracy", "noun", "The quality of being correct", "Check for accuracy."),
    ("accusation", "noun", "A charge of wrongdoing", "Face serious accusations."),
    ("acerbic", "adjective", "Sharp and critical", "An acerbic comment."),
    ("acknowledge", "verb", "To accept or recognize", "Acknowledge your mistakes."),
    ("acme", "noun", "The highest point", "The acme of his career."),
    ("acquaint", "verb", "To make familiar with", "Acquaint yourself with the rules."),
    ("acquiesce", "verb", "To accept reluctantly", "She acquiesced to the demands."),
    ("acquisition", "noun", "Something acquired", "A valuable acquisition."),
    ("acquit", "verb", "To declare not guilty", "The jury acquitted him."),
    ("acrid", "adjective", "Having a sharp smell or taste", "Acrid smoke filled the air."),
    ("acrimonious", "adjective", "Angry and bitter", "An acrimonious debate."),
    ("acuity", "noun", "Sharpness of thought", "Mental acuity declines with age."),
    ("acumen", "noun", "The ability to make good judgments", "Business acumen."),
    ("acute", "adjective", "Very serious or severe", "An acute shortage of supplies."),
    ("adamant", "adjective", "Refusing to change one's mind", "She was adamant about leaving."),
    ("adapt", "verb", "To adjust to new conditions", "Adapt to the environment."),
    ("adaptation", "noun", "The process of adapting", "Adaptation to climate change."),
    ("addendum", "noun", "An addition to a document", "Include an addendum."),
    ("addictive", "adjective", "Causing addiction", "Addictive substances."),
    ("adequate", "adjective", "Sufficient for a specific need", "Adequate preparation."),
    ("adhere", "verb", "To stick firmly", "Adhere to the rules."),
    ("adherent", "noun", "A supporter of a cause", "A loyal adherent."),
    ("adhesive", "noun", "A substance used for sticking", "Use strong adhesive."),
    ("adjacent", "adjective", "Next to or adjoining", "Adjacent buildings."),
    ("adjourn", "verb", "To suspend a meeting", "Adjourn the session."),
    ("adjudicate", "verb", "To make a formal judgment", "Adjudicate the dispute."),
    ("administer", "verb", "To manage or control", "Administer the program."),
    ("administration", "noun", "The management of affairs", "Hospital administration."),
    ("admirable", "adjective", "Worthy of respect", "An admirable effort."),
    ("admiration", "noun", "Respect and approval", "Deserve admiration."),
    ("admire", "verb", "To regard with respect", "I admire your dedication."),
    ("admission", "noun", "Entry into a place", "Admission is free."),
    ("admit", "verb", "To confess to be true", "Admit your mistake."),
    ("admonish", "verb", "To warn or reprimand firmly", "Admonish the student."),
    ("adolescent", "noun", "A young person developing into an adult", "Adolescent behavior."),
    ("adopt", "verb", "To choose to take up", "Adopt a new strategy."),
    ("adoration", "noun", "Deep love and respect", "Adoration for nature."),
    ("adorn", "verb", "To make more beautiful", "Adorn the room with flowers."),
    ("adrift", "adverb", "Floating without control", "The boat was set adrift."),
    ("adroit", "adjective", "Clever or skillful", "An adroit negotiator."),
    ("adulation", "noun", "Excessive admiration", "Public adulation."),
    ("adulterate", "verb", "To make impure by adding inferior substances", "Adulterate food products."),
    ("advent", "noun", "The arrival of an important event", "The advent of technology."),
    ("adversary", "noun", "An opponent", "A formidable adversary."),
    ("adverse", "adjective", "Preventing success", "Adverse weather conditions."),
    ("adversity", "noun", "Difficulties or misfortune", "Overcome adversity."),
    ("advocate", "verb", "To publicly support", "Advocate for change."),
    ("aerial", "adjective", "Existing in the air", "Aerial photography."),
    ("aesthetic", "adjective", "Concerned with beauty", "Aesthetic appeal."),
    ("affable", "adjective", "Friendly and good-natured", "An affable personality."),
    ("affectation", "noun", "Pretentious behavior", "Speak without affectation."),
    ("affiliate", "verb", "To officially attach to an organization", "Affiliate with the group."),
    ("affiliation", "noun", "A connection to an organization", "Political affiliation."),
    ("affinity", "noun", "A natural liking", "An affinity for music."),
    ("affirm", "verb", "To state positively", "Affirm your commitment."),
    ("affirmation", "noun", "A positive statement", "Words of affirmation."),
    ("affirmative", "adjective", "Expressing agreement", "An affirmative answer."),
    ("afflict", "verb", "To cause pain or suffering", "Diseases afflict many people."),
    ("affluent", "adjective", "Having a lot of money", "An affluent neighborhood."),
    ("affordable", "adjective", "Inexpensive enough to buy", "Affordable housing."),
    ("affront", "noun", "An action causing offense", "An affront to dignity."),
    ("aftermath", "noun", "The consequences of an event", "The aftermath of the storm."),
    ("agenda", "noun", "A list of items to be discussed", "Set the meeting agenda."),
    ("aggravate", "verb", "To make worse", "Don't aggravate the situation."),
    ("aggregate", "noun", "A whole formed by combining parts", "An aggregate score."),
    ("aggression", "noun", "Hostile behavior", "Control your aggression."),
    ("aggressive", "adjective", "Ready to attack", "An aggressive approach."),
    ("aggrieved", "adjective", "Feeling resentment", "The aggrieved party."),
    ("aghast", "adjective", "Filled with horror", "She was aghast at the news."),
    ("agile", "adjective", "Able to move quickly", "An agile mind."),
    ("agility", "noun", "The ability to move quickly", "Mental agility."),
    ("agitate", "verb", "To make someone troubled", "Agitate for reform."),
    ("agnostic", "noun", "A person uncertain about God's existence", "Identify as agnostic."),
    ("agrarian", "adjective", "Relating to cultivated land", "An agrarian society."),
    ("ailment", "noun", "An illness", "A common ailment."),
    ("aimless", "adjective", "Without purpose", "An aimless wanderer."),
    ("akin", "adjective", "Of similar character", "Feelings akin to love."),
    ("alacrity", "noun", "Brisk eagerness", "Accept with alacrity."),
    ("albeit", "conjunction", "Although", "Albeit slowly, progress was made."),
    ("algorithm", "noun", "A process for solving problems", "A search algorithm."),
    ("alienate", "verb", "To isolate or estrange", "Don't alienate your friends."),
    ("align", "verb", "To place in a straight line", "Align the text properly."),
    ("alignment", "noun", "Arrangement in a line", "Check wheel alignment."),
    ("allay", "verb", "To diminish fear", "Allay their concerns."),
    ("allegation", "noun", "A claim of wrongdoing", "Serious allegations emerged."),
    ("allege", "verb", "To claim without proof", "Allege misconduct."),
    ("allegiance", "noun", "Loyalty to a person or group", "Pledge allegiance."),
    ("allegorical", "adjective", "Containing a hidden meaning", "An allegorical tale."),
    ("allegory", "noun", "A story with hidden meaning", "A political allegory."),
    ("alleviate", "verb", "To make less severe", "Alleviate suffering."),
    ("alliance", "noun", "A union or association", "Form an alliance."),
    ("allocate", "verb", "To distribute for a purpose", "Allocate resources."),
    ("allocation", "noun", "The action of allocating", "Budget allocation."),
    ("allot", "verb", "To give a share of", "Allot time for each task."),
    ("allotment", "noun", "An amount allocated", "Receive your allotment."),
    ("allowance", "noun", "A sum of money given regularly", "A monthly allowance."),
    ("allude", "verb", "To suggest indirectly", "Allude to past events."),
    ("allure", "noun", "The quality of attraction", "The allure of fame."),
    ("allusion", "noun", "An indirect reference", "A literary allusion."),
    ("ally", "noun", "A person or organization united with another", "A trusted ally."),
    ("aloof", "adjective", "Not friendly or forthcoming", "Remain aloof from gossip."),
    ("alter", "verb", "To change", "Alter the design."),
    ("alteration", "noun", "The action of altering", "Minor alterations needed."),
    ("altercation", "noun", "A noisy argument", "A verbal altercation."),
    ("alternate", "verb", "To occur in turns", "Alternate between tasks."),
    ("alternative", "noun", "One of two or more possibilities", "Consider alternatives."),
    ("altitude", "noun", "Height above sea level", "High altitude."),
    ("altruism", "noun", "Unselfish concern for others", "An act of altruism."),
    ("altruistic", "adjective", "Showing unselfish concern", "Altruistic behavior."),
    ("amalgamate", "verb", "To combine into one", "Amalgamate the departments."),
    ("amass", "verb", "To gather together in quantity", "Amass a fortune."),
    ("ambiance", "noun", "The atmosphere of a place", "A pleasant ambiance."),
    ("ambiguity", "noun", "Uncertainty of meaning", "Avoid ambiguity."),
    ("ambiguous", "adjective", "Open to interpretation", "An ambiguous statement."),
    ("ambition", "noun", "A strong desire to achieve", "Have great ambition."),
    ("ambitious", "adjective", "Having or showing ambition", "An ambitious project."),
    ("ambivalence", "noun", "Mixed feelings", "Feel ambivalence about it."),
    ("ambivalent", "adjective", "Having mixed feelings", "Ambivalent about the decision."),
    ("ameliorate", "verb", "To make something better", "Ameliorate conditions."),
    ("amenable", "adjective", "Open to suggestion", "Amenable to change."),
    ("amend", "verb", "To make minor changes", "Amend the constitution."),
    ("amendment", "noun", "A minor change", "A constitutional amendment."),
    ("amenity", "noun", "A desirable feature", "Modern amenities."),
    ("amiable", "adjective", "Friendly and pleasant", "An amiable host."),
    ("amicable", "adjective", "Characterized by friendliness", "An amicable agreement."),
    ("amid", "preposition", "In the middle of", "Amid the chaos."),
    ("amnesty", "noun", "An official pardon", "Grant amnesty."),
    ("amorphous", "adjective", "Without a defined shape", "An amorphous blob."),
    ("ample", "adjective", "Enough or more than enough", "Ample space available."),
    ("amplify", "verb", "To increase in strength", "Amplify the sound."),
    ("amputate", "verb", "To cut off a limb", "Amputate the leg."),
    ("analogy", "noun", "A comparison of two things", "Draw an analogy."),
    ("analysis", "noun", "Detailed examination", "Data analysis."),
    ("analyst", "noun", "A person who analyzes", "A financial analyst."),
    ("analytical", "adjective", "Using analysis", "Analytical skills."),
    ("analyze", "verb", "To examine in detail", "Analyze the data."),
    ("anarchist", "noun", "A person who believes in no government", "An anarchist movement."),
    ("anarchy", "noun", "A state of disorder", "Political anarchy."),
    ("anatomy", "noun", "The study of body structure", "Human anatomy."),
    ("ancestor", "noun", "A person from whom one is descended", "Honor your ancestors."),
    ("ancestry", "noun", "One's family origin", "Trace your ancestry."),
    ("anchor", "noun", "A heavy object to moor a vessel", "Drop the anchor."),
    ("anecdote", "noun", "A short amusing story", "Share an anecdote."),
    ("anew", "adverb", "In a new or different way", "Start anew."),
    ("anguish", "noun", "Severe mental pain", "Cry out in anguish."),
    ("animosity", "noun", "Strong hostility", "Deep animosity between rivals."),
    ("annex", "verb", "To add as an extra part", "Annex the territory."),
    ("annihilate", "verb", "To destroy completely", "Annihilate the enemy."),
    ("anniversary", "noun", "The yearly recurrence of an event", "Wedding anniversary."),
    ("annotate", "verb", "To add notes to a text", "Annotate the manuscript."),
    ("annotation", "noun", "A note added to a text", "Include annotations."),
    ("announce", "verb", "To make publicly known", "Announce the winner."),
    ("announcement", "noun", "A public statement", "Make an announcement."),
    ("annoy", "verb", "To irritate", "Noise annoys me."),
    ("annoyance", "noun", "The feeling of being annoyed", "Express annoyance."),
    ("annual", "adjective", "Occurring once a year", "Annual meeting."),
    ("annul", "verb", "To declare invalid", "Annul the marriage."),
    ("anomaly", "noun", "Something that deviates from the norm", "A statistical anomaly."),
    ("anonymous", "adjective", "Not identified by name", "An anonymous donor."),
    ("antagonism", "noun", "Active hostility", "Antagonism between groups."),
    ("antagonist", "noun", "A person who opposes", "The story's antagonist."),
    ("antagonize", "verb", "To cause to become hostile", "Don't antagonize him."),
    ("anthology", "noun", "A collection of literary works", "A poetry anthology."),
    ("anthropology", "noun", "The study of human societies", "Study anthropology."),
    ("anticipate", "verb", "To expect", "Anticipate problems."),
    ("anticipation", "noun", "The action of anticipating", "Full of anticipation."),
    ("antidote", "noun", "A medicine to counteract poison", "An antidote for stress."),
    ("antiquated", "adjective", "Old-fashioned", "Antiquated methods."),
    ("antique", "adjective", "Belonging to ancient times", "An antique table."),
    ("antiquity", "noun", "The ancient past", "Relics of antiquity."),
    ("antisocial", "adjective", "Contrary to social norms", "Antisocial behavior."),
    ("antithesis", "noun", "The exact opposite", "The antithesis of good."),
    ("anxiety", "noun", "A feeling of worry", "Reduce anxiety."),
    ("anxious", "adjective", "Feeling worried", "Anxious about the exam."),
    ("apathetic", "adjective", "Showing no interest", "An apathetic response."),
    ("apathy", "noun", "Lack of interest", "Political apathy."),
    ("apex", "noun", "The highest point", "The apex of success."),
    ("aplomb", "noun", "Self-confidence", "Handle with aplomb."),
    ("apocalyptic", "adjective", "Describing great destruction", "An apocalyptic scenario."),
    ("apocryphal", "adjective", "Of doubtful authenticity", "An apocryphal story."),
    ("appall", "verb", "To greatly dismay", "The violence appalled me."),
    ("appalling", "adjective", "Causing shock or dismay", "Appalling conditions."),
    ("apparatus", "noun", "Equipment for a task", "Scientific apparatus."),
    ("apparent", "adjective", "Clearly visible", "The reason is apparent."),
    ("apparently", "adverb", "As far as one knows", "Apparently true."),
    ("appeal", "noun", "A serious request", "Make an appeal."),
    ("appealing", "adjective", "Attractive", "An appealing idea."),
    ("appear", "verb", "To come into sight", "Stars appear at night."),
    ("appearance", "noun", "The way something looks", "Physical appearance."),
    ("appease", "verb", "To pacify by giving in", "Appease the angry crowd."),
    ("append", "verb", "To add to the end", "Append a note."),
    ("appendix", "noun", "A section at the end of a book", "Check the appendix."),
    ("appetite", "noun", "A natural desire for food", "A healthy appetite."),
    ("applaud", "verb", "To show approval by clapping", "Applaud the performers."),
    ("applause", "noun", "Approval shown by clapping", "Receive applause."),
    ("appliance", "noun", "A device for household tasks", "Kitchen appliances."),
    ("applicable", "adjective", "Relevant or appropriate", "Applicable laws."),
    ("applicant", "noun", "A person who applies", "A job applicant."),
    ("application", "noun", "A formal request", "Submit an application."),
    ("apply", "verb", "To make a formal request", "Apply for the job."),
    ("appoint", "verb", "To assign a job to someone", "Appoint a new manager."),
    ("appointment", "noun", "An arrangement to meet", "Schedule an appointment."),
    ("appraisal", "noun", "An assessment of value", "Property appraisal."),
    ("appraise", "verb", "To assess the value of", "Appraise the jewelry."),
    ("appreciate", "verb", "To recognize the value of", "Appreciate your help."),
    ("appreciation", "noun", "Recognition of value", "Show appreciation."),
    ("apprehend", "verb", "To arrest", "Apprehend the suspect."),
    ("apprehension", "noun", "Anxiety about the future", "Fill with apprehension."),
    ("apprehensive", "adjective", "Anxious or fearful", "Apprehensive about changes."),
    ("apprentice", "noun", "A person learning a trade", "An apprentice carpenter."),
    ("approach", "verb", "To come near", "Approach carefully."),
    ("appropriate", "adjective", "Suitable for the circumstances", "Appropriate behavior."),
    ("appropriately", "adverb", "In a suitable way", "Dress appropriately."),
    ("approval", "noun", "Official permission", "Gain approval."),
    ("approve", "verb", "To officially agree to", "Approve the budget."),
    ("approximate", "adjective", "Close to the actual", "Approximate value."),
    ("approximately", "adverb", "Close to", "Approximately 100 people."),
    ("apt", "adjective", "Appropriate or suitable", "An apt description."),
    ("aptitude", "noun", "A natural ability", "Aptitude for languages."),
    ("arbitrary", "adjective", "Based on random choice", "An arbitrary decision."),
    ("arbitrate", "verb", "To judge in a dispute", "Arbitrate the conflict."),
    ("arbitration", "noun", "The settlement of a dispute", "Go to arbitration."),
    ("arc", "noun", "A curved shape", "Draw an arc."),
    ("archaic", "adjective", "Very old or old-fashioned", "Archaic language."),
    ("archetypal", "adjective", "Very typical of a kind", "An archetypal hero."),
    ("archetype", "noun", "A perfect example", "The archetype of success."),
    ("architect", "noun", "A designer of buildings", "A famous architect."),
    ("architecture", "noun", "The design of buildings", "Modern architecture."),
    ("archive", "noun", "A collection of historical documents", "Access the archive."),
]
