# 80-100 Level Words Part 4 (751-1000)
WORDS_80_100_PART4 = [
    ("chip", "noun", "A small piece broken off", "A computer chip."),
    ("choke", "verb", "To have difficulty breathing", "Choke on food."),
    ("cholesterol", "noun", "A substance in body cells", "Lower cholesterol levels."),
    ("choose", "verb", "To select from alternatives", "Choose wisely."),
    ("chop", "verb", "To cut with a sharp blow", "Chop vegetables."),
    ("chord", "noun", "A group of musical notes", "Play a chord."),
    ("chore", "noun", "A routine task", "Household chores."),
    ("chorus", "noun", "A part of a song repeated", "Sing the chorus."),
    ("chronic", "adjective", "Persisting for a long time", "Chronic pain."),
    ("chronicle", "noun", "A factual written account", "A chronicle of events."),
    ("chronological", "adjective", "In order of time", "Chronological order."),
    ("chunk", "noun", "A thick piece", "A chunk of cheese."),
    ("circle", "noun", "A round shape", "Draw a circle."),
    ("circuit", "noun", "A closed loop for electricity", "An electrical circuit."),
    ("circular", "adjective", "Having a round shape", "A circular motion."),
    ("circulate", "verb", "To move continuously", "Circulate the memo."),
    ("circulation", "noun", "The movement of blood", "Blood circulation."),
    ("circumstance", "noun", "A condition connected with an event", "Under the circumstances."),
    ("cite", "verb", "To quote as evidence", "Cite your sources."),
    ("citizen", "noun", "A legally recognized member of a state", "A citizen's rights."),
    ("citizenship", "noun", "The status of being a citizen", "Apply for citizenship."),
    ("city", "noun", "A large town", "A busy city."),
    ("civic", "adjective", "Relating to a city", "Civic duty."),
    ("civil", "adjective", "Relating to citizens", "Civil rights."),
    ("civilian", "noun", "A person not in the military", "Protect civilians."),
    ("civilization", "noun", "An advanced state of society", "Ancient civilization."),
    ("claim", "verb", "To state as a fact", "Claim innocence."),
    ("clamp", "noun", "A device to hold things tight", "Use a clamp."),
    ("clan", "noun", "A close-knit group", "A Scottish clan."),
    ("clandestine", "adjective", "Kept secret", "A clandestine meeting."),
    ("clap", "verb", "To strike hands together", "Clap your hands."),
    ("clarification", "noun", "The action of making clear", "Seek clarification."),
    ("clarify", "verb", "To make clear", "Clarify the meaning."),
    ("clarity", "noun", "The quality of being clear", "Clarity of thought."),
    ("clash", "verb", "To conflict violently", "Ideas clash."),
    ("clasp", "verb", "To hold tightly", "Clasp your hands."),
    ("class", "noun", "A set of similar things", "A biology class."),
    ("classic", "adjective", "Judged over time to be of the highest quality", "A classic novel."),
    ("classical", "adjective", "Relating to ancient Greek or Roman culture", "Classical music."),
    ("classification", "noun", "The action of classifying", "Scientific classification."),
    ("classify", "verb", "To arrange in categories", "Classify the data."),
    ("clause", "noun", "A part of a sentence", "A contract clause."),
    ("clay", "noun", "A type of earth used for pottery", "Mold the clay."),
    ("clean", "adjective", "Free from dirt", "Clean water."),
    ("clear", "adjective", "Easy to perceive", "A clear sky."),
    ("clearance", "noun", "Official permission", "Security clearance."),
    ("clearly", "adverb", "In a clear way", "Speak clearly."),
    ("clergy", "noun", "Religious leaders collectively", "The local clergy."),
    ("clerical", "adjective", "Relating to office work", "Clerical duties."),
    ("clerk", "noun", "An office worker", "A bank clerk."),
    ("clever", "adjective", "Quick to understand", "A clever solution."),
    ("cliche", "noun", "An overused expression", "Avoid cliches."),
    ("click", "verb", "To make a short sharp sound", "Click the button."),
    ("client", "noun", "A person using professional services", "A loyal client."),
    ("cliff", "noun", "A steep rock face", "Stand on the cliff."),
    ("climate", "noun", "Weather conditions in an area", "Climate change."),
    ("climax", "noun", "The most intense point", "The story's climax."),
    ("climb", "verb", "To go upward", "Climb the mountain."),
    ("cling", "verb", "To hold on tightly", "Cling to hope."),
    ("clinic", "noun", "A place for medical treatment", "Visit the clinic."),
    ("clinical", "adjective", "Relating to medical treatment", "Clinical trials."),
    ("clip", "noun", "A device for holding things", "A paper clip."),
    ("cloak", "noun", "A sleeveless outer garment", "A cloak of secrecy."),
    ("clock", "noun", "A device showing time", "Watch the clock."),
    ("clone", "noun", "An identical copy", "A genetic clone."),
    ("close", "adjective", "A short distance away", "Stay close."),
    ("closely", "adverb", "In a close manner", "Watch closely."),
    ("closure", "noun", "The act of closing", "Seek closure."),
    ("cloth", "noun", "Woven material", "A piece of cloth."),
    ("clothe", "verb", "To provide with clothes", "Clothe the homeless."),
    ("clothing", "noun", "Clothes collectively", "Winter clothing."),
    ("cloud", "noun", "A mass of water vapor", "Dark clouds."),
    ("cloudy", "adjective", "Full of clouds", "A cloudy day."),
    ("club", "noun", "An organization of people", "Join a club."),
    ("clue", "noun", "A piece of evidence", "Find a clue."),
    ("cluster", "noun", "A group of similar things", "A cluster of stars."),
    ("clutch", "verb", "To grasp tightly", "Clutch the rail."),
    ("clutter", "noun", "Things lying around untidily", "Clear the clutter."),
    ("coach", "noun", "A trainer of athletes", "The football coach."),
    ("coal", "noun", "A black mineral used as fuel", "Burn coal."),
    ("coalition", "noun", "An alliance of groups", "A political coalition."),
    ("coarse", "adjective", "Rough in texture", "Coarse fabric."),
    ("coast", "noun", "The edge of land near the sea", "The west coast."),
    ("coastal", "adjective", "Of or near a coast", "Coastal erosion."),
    ("coat", "noun", "An outer garment", "Wear a coat."),
    ("code", "noun", "A system of words or symbols", "A dress code."),
    ("coerce", "verb", "To persuade by force", "Coerce into confessing."),
    ("coercion", "noun", "The use of force", "Political coercion."),
    ("cognitive", "adjective", "Relating to cognition", "Cognitive abilities."),
    ("coherent", "adjective", "Logical and consistent", "A coherent argument."),
    ("cohesion", "noun", "The action of forming a united whole", "Team cohesion."),
    ("cohesive", "adjective", "Forming a united whole", "A cohesive group."),
    ("cohort", "noun", "A group of people", "A cohort of students."),
    ("coin", "noun", "A flat piece of metal used as money", "Flip a coin."),
    ("coincide", "verb", "To occur at the same time", "Events coincide."),
    ("coincidence", "noun", "A remarkable concurrence", "What a coincidence!"),
    ("cold", "adjective", "Of low temperature", "A cold day."),
    ("collaborate", "verb", "To work jointly", "Collaborate on the project."),
    ("collaboration", "noun", "The act of collaborating", "International collaboration."),
    ("collaborative", "adjective", "Involving collaboration", "A collaborative effort."),
    ("collapse", "verb", "To fall down suddenly", "The building collapsed."),
    ("collar", "noun", "The part around the neck", "Grab by the collar."),
    ("colleague", "noun", "A person one works with", "A trusted colleague."),
    ("collect", "verb", "To bring together", "Collect stamps."),
    ("collection", "noun", "A group of things collected", "An art collection."),
    ("collective", "adjective", "Done by people acting as a group", "Collective effort."),
    ("collectively", "adverb", "As a group", "Decide collectively."),
    ("collector", "noun", "A person who collects things", "An art collector."),
    ("college", "noun", "An institution of higher education", "Go to college."),
    ("collision", "noun", "A crash between objects", "A car collision."),
    ("colonial", "adjective", "Relating to a colony", "Colonial history."),
    ("colonize", "verb", "To establish a colony in", "Colonize new lands."),
    ("colony", "noun", "A territory under control", "A British colony."),
    ("color", "noun", "A property of objects", "Choose a color."),
    ("colorful", "adjective", "Having many colors", "A colorful painting."),
    ("colossal", "adjective", "Extremely large", "A colossal mistake."),
    ("column", "noun", "A pillar or vertical section", "A newspaper column."),
    ("combat", "noun", "Fighting between armed forces", "Close combat."),
    ("combination", "noun", "A joining of different things", "A winning combination."),
    ("combine", "verb", "To join together", "Combine the ingredients."),
    ("come", "verb", "To move toward", "Come here."),
    ("comeback", "noun", "A return to a previous state", "Make a comeback."),
    ("comedy", "noun", "Entertainment with humor", "A romantic comedy."),
    ("comfort", "noun", "A state of physical ease", "Find comfort."),
    ("comfortable", "adjective", "Providing comfort", "A comfortable chair."),
    ("comfortably", "adverb", "In a comfortable way", "Sit comfortably."),
    ("comic", "adjective", "Causing laughter", "A comic strip."),
    ("command", "noun", "An authoritative order", "Give a command."),
    ("commander", "noun", "A person in authority", "The military commander."),
    ("commemorate", "verb", "To recall and show respect", "Commemorate the event."),
    ("commence", "verb", "To begin", "Commence the ceremony."),
    ("commencement", "noun", "A beginning", "Graduation commencement."),
    ("commend", "verb", "To praise formally", "Commend for bravery."),
    ("commendable", "adjective", "Deserving praise", "A commendable effort."),
    ("comment", "noun", "A remark expressing an opinion", "Leave a comment."),
    ("commentary", "noun", "Spoken description of an event", "Sports commentary."),
    ("commentator", "noun", "A person who comments", "A news commentator."),
    ("commerce", "noun", "The activity of buying and selling", "Global commerce."),
    ("commercial", "adjective", "Relating to commerce", "Commercial success."),
    ("commission", "noun", "A fee paid for a service", "Earn a commission."),
    ("commissioner", "noun", "A person appointed to a role", "The police commissioner."),
    ("commit", "verb", "To carry out", "Commit a crime."),
    ("commitment", "noun", "Dedication to a cause", "Show commitment."),
    ("committed", "adjective", "Dedicated to a cause", "Committed to success."),
    ("committee", "noun", "A group appointed for a function", "The budget committee."),
    ("commodity", "noun", "A raw material", "A valuable commodity."),
    ("common", "adjective", "Occurring frequently", "A common problem."),
    ("commonly", "adverb", "Very often", "Commonly used."),
    ("commonplace", "adjective", "Not unusual", "A commonplace occurrence."),
    ("commonwealth", "noun", "An independent state", "The Commonwealth of Nations."),
    ("communal", "adjective", "Shared by members of a community", "Communal living."),
    ("communicate", "verb", "To share information", "Communicate effectively."),
    ("communication", "noun", "The exchange of information", "Clear communication."),
    ("communism", "noun", "A political theory", "The fall of communism."),
    ("communist", "noun", "A supporter of communism", "A former communist."),
    ("community", "noun", "A group living in one place", "The local community."),
    ("commute", "verb", "To travel regularly", "Commute to work."),
    ("commuter", "noun", "A person who commutes", "A daily commuter."),
    ("compact", "adjective", "Closely packed together", "A compact design."),
    ("companion", "noun", "A person one spends time with", "A travel companion."),
    ("companionship", "noun", "Friendly association", "Enjoy companionship."),
    ("company", "noun", "A commercial business", "Start a company."),
    ("comparable", "adjective", "Able to be compared", "Comparable results."),
    ("comparative", "adjective", "Measured by comparison", "A comparative study."),
    ("comparatively", "adverb", "To a moderate degree", "Comparatively easy."),
    ("compare", "verb", "To examine similarities", "Compare prices."),
    ("comparison", "noun", "The act of comparing", "A fair comparison."),
    ("compartment", "noun", "A separate section", "A storage compartment."),
    ("compass", "noun", "A device showing directions", "Use a compass."),
    ("compassion", "noun", "Sympathetic concern", "Show compassion."),
    ("compassionate", "adjective", "Feeling compassion", "A compassionate person."),
    ("compatible", "adjective", "Able to exist together", "Compatible devices."),
    ("compel", "verb", "To force or oblige", "Compel to act."),
    ("compelling", "adjective", "Evoking interest", "A compelling argument."),
    ("compensate", "verb", "To make up for", "Compensate for losses."),
    ("compensation", "noun", "Something given to make up for loss", "Fair compensation."),
    ("compete", "verb", "To try to gain something", "Compete for the prize."),
    ("competence", "noun", "The ability to do something", "Professional competence."),
    ("competent", "adjective", "Having the necessary ability", "A competent worker."),
    ("competition", "noun", "The act of competing", "Fierce competition."),
    ("competitive", "adjective", "Relating to competition", "A competitive market."),
    ("competitor", "noun", "A person who competes", "A major competitor."),
    ("compile", "verb", "To produce by assembling", "Compile the data."),
    ("complacent", "adjective", "Showing smug satisfaction", "Don't become complacent."),
    ("complain", "verb", "To express dissatisfaction", "Complain about the service."),
    ("complaint", "noun", "An expression of dissatisfaction", "File a complaint."),
    ("complement", "verb", "To add to so as to improve", "Colors that complement."),
    ("complementary", "adjective", "Combining well", "Complementary skills."),
    ("complete", "adjective", "Having all parts", "A complete set."),
    ("completely", "adverb", "Totally", "Completely satisfied."),
    ("completion", "noun", "The action of completing", "Upon completion."),
    ("complex", "adjective", "Consisting of many parts", "A complex problem."),
    ("complexity", "noun", "The state of being complex", "Reduce complexity."),
    ("compliance", "noun", "The act of complying", "Regulatory compliance."),
    ("compliant", "adjective", "Disposed to comply", "Fully compliant."),
    ("complicate", "verb", "To make complex", "Don't complicate things."),
    ("complicated", "adjective", "Involving many parts", "A complicated process."),
    ("complication", "noun", "A circumstance that complicates", "Avoid complications."),
    ("compliment", "noun", "An expression of praise", "Pay a compliment."),
    ("comply", "verb", "To act in accordance", "Comply with regulations."),
    ("component", "noun", "A part of a larger whole", "A key component."),
    ("compose", "verb", "To write or create", "Compose a song."),
    ("composed", "adjective", "Calm and in control", "Stay composed."),
    ("composer", "noun", "A person who writes music", "A famous composer."),
    ("composite", "adjective", "Made up of various parts", "A composite material."),
    ("composition", "noun", "The way something is made up", "Musical composition."),
    ("compound", "noun", "A thing composed of elements", "A chemical compound."),
    ("comprehend", "verb", "To understand", "Comprehend the concept."),
    ("comprehension", "noun", "The ability to understand", "Reading comprehension."),
    ("comprehensive", "adjective", "Complete and including all elements", "A comprehensive study."),
    ("compress", "verb", "To flatten by pressure", "Compress the file."),
    ("compression", "noun", "The action of compressing", "Data compression."),
    ("comprise", "verb", "To consist of", "The team comprises five members."),
    ("compromise", "noun", "An agreement reached by concession", "Reach a compromise."),
    ("compulsion", "noun", "An irresistible urge", "A strange compulsion."),
    ("compulsory", "adjective", "Required by law", "Compulsory education."),
    ("compute", "verb", "To calculate", "Compute the total."),
    ("computer", "noun", "An electronic device for processing data", "Use a computer."),
    ("comrade", "noun", "A companion in an activity", "A comrade in arms."),
    ("conceal", "verb", "To hide from view", "Conceal the evidence."),
    ("concede", "verb", "To admit or acknowledge", "Concede defeat."),
    ("conceivable", "adjective", "Capable of being imagined", "Every conceivable option."),
    ("conceive", "verb", "To form or devise", "Conceive an idea."),
    ("concentrate", "verb", "To focus attention", "Concentrate on the task."),
    ("concentration", "noun", "The action of concentrating", "High concentration."),
    ("concept", "noun", "An abstract idea", "A new concept."),
    ("conception", "noun", "The forming of an idea", "From conception to completion."),
    ("conceptual", "adjective", "Relating to concepts", "Conceptual framework."),
    ("concern", "noun", "Anxiety or worry", "A cause for concern."),
    ("concerned", "adjective", "Worried", "I am concerned."),
    ("concerning", "preposition", "About or regarding", "Questions concerning policy."),
    ("concert", "noun", "A musical performance", "Attend a concert."),
    ("concerted", "adjective", "Done together", "A concerted effort."),
    ("concession", "noun", "A thing conceded", "Make concessions."),
    ("concise", "adjective", "Giving information briefly", "A concise summary."),
    ("conclude", "verb", "To bring to an end", "Conclude the meeting."),
    ("conclusion", "noun", "The end or final part", "In conclusion."),
    ("conclusive", "adjective", "Serving to settle an issue", "Conclusive evidence."),
    ("concrete", "adjective", "Existing in a material form", "Concrete evidence."),
    ("concur", "verb", "To agree", "I concur with the decision."),
    ("concurrent", "adjective", "Existing at the same time", "Concurrent sessions."),
    ("condemn", "verb", "To express strong disapproval", "Condemn violence."),
    ("condemnation", "noun", "The expression of strong disapproval", "Public condemnation."),
    ("condensation", "noun", "Water formed by cooling vapor", "Condensation on windows."),
    ("condense", "verb", "To make denser or more concise", "Condense the report."),
    ("condition", "noun", "The state of something", "In good condition."),
    ("conditional", "adjective", "Subject to conditions", "Conditional approval."),
    ("conduct", "verb", "To organize and carry out", "Conduct research."),
    ("conductor", "noun", "A person who directs an orchestra", "The orchestra conductor."),
    ("confer", "verb", "To grant or bestow", "Confer an honor."),
    ("conference", "noun", "A formal meeting", "Attend a conference."),
    ("confess", "verb", "To admit to a crime", "Confess the truth."),
    ("confession", "noun", "An admission of guilt", "A full confession."),
    ("confidence", "noun", "A feeling of self-assurance", "Build confidence."),
    ("confident", "adjective", "Feeling certain", "Confident of success."),
    ("confidential", "adjective", "Intended to be kept secret", "Confidential information."),
    ("configuration", "noun", "An arrangement of elements", "System configuration."),
    ("configure", "verb", "To arrange in a particular way", "Configure the settings."),
    ("confine", "verb", "To keep within limits", "Confine to the house."),
    ("confined", "adjective", "Restricted in area", "A confined space."),
    ("confinement", "noun", "The state of being confined", "Solitary confinement."),
]
