# 100+ Level Words Part 2 (201-400)
WORDS_100_PLUS_PART2 = [
    ("bolster", "verb", "To support", "Bolster confidence."),
    ("bombastic", "adjective", "Using pompous language", "Bombastic speeches."),
    ("bona fide", "adjective", "Genuine", "A bona fide offer."),
    ("bonhomie", "noun", "Good-natured friendliness", "Full of bonhomie."),
    ("boon", "noun", "A benefit", "A boon to society."),
    ("boorish", "adjective", "Rough and ill-mannered", "Boorish behavior."),
    ("bourgeois", "adjective", "Middle class", "Bourgeois values."),
    ("brandish", "verb", "To wave threateningly", "Brandish a weapon."),
    ("brash", "adjective", "Self-assertive", "A brash comment."),
    ("bravado", "noun", "Bold manner to impress", "False bravado."),
    ("brazen", "adjective", "Bold and shameless", "A brazen lie."),
    ("breach", "noun", "A gap or violation", "A breach of contract."),
    ("brevity", "noun", "Shortness", "Brevity of speech."),
    ("brusque", "adjective", "Abrupt in manner", "A brusque reply."),
    ("bucolic", "adjective", "Relating to countryside", "Bucolic scenery."),
    ("bulwark", "noun", "A defensive wall", "A bulwark against tyranny."),
    ("bumptious", "adjective", "Self-assertive", "Bumptious attitude."),
    ("bungle", "verb", "To carry out clumsily", "Bungle the job."),
    ("buoyant", "adjective", "Cheerful and optimistic", "A buoyant mood."),
    ("burgeon", "verb", "To grow rapidly", "Burgeoning industry."),
    ("burnish", "verb", "To polish", "Burnish reputation."),
    ("buttress", "verb", "To support", "Buttress an argument."),
    ("byzantine", "adjective", "Excessively complicated", "Byzantine regulations."),
    ("cabal", "noun", "A secret political group", "A cabal of conspirators."),
    ("cache", "noun", "A hidden store", "A weapons cache."),
    ("cacophony", "noun", "A harsh mixture of sounds", "A cacophony of noise."),
    ("cadence", "noun", "A rhythmic sequence", "The cadence of speech."),
    ("cajole", "verb", "To persuade by flattery", "Cajole into agreeing."),
    ("calamity", "noun", "A disaster", "Natural calamity."),
    ("calculated", "adjective", "Carefully planned", "A calculated risk."),
    ("calibrate", "verb", "To adjust precisely", "Calibrate instruments."),
    ("callous", "adjective", "Insensitive", "A callous remark."),
    ("callow", "adjective", "Inexperienced", "A callow youth."),
    ("calumny", "noun", "False accusation", "Spread calumny."),
    ("camaraderie", "noun", "Trust among friends", "Team camaraderie."),
    ("candid", "adjective", "Truthful", "A candid assessment."),
    ("candor", "noun", "Frankness", "Speak with candor."),
    ("canonical", "adjective", "According to the rules", "Canonical texts."),
    ("cant", "noun", "Hypocritical talk", "Political cant."),
    ("cantankerous", "adjective", "Bad-tempered", "A cantankerous old man."),
    ("capacious", "adjective", "Roomy", "A capacious bag."),
    ("capitulate", "verb", "To surrender", "Forced to capitulate."),
    ("capricious", "adjective", "Changeable", "Capricious weather."),
    ("captious", "adjective", "Tending to find fault", "Captious criticism."),
    ("cardinal", "adjective", "Of prime importance", "A cardinal rule."),
    ("caricature", "noun", "An exaggerated portrayal", "A political caricature."),
    ("carnage", "noun", "Slaughter of people", "War carnage."),
    ("carping", "adjective", "Difficult to please", "Carping criticism."),
    ("castigate", "verb", "To reprimand severely", "Castigate for failure."),
    ("catalyst", "noun", "Something that causes change", "A catalyst for reform."),
    ("categorical", "adjective", "Unqualified", "A categorical denial."),
    ("caustic", "adjective", "Severely critical", "Caustic remarks."),
    ("cavalier", "adjective", "Dismissive", "A cavalier attitude."),
    ("caveat", "noun", "A warning", "A caveat emptor."),
    ("cede", "verb", "To give up", "Cede territory."),
    ("celerity", "noun", "Swiftness", "Act with celerity."),
    ("censure", "verb", "To express disapproval", "Censure the official."),
    ("cerebral", "adjective", "Intellectual", "Cerebral pursuits."),
    ("certitude", "noun", "Complete certainty", "Speak with certitude."),
    ("chagrin", "noun", "Annoyance", "Much to my chagrin."),
    ("chameleon", "noun", "A changeable person", "A political chameleon."),
    ("champion", "verb", "To support vigorously", "Champion the cause."),
    ("charlatan", "noun", "A fraud", "Exposed as a charlatan."),
    ("chary", "adjective", "Cautious", "Chary of strangers."),
    ("chasm", "noun", "A deep gap", "A political chasm."),
    ("chastise", "verb", "To reprimand severely", "Chastise for errors."),
    ("cherubic", "adjective", "Sweet and innocent", "A cherubic face."),
    ("chicanery", "noun", "Trickery", "Political chicanery."),
    ("chide", "verb", "To scold", "Chide for laziness."),
    ("chimerical", "adjective", "Imaginary", "Chimerical ideas."),
    ("choleric", "adjective", "Bad-tempered", "A choleric disposition."),
    ("chronology", "noun", "Arrangement of events by time", "A chronology of events."),
    ("churlish", "adjective", "Rude", "Churlish behavior."),
    ("circuitous", "adjective", "Roundabout", "A circuitous route."),
    ("circumlocution", "noun", "Using many words", "Avoid circumlocution."),
    ("circumscribe", "verb", "To restrict", "Circumscribe powers."),
    ("circumspect", "adjective", "Cautious", "Be circumspect."),
    ("circumvent", "verb", "To find a way around", "Circumvent regulations."),
    ("clairvoyant", "noun", "A person who sees the future", "Consult a clairvoyant."),
    ("clamor", "noun", "A loud noise", "Public clamor."),
    ("clandestine", "adjective", "Kept secret", "A clandestine meeting."),
    ("claque", "noun", "A group of hired applauders", "A political claque."),
    ("clemency", "noun", "Mercy", "Grant clemency."),
    ("cliche", "noun", "An overused phrase", "Avoid cliches."),
    ("clique", "noun", "An exclusive group", "A social clique."),
    ("clout", "noun", "Influence", "Political clout."),
    ("coalesce", "verb", "To come together", "Ideas coalesce."),
    ("coddle", "verb", "To treat indulgently", "Don't coddle them."),
    ("codify", "verb", "To arrange systematically", "Codify the laws."),
    ("coerce", "verb", "To force", "Coerce into confessing."),
    ("cogent", "adjective", "Convincing", "A cogent argument."),
    ("cogitate", "verb", "To think deeply", "Cogitate on the matter."),
    ("cognizant", "adjective", "Having knowledge", "Cognizant of the risks."),
    ("coherent", "adjective", "Logical", "A coherent argument."),
    ("cohort", "noun", "A group", "A cohort of students."),
    ("collateral", "adjective", "Additional but subordinate", "Collateral damage."),
    ("colloquial", "adjective", "Used in conversation", "Colloquial language."),
    ("collusion", "noun", "Secret cooperation", "Act in collusion."),
    ("colossal", "adjective", "Extremely large", "A colossal mistake."),
    ("comatose", "adjective", "Unconscious", "In a comatose state."),
    ("combustible", "adjective", "Able to catch fire", "Combustible materials."),
    ("comely", "adjective", "Pleasant to look at", "A comely appearance."),
    ("commend", "verb", "To praise", "Commend for bravery."),
    ("commensurate", "adjective", "Corresponding in size", "Salary commensurate with experience."),
    ("commiserate", "verb", "To express sympathy", "Commiserate over failure."),
    ("commodious", "adjective", "Roomy", "A commodious apartment."),
    ("compendium", "noun", "A collection of information", "A compendium of facts."),
    ("complacent", "adjective", "Smugly satisfied", "Don't be complacent."),
    ("complaisance", "noun", "Willingness to please", "Show complaisance."),
    ("complement", "verb", "To add to", "Colors complement each other."),
    ("compliant", "adjective", "Obedient", "A compliant employee."),
    ("complicit", "adjective", "Involved in wrongdoing", "Complicit in crime."),
    ("comport", "verb", "To conduct oneself", "Comport with dignity."),
    ("composure", "noun", "Calmness", "Maintain composure."),
    ("compunction", "noun", "A feeling of guilt", "Without compunction."),
    ("concatenate", "verb", "To link together", "Concatenate events."),
    ("concede", "verb", "To admit", "Concede defeat."),
    ("conceit", "noun", "Excessive pride", "Full of conceit."),
    ("concerted", "adjective", "Done together", "A concerted effort."),
    ("conciliate", "verb", "To win over", "Conciliate opponents."),
    ("concise", "adjective", "Brief", "A concise summary."),
    ("conclave", "noun", "A private meeting", "A secret conclave."),
    ("concomitant", "adjective", "Accompanying", "Concomitant risks."),
    ("concord", "noun", "Agreement", "Live in concord."),
    ("concur", "verb", "To agree", "I concur."),
    ("condescend", "verb", "To act superior", "Condescend to speak."),
    ("condone", "verb", "To accept behavior", "Cannot condone violence."),
    ("conducive", "adjective", "Making likely to happen", "Conducive to learning."),
    ("conflagration", "noun", "A large fire", "A conflagration spread."),
    ("confluence", "noun", "A coming together", "A confluence of rivers."),
    ("confound", "verb", "To confuse", "Confound expectations."),
    ("congenial", "adjective", "Pleasant", "A congenial atmosphere."),
    ("congenital", "adjective", "Present from birth", "A congenital defect."),
    ("conglomerate", "noun", "A large corporation", "A media conglomerate."),
    ("conjecture", "noun", "An opinion based on incomplete information", "Pure conjecture."),
    ("conjugal", "adjective", "Relating to marriage", "Conjugal rights."),
    ("conjure", "verb", "To make appear by magic", "Conjure images."),
    ("connive", "verb", "To secretly allow", "Connive at wrongdoing."),
    ("connoisseur", "noun", "An expert judge", "A wine connoisseur."),
    ("conscientious", "adjective", "Wishing to do right", "A conscientious worker."),
    ("consecrate", "verb", "To make sacred", "Consecrate the church."),
    ("consensus", "noun", "General agreement", "Reach consensus."),
    ("consequential", "adjective", "Important", "A consequential decision."),
    ("consign", "verb", "To deliver to a person's custody", "Consign to oblivion."),
    ("consolidate", "verb", "To make stronger", "Consolidate power."),
    ("consonance", "noun", "Agreement", "In consonance with policy."),
    ("consort", "verb", "To associate", "Consort with criminals."),
    ("conspicuous", "adjective", "Easily seen", "Conspicuous success."),
    ("constituent", "noun", "A member of a constituency", "Listen to constituents."),
    ("constrain", "verb", "To compel", "Constrained to act."),
    ("construe", "verb", "To interpret", "Construe as criticism."),
    ("consummate", "adjective", "Complete", "Consummate skill."),
    ("contagion", "noun", "Spread of disease", "Prevent contagion."),
    ("contemplate", "verb", "To think about", "Contemplate the future."),
    ("contemporary", "adjective", "Living at the same time", "Contemporary art."),
    ("contempt", "noun", "The feeling of despising", "Treat with contempt."),
    ("contentious", "adjective", "Causing controversy", "A contentious issue."),
    ("contiguous", "adjective", "Sharing a boundary", "Contiguous states."),
    ("contingent", "adjective", "Dependent on", "Contingent upon approval."),
    ("contort", "verb", "To twist out of shape", "Contort the face."),
    ("contraband", "noun", "Smuggled goods", "Contraband items."),
    ("contravene", "verb", "To violate", "Contravene regulations."),
    ("contrite", "adjective", "Feeling remorse", "A contrite apology."),
    ("contrived", "adjective", "Artificial", "A contrived ending."),
    ("controvert", "verb", "To deny the truth of", "Controvert the claim."),
    ("contumacious", "adjective", "Stubbornly disobedient", "Contumacious behavior."),
    ("conundrum", "noun", "A difficult problem", "A moral conundrum."),
    ("convene", "verb", "To come together", "Convene a meeting."),
    ("conventional", "adjective", "Based on custom", "Conventional wisdom."),
    ("converge", "verb", "To come together", "Ideas converge."),
    ("conversant", "adjective", "Familiar with", "Conversant with the topic."),
    ("convey", "verb", "To transport or communicate", "Convey a message."),
    ("conviction", "noun", "A firmly held belief", "Speak with conviction."),
    ("convivial", "adjective", "Friendly", "A convivial atmosphere."),
    ("convoluted", "adjective", "Complex", "A convoluted plot."),
    ("copious", "adjective", "Abundant", "Copious notes."),
    ("corollary", "noun", "A natural consequence", "A corollary of success."),
    ("corporeal", "adjective", "Relating to the body", "Corporeal existence."),
    ("corpulent", "adjective", "Fat", "A corpulent figure."),
    ("corroborate", "verb", "To confirm", "Corroborate the story."),
    ("corrode", "verb", "To destroy gradually", "Acid corrodes metal."),
    ("corrosive", "adjective", "Causing corrosion", "Corrosive chemicals."),
    ("cosmopolitan", "adjective", "Familiar with many cultures", "A cosmopolitan city."),
    ("countenance", "noun", "A person's face", "A stern countenance."),
    ("counterfeit", "adjective", "Fake", "Counterfeit money."),
    ("countermand", "verb", "To cancel an order", "Countermand the directive."),
    ("counterpart", "noun", "An equivalent person", "His counterpart abroad."),
    ("coup", "noun", "A sudden seizure of power", "A military coup."),
    ("courier", "noun", "A messenger", "Send by courier."),
    ("covenant", "noun", "An agreement", "A binding covenant."),
    ("covert", "adjective", "Secret", "Covert operations."),
    ("covet", "verb", "To desire eagerly", "Covet success."),
    ("cower", "verb", "To crouch in fear", "Cower in the corner."),
]
