# 60-80 Level Words Part 3 (601-900)
WORDS_60_80_PART3 = [
    ("left", "adjective", "On the side of the body with the heart", "Turn left at the corner."),
    ("leg", "noun", "A limb used for walking", "He broke his leg."),
    ("legacy", "noun", "Something left to future generations", "Leave a positive legacy."),
    ("legal", "adjective", "Relating to the law", "Get legal advice."),
    ("legally", "adverb", "In accordance with law", "It is legally binding."),
    ("legend", "noun", "A traditional story", "The legend speaks of heroes."),
    ("legislation", "noun", "Laws collectively", "New legislation was passed."),
    ("legislative", "adjective", "Having power to make laws", "The legislative body meets today."),
    ("legitimate", "adjective", "Conforming to the law", "A legitimate concern."),
    ("lemon", "noun", "A yellow citrus fruit", "Add lemon to your tea."),
    ("length", "noun", "The measurement of something", "The length of the room is 10 meters."),
    ("less", "determiner", "Smaller in amount", "Use less sugar."),
    ("lesson", "noun", "A period of teaching", "The lesson was informative."),
    ("let", "verb", "To allow", "Let me help you."),
    ("letter", "noun", "A written message", "Send a letter."),
    ("level", "noun", "A position on a scale", "Reach the next level."),
    ("liberal", "adjective", "Open to new ideas", "Liberal policies were introduced."),
    ("library", "noun", "A building containing books", "Study in the library."),
    ("license", "noun", "A permit to do something", "Get a driving license."),
    ("lie", "verb", "To be in a horizontal position", "Lie down and rest."),
    ("life", "noun", "The existence of an individual", "Life is precious."),
    ("lifestyle", "noun", "The way a person lives", "Adopt a healthy lifestyle."),
    ("lifetime", "noun", "The duration of a person's life", "A once-in-a-lifetime opportunity."),
    ("lift", "verb", "To raise to a higher position", "Lift the box carefully."),
    ("light", "noun", "The natural agent that makes things visible", "Turn on the light."),
    ("like", "verb", "To find pleasant", "I like this song."),
    ("likely", "adjective", "Probable", "Rain is likely tomorrow."),
    ("limit", "noun", "A point beyond which something cannot go", "Set a time limit."),
    ("limitation", "noun", "A restriction", "Know your limitations."),
    ("limited", "adjective", "Restricted in size or amount", "Resources are limited."),
    ("line", "noun", "A long narrow mark", "Draw a straight line."),
    ("link", "noun", "A connection", "Click the link."),
    ("lip", "noun", "Either edge of the mouth", "She bit her lip."),
    ("list", "noun", "A series of items", "Make a shopping list."),
    ("listen", "verb", "To pay attention to sound", "Listen carefully."),
    ("listener", "noun", "A person who listens", "Be a good listener."),
    ("literally", "adverb", "In a literal manner", "I literally ran there."),
    ("literary", "adjective", "Concerning literature", "Literary works are timeless."),
    ("literature", "noun", "Written works", "Study English literature."),
    ("little", "adjective", "Small in size", "A little house."),
    ("live", "verb", "To remain alive", "Live life to the fullest."),
    ("living", "adjective", "Having life", "All living things need water."),
    ("load", "noun", "A heavy thing being carried", "Carry a heavy load."),
    ("loan", "noun", "Money that is borrowed", "Apply for a loan."),
    ("local", "adjective", "Relating to a particular place", "Support local businesses."),
    ("locate", "verb", "To discover the position of", "Locate the nearest hospital."),
    ("location", "noun", "A particular place", "Share your location."),
    ("lock", "verb", "To fasten with a lock", "Lock the door."),
    ("long", "adjective", "Of great length", "The road is long."),
    ("long-term", "adjective", "Occurring over a long period", "Think about long-term goals."),
    ("look", "verb", "To direct eyes at something", "Look at the view."),
    ("loose", "adjective", "Not tight", "The screw is loose."),
    ("lose", "verb", "To be deprived of", "Do not lose hope."),
    ("loss", "noun", "The state of losing something", "The loss was devastating."),
    ("lost", "adjective", "Unable to find the way", "I got lost in the city."),
    ("lot", "noun", "A large amount", "I learned a lot."),
    ("lots", "pronoun", "A large number", "Lots of people came."),
    ("loud", "adjective", "Making a lot of noise", "The music is too loud."),
    ("love", "noun", "An intense feeling of affection", "Love conquers all."),
    ("lovely", "adjective", "Attractive and pleasant", "What a lovely day!"),
    ("lover", "noun", "A person who loves something", "She is a music lover."),
    ("low", "adjective", "Not high", "Keep your voice low."),
    ("lower", "verb", "To reduce in amount", "Lower the price."),
    ("luck", "noun", "Success brought by chance", "Good luck!"),
    ("lucky", "adjective", "Having good luck", "I feel lucky today."),
    ("lunch", "noun", "A midday meal", "Let's have lunch together."),
    ("lung", "noun", "An organ for breathing", "Smoking damages lungs."),
    ("machine", "noun", "A mechanical device", "The machine is broken."),
    ("mad", "adjective", "Mentally ill or very angry", "Do not get mad at me."),
    ("magazine", "noun", "A periodical publication", "Read a fashion magazine."),
    ("magic", "noun", "The power of influencing events", "Believe in magic."),
    ("magical", "adjective", "Relating to magic", "A magical experience."),
    ("mail", "noun", "Letters and packages delivered", "Check the mail."),
    ("main", "adjective", "Most important", "The main entrance is here."),
    ("mainly", "adverb", "More than anything else", "It was mainly my fault."),
    ("mainstream", "adjective", "The dominant trend", "Mainstream media coverage."),
    ("maintain", "verb", "To keep in good condition", "Maintain your health."),
    ("maintenance", "noun", "The process of maintaining", "Regular maintenance is needed."),
    ("major", "adjective", "Important or serious", "A major decision."),
    ("majority", "noun", "The greater number", "The majority voted yes."),
    ("make", "verb", "To create or produce", "Make a decision."),
    ("maker", "noun", "A person who makes something", "The coffee maker is new."),
    ("makeup", "noun", "Cosmetics applied to the face", "She applied makeup."),
    ("male", "adjective", "Of the sex that produces sperm", "A male voice."),
    ("mall", "noun", "A large shopping center", "Shop at the mall."),
    ("man", "noun", "An adult male", "The man is walking."),
    ("manage", "verb", "To be in charge of", "Manage your time wisely."),
    ("management", "noun", "The process of managing", "Good management is key."),
    ("manager", "noun", "A person responsible for control", "The manager approved it."),
    ("manner", "noun", "A way of doing something", "Speak in a polite manner."),
    ("manufacturer", "noun", "A company that makes goods", "Contact the manufacturer."),
    ("manufacturing", "noun", "The making of articles on a large scale", "Manufacturing increased."),
    ("many", "determiner", "A large number of", "Many people attended."),
    ("map", "noun", "A representation of an area", "Use a map to navigate."),
    ("margin", "noun", "An edge or border", "Leave wide margins."),
    ("mark", "noun", "A visible impression", "Make your mark."),
    ("market", "noun", "A place where goods are sold", "Go to the market."),
    ("marketing", "noun", "The promotion of products", "Marketing is essential."),
    ("marriage", "noun", "The legal union of two people", "Celebrate their marriage."),
    ("married", "adjective", "United in marriage", "They are happily married."),
    ("marry", "verb", "To become spouse of", "They will marry next year."),
    ("mask", "noun", "A covering for the face", "Wear a mask."),
    ("mass", "noun", "A large body of matter", "A mass of clouds."),
    ("massive", "adjective", "Large and heavy", "A massive building."),
    ("master", "noun", "A skilled practitioner", "He is a master of his craft."),
    ("match", "noun", "A contest", "Watch the football match."),
    ("material", "noun", "The matter from which things are made", "Choose quality material."),
    ("math", "noun", "Mathematics", "Study math every day."),
    ("mathematics", "noun", "The study of numbers", "Mathematics is fundamental."),
    ("matter", "noun", "Physical substance", "Dark matter is mysterious."),
    ("maximum", "adjective", "The greatest possible", "Maximum capacity reached."),
    ("may", "verb", "Expressing possibility", "It may rain today."),
    ("maybe", "adverb", "Perhaps", "Maybe we should go."),
    ("mayor", "noun", "The head of a city", "The mayor addressed the issue."),
    ("me", "pronoun", "Used to refer to the speaker", "Give it to me."),
    ("meal", "noun", "Food eaten at a specific time", "Enjoy your meal."),
    ("mean", "verb", "To intend to convey", "What do you mean?"),
    ("meaning", "noun", "What is intended to be expressed", "The meaning is clear."),
    ("meaningful", "adjective", "Having significance", "A meaningful conversation."),
    ("means", "noun", "A method or way", "A means to an end."),
    ("meanwhile", "adverb", "In the intervening time", "Meanwhile, I will wait here."),
    ("measure", "verb", "To determine the size of", "Measure the ingredients."),
    ("measurement", "noun", "The act of measuring", "Take accurate measurements."),
    ("meat", "noun", "The flesh of an animal as food", "Cook the meat thoroughly."),
    ("mechanism", "noun", "A system of parts working together", "The mechanism is complex."),
    ("media", "noun", "The means of communication", "Social media is popular."),
    ("medical", "adjective", "Relating to medicine", "Seek medical attention."),
    ("medication", "noun", "A substance used as medicine", "Take your medication."),
    ("medicine", "noun", "The science of treating disease", "Study medicine at university."),
    ("medium", "adjective", "About halfway between extremes", "A medium-sized shirt."),
    ("meet", "verb", "To come into the presence of", "Nice to meet you."),
    ("meeting", "noun", "An assembly of people", "Attend the meeting."),
    ("member", "noun", "A person belonging to a group", "She is a member of the club."),
    ("membership", "noun", "The state of being a member", "Renew your membership."),
    ("memory", "noun", "The faculty of remembering", "She has a good memory."),
    ("mental", "adjective", "Relating to the mind", "Mental health matters."),
    ("mention", "verb", "To refer to briefly", "He mentioned your name."),
    ("menu", "noun", "A list of dishes available", "Look at the menu."),
    ("mere", "adjective", "No more than what is specified", "A mere suggestion."),
    ("merely", "adverb", "Just; only", "It was merely a joke."),
    ("mess", "noun", "A dirty or untidy state", "Clean up this mess."),
    ("message", "noun", "A written or spoken communication", "Leave a message."),
    ("metal", "noun", "A solid material that is typically hard", "The gate is made of metal."),
    ("meter", "noun", "A unit of length", "The room is 5 meters wide."),
    ("method", "noun", "A way of doing something", "Try a different method."),
    ("Mexican", "adjective", "Relating to Mexico", "Mexican food is spicy."),
    ("middle", "noun", "The central part", "Sit in the middle."),
    ("middle-class", "adjective", "Of the social group between rich and poor", "Middle-class families."),
    ("might", "verb", "Past tense of may", "It might be possible."),
    ("military", "adjective", "Relating to armed forces", "Military service is mandatory."),
    ("milk", "noun", "A white liquid from mammals", "Drink some milk."),
    ("million", "number", "The number 1,000,000", "A million dollars."),
    ("mind", "noun", "The element of a person that thinks", "Clear your mind."),
    ("mine", "pronoun", "Belonging to me", "This book is mine."),
    ("mineral", "noun", "A solid inorganic substance", "Minerals are essential."),
    ("minimum", "adjective", "The smallest possible", "Minimum wage increased."),
    ("minister", "noun", "A head of a government department", "The minister announced the policy."),
    ("ministry", "noun", "A government department", "The Ministry of Education."),
    ("minor", "adjective", "Lesser in importance", "A minor problem."),
    ("minority", "noun", "The smaller number", "The minority disagreed."),
    ("minute", "noun", "A period of 60 seconds", "Wait a minute."),
    ("miracle", "noun", "An extraordinary event", "It was a miracle."),
    ("mirror", "noun", "A reflective surface", "Look in the mirror."),
    ("miss", "verb", "To fail to hit or reach", "I miss my family."),
    ("missile", "noun", "A weapon propelled through the air", "The missile was launched."),
    ("mission", "noun", "An important assignment", "Complete the mission."),
    ("mistake", "noun", "An action that is wrong", "Learn from your mistakes."),
    ("mix", "verb", "To combine", "Mix the ingredients."),
    ("mixture", "noun", "A combination of different things", "A mixture of flavors."),
    ("mobile", "adjective", "Able to move", "Use a mobile phone."),
    ("mode", "noun", "A way of operating", "Switch to silent mode."),
    ("model", "noun", "A representation of something", "Build a model airplane."),
    ("moderate", "adjective", "Average in amount or degree", "Moderate exercise is healthy."),
    ("modern", "adjective", "Relating to the present time", "Modern technology is amazing."),
    ("modest", "adjective", "Unassuming about one's abilities", "She is very modest."),
    ("modify", "verb", "To make partial changes", "Modify the design."),
    ("mom", "noun", "One's mother", "Thanks, Mom!"),
    ("moment", "noun", "A very brief period of time", "Wait a moment."),
    ("money", "noun", "A medium of exchange", "Save money for the future."),
    ("monitor", "verb", "To observe and check", "Monitor your progress."),
    ("month", "noun", "A period of about 30 days", "Next month is busy."),
    ("monthly", "adjective", "Happening once a month", "Pay the monthly bill."),
    ("mood", "noun", "A temporary state of mind", "I am in a good mood."),
    ("moon", "noun", "The natural satellite of Earth", "The moon is bright tonight."),
    ("moral", "adjective", "Concerned with right and wrong", "A moral dilemma."),
    ("more", "determiner", "A greater amount", "I want more time."),
    ("moreover", "adverb", "In addition", "Moreover, it is cost-effective."),
    ("morning", "noun", "The early part of the day", "Good morning!"),
    ("mortgage", "noun", "A loan for property purchase", "Pay the mortgage."),
    ("most", "determiner", "The greatest amount", "Most people agree."),
    ("mostly", "adverb", "Mainly", "It was mostly cloudy."),
    ("mother", "noun", "A female parent", "Call your mother."),
    ("motion", "noun", "The action of moving", "The motion was smooth."),
    ("motivation", "noun", "A reason for acting", "Find your motivation."),
    ("motor", "noun", "A machine supplying power", "The motor is running."),
    ("mount", "verb", "To climb up", "Mount the horse."),
    ("mountain", "noun", "A large natural elevation", "Climb the mountain."),
    ("mouse", "noun", "A small rodent", "The cat chased the mouse."),
    ("mouth", "noun", "The opening in the face for eating", "Open your mouth."),
    ("move", "verb", "To change position", "Move to the left."),
    ("movement", "noun", "An act of moving", "The movement was graceful."),
    ("movie", "noun", "A motion picture", "Watch a movie tonight."),
    ("much", "determiner", "A large amount", "How much does it cost?"),
    ("multiple", "adjective", "Having many parts", "Multiple options are available."),
    ("municipal", "adjective", "Relating to a city", "Municipal elections are held."),
    ("murder", "noun", "The unlawful killing of a person", "The murder was solved."),
    ("muscle", "noun", "Body tissue producing movement", "Exercise your muscles."),
    ("museum", "noun", "A building displaying objects", "Visit the museum."),
    ("music", "noun", "Vocal or instrumental sounds", "I love music."),
    ("musical", "adjective", "Relating to music", "A musical performance."),
    ("musician", "noun", "A person who plays music", "She is a talented musician."),
    ("Muslim", "noun", "A follower of Islam", "Muslim traditions are diverse."),
    ("must", "verb", "Expressing necessity", "You must go now."),
    ("mutual", "adjective", "Shared by two or more", "Mutual respect is important."),
    ("my", "determiner", "Belonging to me", "This is my house."),
    ("myself", "pronoun", "Used for emphasis", "I did it myself."),
    ("mystery", "noun", "Something unexplained", "The mystery was solved."),
    ("myth", "noun", "A traditional story", "Greek myths are fascinating."),
    ("naked", "adjective", "Without clothes", "The naked eye can see it."),
    ("name", "noun", "A word used to identify someone", "What is your name?"),
    ("narrative", "noun", "A spoken or written account", "The narrative is compelling."),
    ("narrow", "adjective", "Of small width", "The road is narrow."),
    ("nation", "noun", "A country considered as a group", "The nation celebrated."),
    ("national", "adjective", "Relating to a nation", "National pride is strong."),
    ("native", "adjective", "Belonging to a place by birth", "A native speaker."),
    ("natural", "adjective", "Existing in nature", "Natural beauty is inspiring."),
    ("naturally", "adverb", "In a natural manner", "It comes naturally to him."),
    ("nature", "noun", "The phenomena of the physical world", "Enjoy nature."),
    ("naval", "adjective", "Relating to a navy", "Naval forces were deployed."),
    ("near", "preposition", "At a short distance from", "Stay near me."),
    ("nearby", "adjective", "Not far away", "A nearby restaurant."),
    ("nearly", "adverb", "Almost", "I nearly forgot."),
    ("necessarily", "adverb", "As a necessary result", "Not necessarily true."),
    ("necessary", "adjective", "Required or essential", "It is necessary to act."),
    ("neck", "noun", "The part of the body connecting head and body", "She wore a necklace around her neck."),
    ("need", "verb", "To require", "I need your help."),
    ("negative", "adjective", "Expressing denial", "A negative response."),
    ("negotiate", "verb", "To discuss to reach an agreement", "Negotiate the terms."),
    ("negotiation", "noun", "Discussion to reach an agreement", "Negotiations are ongoing."),
    ("neighbor", "noun", "A person living near another", "My neighbor is friendly."),
    ("neighborhood", "noun", "A district within a city", "A nice neighborhood."),
    ("neither", "determiner", "Not either of two things", "Neither option is good."),
    ("nerve", "noun", "A fiber transmitting impulses", "Calm your nerves."),
    ("nervous", "adjective", "Easily agitated", "I feel nervous before exams."),
    ("net", "noun", "A mesh material", "Catch fish with a net."),
    ("network", "noun", "A group of interconnected things", "Build a network."),
    ("never", "adverb", "At no time", "I will never forget."),
    ("nevertheless", "adverb", "In spite of that", "Nevertheless, we continued."),
    ("new", "adjective", "Not existing before", "Buy a new car."),
    ("newly", "adverb", "Recently", "A newly built house."),
    ("news", "noun", "Information about recent events", "Watch the news."),
    ("newspaper", "noun", "A printed publication with news", "Read the newspaper."),
    ("next", "adjective", "Coming immediately after", "Next week is busy."),
    ("nice", "adjective", "Pleasant", "Have a nice day!"),
    ("night", "noun", "The time from sunset to sunrise", "Good night!"),
    ("nightmare", "noun", "A frightening dream", "I had a nightmare."),
    ("nine", "number", "The number 9", "Nine students passed."),
    ("no", "determiner", "Not any", "There is no time left."),
    ("nobody", "pronoun", "No person", "Nobody knows the answer."),
    ("nod", "verb", "To move the head up and down", "He nodded in agreement."),
    ("noise", "noun", "A sound especially loud or unpleasant", "Reduce the noise."),
    ("nomination", "noun", "The action of proposing someone", "Accept the nomination."),
    ("none", "pronoun", "Not one", "None of them came."),
    ("nonetheless", "adverb", "In spite of that", "Nonetheless, I tried."),
    ("nonsense", "noun", "Foolish or meaningless talk", "That is nonsense!"),
    ("nor", "conjunction", "And not", "Neither rain nor snow."),
    ("normal", "adjective", "Conforming to a standard", "Everything is normal."),
    ("normally", "adverb", "Usually", "I normally wake up early."),
    ("north", "noun", "The direction opposite to south", "Travel north."),
    ("northern", "adjective", "In the north", "Northern regions are cold."),
    ("nose", "noun", "The organ of smell", "Follow your nose."),
    ("not", "adverb", "Used to express negation", "I am not sure."),
    ("note", "noun", "A brief written record", "Take notes in class."),
    ("notebook", "noun", "A small book for writing", "Use a notebook."),
    ("nothing", "pronoun", "Not anything", "Nothing is impossible."),
    ("notice", "verb", "To become aware of", "Notice the difference."),
    ("notion", "noun", "A concept or idea", "A vague notion."),
    ("novel", "noun", "A fictional prose narrative", "Read a novel."),
    ("now", "adverb", "At the present time", "Do it now."),
    ("nowhere", "adverb", "Not in any place", "Nowhere to go."),
    ("nuclear", "adjective", "Relating to nuclear energy", "Nuclear power plants."),
    ("number", "noun", "An arithmetical value", "Pick a number."),
    ("numerous", "adjective", "Great in number", "Numerous opportunities exist."),
    ("nurse", "noun", "A person who cares for the sick", "The nurse was kind."),
    ("nut", "noun", "A hard-shelled fruit", "Eat some nuts."),
]
