# 80-100 Level Words Part 3 (501-750)
WORDS_80_100_PART3 = [
    ("botany", "noun", "The study of plants", "Study botany at university."),
    ("bother", "verb", "To annoy or worry", "Don't bother me now."),
    ("bottleneck", "noun", "A point of congestion", "A traffic bottleneck."),
    ("bottom", "noun", "The lowest point", "At the bottom of the page."),
    ("bounce", "verb", "To spring back", "The ball bounced."),
    ("bound", "adjective", "Certain to happen", "Bound to succeed."),
    ("boundary", "noun", "A line marking limits", "Cross the boundary."),
    ("boundless", "adjective", "Unlimited", "Boundless energy."),
    ("bountiful", "adjective", "Large in quantity", "A bountiful harvest."),
    ("bounty", "noun", "Generosity or a reward", "Nature's bounty."),
    ("bow", "verb", "To bend the head as a greeting", "Bow respectfully."),
    ("boycott", "verb", "To refuse to buy or participate", "Boycott the product."),
    ("bracket", "noun", "A support projecting from a wall", "A tax bracket."),
    ("brag", "verb", "To boast", "Don't brag about it."),
    ("brain", "noun", "The organ inside the head", "Use your brain."),
    ("brake", "noun", "A device for stopping", "Apply the brakes."),
    ("branch", "noun", "A part of a tree", "A company branch."),
    ("brand", "noun", "A type of product", "A famous brand."),
    ("brash", "adjective", "Self-assertive in a rude way", "A brash comment."),
    ("brave", "adjective", "Ready to face danger", "A brave soldier."),
    ("bravery", "noun", "Courage", "Show bravery in battle."),
    ("breach", "noun", "A violation or break", "A breach of contract."),
    ("breadth", "noun", "The extent of something", "Breadth of knowledge."),
    ("break", "verb", "To separate into pieces", "Break the glass."),
    ("breakdown", "noun", "A failure or collapse", "A mental breakdown."),
    ("breakthrough", "noun", "An important discovery", "A scientific breakthrough."),
    ("breast", "noun", "The upper front of the body", "Beat your breast."),
    ("breath", "noun", "Air taken into the lungs", "Take a deep breath."),
    ("breathe", "verb", "To take air into the lungs", "Breathe deeply."),
    ("breathtaking", "adjective", "Astonishing", "A breathtaking view."),
    ("breed", "verb", "To produce offspring", "Breed animals responsibly."),
    ("breeding", "noun", "The mating of animals", "Selective breeding."),
    ("breeze", "noun", "A light wind", "A gentle breeze."),
    ("brevity", "noun", "Shortness of time", "Brevity is key."),
    ("bribe", "noun", "Money offered to influence", "Accept a bribe."),
    ("bribery", "noun", "The act of bribing", "Charged with bribery."),
    ("bridge", "noun", "A structure over water", "Cross the bridge."),
    ("brief", "adjective", "Of short duration", "A brief meeting."),
    ("briefing", "noun", "A meeting for giving information", "A press briefing."),
    ("briefly", "adverb", "For a short time", "Speak briefly."),
    ("bright", "adjective", "Giving out light", "A bright light."),
    ("brighten", "verb", "To make brighter", "Brighten the room."),
    ("brilliance", "noun", "Exceptional talent", "Show brilliance."),
    ("brilliant", "adjective", "Exceptionally clever", "A brilliant idea."),
    ("brink", "noun", "The edge of a steep place", "On the brink of disaster."),
    ("brisk", "adjective", "Active and energetic", "A brisk walk."),
    ("brittle", "adjective", "Hard but easily broken", "Brittle bones."),
    ("broad", "adjective", "Having a large area", "A broad range."),
    ("broadcast", "verb", "To transmit by radio or TV", "Broadcast the news."),
    ("broaden", "verb", "To make broader", "Broaden your horizons."),
    ("broadly", "adverb", "In general terms", "Broadly speaking."),
    ("brochure", "noun", "A booklet with information", "Read the brochure."),
    ("broker", "noun", "A person who arranges deals", "A real estate broker."),
    ("bronze", "noun", "A brown metal alloy", "A bronze medal."),
    ("brook", "noun", "A small stream", "A babbling brook."),
    ("brotherhood", "noun", "The relationship between brothers", "A sense of brotherhood."),
    ("browse", "verb", "To look through casually", "Browse the store."),
    ("bruise", "noun", "An injury appearing as discoloration", "A painful bruise."),
    ("brunt", "noun", "The chief impact", "Bear the brunt."),
    ("brush", "noun", "An implement with bristles", "Use a brush."),
    ("brutal", "adjective", "Savagely violent", "A brutal attack."),
    ("brutality", "noun", "Savage cruelty", "Police brutality."),
    ("bubble", "noun", "A thin sphere of liquid", "Blow bubbles."),
    ("buck", "noun", "A dollar", "Make a quick buck."),
    ("bucket", "noun", "A container with a handle", "Fill the bucket."),
    ("bud", "noun", "A growth that will become a flower", "A flower bud."),
    ("budget", "noun", "A financial plan", "Set a budget."),
    ("buffer", "noun", "Something that reduces shock", "A buffer zone."),
    ("bug", "noun", "An insect or a problem", "Fix the software bug."),
    ("build", "verb", "To construct", "Build a house."),
    ("builder", "noun", "A person who builds", "A home builder."),
    ("building", "noun", "A structure with walls", "A tall building."),
    ("buildup", "noun", "A gradual accumulation", "A military buildup."),
    ("bulk", "noun", "The mass or size of something", "Buy in bulk."),
    ("bulky", "adjective", "Large and unwieldy", "A bulky package."),
    ("bullet", "noun", "A projectile for a gun", "Dodge a bullet."),
    ("bulletin", "noun", "A short official statement", "A news bulletin."),
    ("bully", "noun", "A person who intimidates others", "Stand up to the bully."),
    ("bump", "verb", "To knock against", "Bump into someone."),
    ("bunch", "noun", "A cluster of things", "A bunch of grapes."),
    ("bundle", "noun", "A collection of things tied together", "A bundle of joy."),
    ("burden", "noun", "A heavy load", "Carry a burden."),
    ("burdensome", "adjective", "Difficult to carry out", "A burdensome task."),
    ("bureau", "noun", "An office or department", "The weather bureau."),
    ("bureaucracy", "noun", "A system of government by officials", "Cut through bureaucracy."),
    ("bureaucrat", "noun", "An official in a bureaucracy", "A government bureaucrat."),
    ("bureaucratic", "adjective", "Relating to bureaucracy", "Bureaucratic procedures."),
    ("burgeon", "verb", "To grow rapidly", "Burgeoning population."),
    ("burial", "noun", "The act of burying", "A burial ceremony."),
    ("burn", "verb", "To be on fire", "The fire burns."),
    ("burst", "verb", "To break open suddenly", "The balloon burst."),
    ("bury", "verb", "To put underground", "Bury the treasure."),
    ("bush", "noun", "A shrub", "Hide in the bush."),
    ("business", "noun", "Commercial activity", "Start a business."),
    ("bust", "verb", "To break", "Bust the myth."),
    ("bustle", "noun", "Excited activity", "The bustle of the city."),
    ("busy", "adjective", "Having much to do", "A busy schedule."),
    ("butcher", "noun", "A person who sells meat", "Visit the butcher."),
    ("buy", "verb", "To obtain by paying", "Buy groceries."),
    ("buyer", "noun", "A person who buys", "A potential buyer."),
    ("bypass", "verb", "To avoid or go around", "Bypass the traffic."),
    ("byproduct", "noun", "A secondary product", "A byproduct of manufacturing."),
    ("bystander", "noun", "A person present but not involved", "An innocent bystander."),
    ("cabin", "noun", "A small wooden house", "A log cabin."),
    ("cabinet", "noun", "A cupboard with shelves", "A kitchen cabinet."),
    ("cable", "noun", "A thick rope or wire", "A cable car."),
    ("cache", "noun", "A hidden store", "A cache of weapons."),
    ("calamity", "noun", "A disaster", "A natural calamity."),
    ("calculate", "verb", "To determine mathematically", "Calculate the cost."),
    ("calculation", "noun", "A mathematical determination", "A quick calculation."),
    ("calendar", "noun", "A system of organizing days", "Check the calendar."),
    ("caliber", "noun", "The quality of ability", "High caliber work."),
    ("calibrate", "verb", "To mark with a scale", "Calibrate the instrument."),
    ("call", "verb", "To shout or telephone", "Call me later."),
    ("calm", "adjective", "Not excited", "Stay calm."),
    ("calorie", "noun", "A unit of energy", "Count calories."),
    ("camaraderie", "noun", "Mutual trust among friends", "Team camaraderie."),
    ("camouflage", "noun", "A way of hiding", "Military camouflage."),
    ("campaign", "noun", "An organized course of action", "A political campaign."),
    ("campus", "noun", "The grounds of a university", "On campus housing."),
    ("canal", "noun", "An artificial waterway", "The Panama Canal."),
    ("cancel", "verb", "To decide that something will not happen", "Cancel the meeting."),
    ("cancellation", "noun", "The act of canceling", "A flight cancellation."),
    ("cancer", "noun", "A disease caused by uncontrolled cell division", "Fight cancer."),
    ("candid", "adjective", "Truthful and straightforward", "A candid opinion."),
    ("candidate", "noun", "A person seeking a position", "A job candidate."),
    ("canopy", "noun", "A covering", "A forest canopy."),
    ("canvas", "noun", "A strong cloth for painting", "Paint on canvas."),
    ("capability", "noun", "The power to do something", "Technical capability."),
    ("capable", "adjective", "Having ability", "Highly capable."),
    ("capacity", "noun", "The maximum amount", "Full capacity."),
    ("capital", "noun", "A city where government sits", "The nation's capital."),
    ("capitalism", "noun", "An economic system", "Free market capitalism."),
    ("capitalist", "noun", "A supporter of capitalism", "A venture capitalist."),
    ("capitalize", "verb", "To take advantage of", "Capitalize on opportunities."),
    ("capitulate", "verb", "To surrender", "Forced to capitulate."),
    ("caprice", "noun", "A sudden change of mood", "Act on a caprice."),
    ("capricious", "adjective", "Given to sudden changes", "Capricious weather."),
    ("captivate", "verb", "To attract and hold attention", "Captivate the audience."),
    ("captive", "noun", "A person held prisoner", "Held captive."),
    ("captivity", "noun", "The state of being captured", "Animals in captivity."),
    ("capture", "verb", "To take prisoner", "Capture the moment."),
    ("carbon", "noun", "A chemical element", "Carbon emissions."),
    ("cardinal", "adjective", "Of the greatest importance", "A cardinal rule."),
    ("career", "noun", "An occupation undertaken for life", "A successful career."),
    ("carefree", "adjective", "Free from worry", "A carefree attitude."),
    ("careful", "adjective", "Making sure to avoid danger", "Be careful."),
    ("carefully", "adverb", "With great attention", "Handle carefully."),
    ("careless", "adjective", "Not giving attention", "A careless mistake."),
    ("cargo", "noun", "Goods carried by a vehicle", "Ship cargo."),
    ("carnage", "noun", "The killing of many people", "War carnage."),
    ("carnival", "noun", "A festival with entertainment", "A street carnival."),
    ("carpenter", "noun", "A person who makes wooden objects", "A skilled carpenter."),
    ("carpet", "noun", "A floor covering", "A thick carpet."),
    ("carriage", "noun", "A vehicle pulled by horses", "A horse-drawn carriage."),
    ("carrier", "noun", "A person or thing that carries", "An aircraft carrier."),
    ("carry", "verb", "To support and move", "Carry the boxes."),
    ("carve", "verb", "To cut into a shape", "Carve a statue."),
    ("cascade", "noun", "A waterfall", "A cascade of events."),
    ("case", "noun", "An instance of something", "A court case."),
    ("cash", "noun", "Money in coins or notes", "Pay in cash."),
    ("cast", "verb", "To throw forcefully", "Cast a shadow."),
    ("casual", "adjective", "Relaxed and unconcerned", "Casual dress."),
    ("casualty", "noun", "A person killed or injured", "War casualties."),
    ("catalog", "noun", "A list of items", "A product catalog."),
    ("catalyst", "noun", "Something that causes change", "A catalyst for reform."),
    ("catastrophe", "noun", "A sudden disaster", "A natural catastrophe."),
    ("catastrophic", "adjective", "Involving a catastrophe", "Catastrophic failure."),
    ("catch", "verb", "To capture or seize", "Catch the ball."),
    ("category", "noun", "A class or division", "A product category."),
    ("cater", "verb", "To provide food and service", "Cater to their needs."),
    ("cathedral", "noun", "The principal church", "A Gothic cathedral."),
    ("cause", "noun", "A reason for something", "The cause of the problem."),
    ("caution", "noun", "Care taken to avoid danger", "Exercise caution."),
    ("cautious", "adjective", "Careful to avoid danger", "A cautious approach."),
    ("cavalry", "noun", "Soldiers on horseback", "The cavalry arrived."),
    ("cave", "noun", "A large underground chamber", "Explore the cave."),
    ("cavity", "noun", "A hollow space", "A tooth cavity."),
    ("cease", "verb", "To come to an end", "Cease operations."),
    ("ceasefire", "noun", "A temporary stop in fighting", "Declare a ceasefire."),
    ("cede", "verb", "To give up power or territory", "Cede control."),
    ("celebrate", "verb", "To mark with festivities", "Celebrate the victory."),
    ("celebrated", "adjective", "Widely known and esteemed", "A celebrated author."),
    ("celebration", "noun", "The act of celebrating", "A birthday celebration."),
    ("celebrity", "noun", "A famous person", "A movie celebrity."),
    ("cell", "noun", "The smallest unit of an organism", "A blood cell."),
    ("cement", "noun", "A building material", "Mix cement."),
    ("cemetery", "noun", "A burial ground", "Visit the cemetery."),
    ("censor", "verb", "To suppress unacceptable content", "Censor the media."),
    ("censorship", "noun", "The suppression of speech", "Media censorship."),
    ("census", "noun", "An official count of population", "Conduct a census."),
    ("center", "noun", "The middle point", "In the center."),
    ("central", "adjective", "At the center", "Central location."),
    ("centralize", "verb", "To concentrate control", "Centralize operations."),
    ("century", "noun", "A period of 100 years", "The 21st century."),
    ("ceramic", "adjective", "Made of clay", "Ceramic tiles."),
    ("ceremony", "noun", "A formal event", "A graduation ceremony."),
    ("certain", "adjective", "Known for sure", "I am certain."),
    ("certainly", "adverb", "Without doubt", "Certainly true."),
    ("certainty", "noun", "A fact that is certain", "With certainty."),
    ("certificate", "noun", "An official document", "A birth certificate."),
    ("certification", "noun", "The process of certifying", "Professional certification."),
    ("certify", "verb", "To officially recognize", "Certify the document."),
    ("cessation", "noun", "The ending of something", "Cessation of hostilities."),
    ("chain", "noun", "A series of linked rings", "A chain reaction."),
    ("chair", "noun", "A seat for one person", "Sit on the chair."),
    ("chairman", "noun", "A person in charge of a meeting", "The board chairman."),
    ("challenge", "noun", "A difficult task", "Accept the challenge."),
    ("challenging", "adjective", "Testing one's abilities", "A challenging project."),
    ("chamber", "noun", "A large room", "A council chamber."),
    ("champion", "noun", "A winner of a competition", "The world champion."),
    ("championship", "noun", "A competition for champions", "Win the championship."),
    ("chance", "noun", "A possibility", "Take a chance."),
    ("chancellor", "noun", "A senior official", "The university chancellor."),
    ("chaos", "noun", "Complete disorder", "Total chaos."),
    ("chaotic", "adjective", "In a state of chaos", "A chaotic situation."),
    ("chapel", "noun", "A small church", "A wedding chapel."),
    ("chapter", "noun", "A main division of a book", "Chapter one."),
    ("character", "noun", "The mental qualities of a person", "A strong character."),
    ("characteristic", "noun", "A typical feature", "A defining characteristic."),
    ("characterize", "verb", "To describe the qualities of", "Characterize the problem."),
    ("charge", "verb", "To accuse formally", "Charge with a crime."),
    ("charisma", "noun", "Compelling charm", "Natural charisma."),
    ("charismatic", "adjective", "Having charisma", "A charismatic leader."),
    ("charitable", "adjective", "Relating to charity", "A charitable donation."),
    ("charity", "noun", "An organization helping those in need", "Donate to charity."),
    ("charm", "noun", "The power of pleasing", "Personal charm."),
    ("charming", "adjective", "Very pleasant", "A charming personality."),
    ("chart", "noun", "A graphical representation", "A bar chart."),
    ("charter", "noun", "A written grant of rights", "A company charter."),
    ("chase", "verb", "To pursue", "Chase the thief."),
    ("chasm", "noun", "A deep gap", "A political chasm."),
    ("cheap", "adjective", "Low in price", "A cheap option."),
    ("cheat", "verb", "To act dishonestly", "Don't cheat on tests."),
    ("check", "verb", "To examine", "Check the results."),
    ("cheer", "verb", "To shout encouragement", "Cheer the team."),
    ("cheerful", "adjective", "Noticeably happy", "A cheerful smile."),
    ("chemical", "noun", "A substance produced by chemistry", "A dangerous chemical."),
    ("chemistry", "noun", "The study of substances", "Study chemistry."),
    ("cherish", "verb", "To protect lovingly", "Cherish the memory."),
    ("chest", "noun", "The upper front of the body", "A pain in the chest."),
    ("chew", "verb", "To bite and work in the mouth", "Chew your food."),
    ("chief", "adjective", "Most important", "The chief reason."),
    ("child", "noun", "A young person", "A happy child."),
    ("childhood", "noun", "The state of being a child", "Happy childhood."),
    ("chill", "noun", "An uncomfortable coldness", "A chill in the air."),
    ("chilly", "adjective", "Uncomfortably cold", "A chilly morning."),
]
