# 60-80 Level Words Part 4 (901-1200)
WORDS_60_80_PART4 = [
    ("object", "noun", "A material thing", "The object is heavy."),
    ("objective", "noun", "A goal or aim", "Define your objectives."),
    ("obligation", "noun", "A duty or commitment", "Fulfill your obligations."),
    ("observation", "noun", "The action of observing", "Make careful observations."),
    ("observe", "verb", "To watch carefully", "Observe the experiment."),
    ("observer", "noun", "A person who observes", "The observer noted everything."),
    ("obtain", "verb", "To get or acquire", "Obtain permission first."),
    ("obvious", "adjective", "Easily perceived", "The answer is obvious."),
    ("obviously", "adverb", "In a way that is obvious", "Obviously, we need to act."),
    ("occasion", "noun", "A particular event", "A special occasion."),
    ("occasional", "adjective", "Occurring sometimes", "Occasional rain is expected."),
    ("occasionally", "adverb", "Sometimes", "I occasionally eat out."),
    ("occupation", "noun", "A person's job", "State your occupation."),
    ("occupy", "verb", "To fill or take up space", "The building is occupied."),
    ("occur", "verb", "To happen", "Accidents can occur anytime."),
    ("ocean", "noun", "A very large expanse of sea", "The ocean is deep."),
    ("odd", "adjective", "Strange or unusual", "That's odd behavior."),
    ("odds", "noun", "The probability of something", "The odds are good."),
    ("of", "preposition", "Expressing the relationship", "A piece of cake."),
    ("off", "adverb", "Away from a place", "Turn off the lights."),
    ("offense", "noun", "A breach of a law", "Take no offense."),
    ("offensive", "adjective", "Causing offense", "Avoid offensive language."),
    ("offer", "verb", "To present for acceptance", "Offer your help."),
    ("offering", "noun", "Something offered", "A special offering."),
    ("office", "noun", "A room for business", "Come to my office."),
    ("officer", "noun", "A person with authority", "The officer on duty."),
    ("official", "adjective", "Relating to an authority", "Official documents are required."),
    ("officially", "adverb", "In an official manner", "Officially announced."),
    ("often", "adverb", "Frequently", "I often walk here."),
    ("oh", "interjection", "Expressing surprise", "Oh, I see!"),
    ("oil", "noun", "A thick liquid from petroleum", "Oil prices rose."),
    ("okay", "adjective", "Acceptable", "Is everything okay?"),
    ("old", "adjective", "Having lived for many years", "An old friend."),
    ("Olympic", "adjective", "Relating to the Olympics", "Olympic athletes train hard."),
    ("on", "preposition", "Touching the surface of", "Put it on the table."),
    ("once", "adverb", "One time only", "I met her once."),
    ("one", "number", "The lowest cardinal number", "One day at a time."),
    ("ongoing", "adjective", "Continuing", "The ongoing project."),
    ("onion", "noun", "A vegetable with layers", "Chop the onion."),
    ("online", "adjective", "Connected to the internet", "Shop online."),
    ("only", "adverb", "Solely", "Only you can do it."),
    ("onto", "preposition", "Moving to a position on", "Jump onto the bus."),
    ("open", "adjective", "Not closed", "The door is open."),
    ("opening", "noun", "An available space or opportunity", "Apply for the job opening."),
    ("openly", "adverb", "Without concealment", "Speak openly about it."),
    ("opera", "noun", "A dramatic musical work", "Attend the opera."),
    ("operate", "verb", "To control the functioning of", "Operate the machine safely."),
    ("operating", "adjective", "In operation", "Operating costs are high."),
    ("operation", "noun", "The action of operating", "A surgical operation."),
    ("operational", "adjective", "Ready for use", "The system is operational."),
    ("operator", "noun", "A person who operates", "Call the operator."),
    ("opinion", "noun", "A view or judgment", "In my opinion, it's good."),
    ("opponent", "noun", "A person who opposes another", "Defeat your opponent."),
    ("opportunity", "noun", "A favorable circumstance", "Seize the opportunity."),
    ("oppose", "verb", "To resist or be against", "Oppose the plan."),
    ("opposed", "adjective", "Anxious to prevent or resist", "She is opposed to the idea."),
    ("opposite", "adjective", "Completely different", "The opposite direction."),
    ("opposition", "noun", "Resistance or disagreement", "Face strong opposition."),
    ("option", "noun", "A thing that may be chosen", "Consider all options."),
    ("or", "conjunction", "Used to link alternatives", "Yes or no?"),
    ("orange", "noun", "A round citrus fruit", "Eat an orange daily."),
    ("order", "noun", "An arrangement", "Put things in order."),
    ("ordinary", "adjective", "With no special features", "An ordinary day."),
    ("organic", "adjective", "Produced without chemicals", "Buy organic food."),
    ("organization", "noun", "An organized group", "Join the organization."),
    ("organizational", "adjective", "Relating to organization", "Organizational structure."),
    ("organize", "verb", "To arrange systematically", "Organize your files."),
    ("orientation", "noun", "A person's basic attitudes", "Sexual orientation rights."),
    ("origin", "noun", "The point of beginning", "The origin of the word."),
    ("original", "adjective", "Present from the beginning", "The original version."),
    ("originally", "adverb", "At first", "Originally, I planned to stay."),
    ("other", "adjective", "Additional", "Other people agree."),
    ("others", "pronoun", "Other people", "Think of others."),
    ("otherwise", "adverb", "In different circumstances", "Otherwise, we will fail."),
    ("ought", "verb", "Used to indicate duty", "You ought to go."),
    ("our", "determiner", "Belonging to us", "This is our house."),
    ("ours", "pronoun", "Used to refer to something belonging to us", "The victory is ours."),
    ("ourselves", "pronoun", "We as the object of a verb", "We did it ourselves."),
    ("out", "adverb", "Moving away", "Go out and play."),
    ("outcome", "noun", "The way something turns out", "A positive outcome."),
    ("outdoor", "adjective", "Done or located outside", "Outdoor activities."),
    ("outer", "adjective", "Outside", "Outer space is vast."),
    ("outlet", "noun", "A way to release or express", "A creative outlet."),
    ("outline", "noun", "A general description", "Provide an outline."),
    ("output", "noun", "The amount produced", "Increase output."),
    ("outside", "preposition", "Not within", "Wait outside."),
    ("outstanding", "adjective", "Exceptionally good", "Outstanding performance."),
    ("oven", "noun", "An enclosed space for cooking", "Preheat the oven."),
    ("over", "preposition", "Extending above", "Jump over the fence."),
    ("overall", "adjective", "Taking everything into account", "Overall, it was good."),
    ("overcome", "verb", "To succeed in dealing with", "Overcome your fears."),
    ("overlook", "verb", "To fail to notice", "Don't overlook the details."),
    ("overnight", "adverb", "For the duration of a night", "Stay overnight."),
    ("overseas", "adverb", "In a foreign country", "Work overseas."),
    ("overwhelming", "adjective", "Very great in amount", "Overwhelming support."),
    ("owe", "verb", "To be obligated to pay", "I owe you money."),
    ("own", "adjective", "Belonging to oneself", "My own car."),
    ("owner", "noun", "A person who owns something", "The owner of the shop."),
    ("ownership", "noun", "The act of owning", "Transfer ownership."),
    ("oxygen", "noun", "A gas essential for life", "Oxygen is vital."),
    ("pace", "noun", "A rate of movement", "Keep up the pace."),
    ("pack", "verb", "To fill a bag for traveling", "Pack your bags."),
    ("package", "noun", "A parcel", "Send the package."),
    ("page", "noun", "One side of a sheet of paper", "Turn the page."),
    ("pain", "noun", "Physical suffering", "The pain is gone."),
    ("painful", "adjective", "Causing pain", "A painful memory."),
    ("paint", "verb", "To cover with color", "Paint the wall."),
    ("painter", "noun", "A person who paints", "The painter finished the mural."),
    ("painting", "noun", "A painted picture", "A beautiful painting."),
    ("pair", "noun", "A set of two things", "A pair of shoes."),
    ("palace", "noun", "A residence of royalty", "Visit the palace."),
    ("pale", "adjective", "Light in color", "She looks pale."),
    ("Palestinian", "adjective", "Relating to Palestine", "Palestinian culture is rich."),
    ("pan", "noun", "A cooking vessel", "Use a frying pan."),
    ("panel", "noun", "A flat section forming part of something", "A solar panel."),
    ("panic", "noun", "Sudden uncontrollable fear", "Don't panic!"),
    ("paper", "noun", "Material for writing on", "Write on paper."),
    ("paragraph", "noun", "A distinct section of writing", "Read the first paragraph."),
    ("parent", "noun", "A father or mother", "Respect your parents."),
    ("park", "noun", "A public area for recreation", "Walk in the park."),
    ("parking", "noun", "The action of parking a vehicle", "Parking is free."),
    ("part", "noun", "A piece of something", "Part of the plan."),
    ("participant", "noun", "A person who participates", "All participants received prizes."),
    ("participate", "verb", "To take part in", "Participate actively."),
    ("participation", "noun", "The action of participating", "Encourage participation."),
    ("particular", "adjective", "Specific", "A particular reason."),
    ("particularly", "adverb", "Especially", "Particularly interesting."),
    ("partly", "adverb", "To some extent", "Partly cloudy."),
    ("partner", "noun", "One of a pair", "Business partner."),
    ("partnership", "noun", "An association of partners", "Form a partnership."),
    ("party", "noun", "A social gathering", "Attend the party."),
    ("pass", "verb", "To move past", "Pass the ball."),
    ("passage", "noun", "A way through", "A narrow passage."),
    ("passenger", "noun", "A traveler in a vehicle", "All passengers are safe."),
    ("passing", "adjective", "Going past", "A passing car."),
    ("passion", "noun", "Strong emotion", "Follow your passion."),
    ("passive", "adjective", "Accepting without resistance", "A passive attitude."),
    ("past", "noun", "The time before the present", "Learn from the past."),
    ("patch", "noun", "A small area", "A patch of grass."),
    ("path", "noun", "A way or track", "Follow the path."),
    ("patience", "noun", "The capacity to wait calmly", "Have patience."),
    ("patient", "noun", "A person receiving medical treatment", "The patient recovered."),
    ("pattern", "noun", "A repeated design", "A colorful pattern."),
    ("pause", "verb", "To stop temporarily", "Pause the video."),
    ("pay", "verb", "To give money for goods", "Pay the bill."),
    ("payment", "noun", "The action of paying", "Make a payment."),
    ("peace", "noun", "Freedom from disturbance", "World peace is essential."),
    ("peaceful", "adjective", "Free from disturbance", "A peaceful place."),
    ("peak", "noun", "The highest point", "Reach the peak."),
    ("peer", "noun", "A person of the same age or status", "Peer pressure."),
    ("penalty", "noun", "A punishment", "Pay the penalty."),
    ("people", "noun", "Human beings in general", "People are kind."),
    ("pepper", "noun", "A spice or vegetable", "Add some pepper."),
    ("per", "preposition", "For each", "Price per item."),
    ("perceive", "verb", "To become aware of", "Perceive the truth."),
    ("percent", "noun", "Parts per hundred", "Fifty percent."),
    ("percentage", "noun", "A proportion in hundredths", "A high percentage."),
    ("perception", "noun", "The way something is understood", "Change your perception."),
    ("perfect", "adjective", "Having all required elements", "A perfect score."),
    ("perfectly", "adverb", "In a perfect way", "Perfectly clear."),
    ("perform", "verb", "To carry out an action", "Perform well."),
    ("performance", "noun", "An act of performing", "A great performance."),
    ("perhaps", "adverb", "Maybe", "Perhaps you're right."),
    ("period", "noun", "A length of time", "A long period."),
    ("permanent", "adjective", "Lasting indefinitely", "A permanent job."),
    ("permission", "noun", "Consent or authorization", "Ask for permission."),
    ("permit", "verb", "To allow", "Permit entry."),
    ("person", "noun", "A human being", "A kind person."),
    ("personal", "adjective", "Belonging to a particular person", "Personal information."),
    ("personality", "noun", "The qualities of a person's character", "A strong personality."),
    ("personally", "adverb", "In a personal manner", "I personally think so."),
    ("personnel", "noun", "People employed in an organization", "Personnel management."),
    ("perspective", "noun", "A point of view", "Gain a new perspective."),
    ("persuade", "verb", "To convince", "Persuade them to come."),
    ("pet", "noun", "A domestic animal", "She has a pet dog."),
    ("phase", "noun", "A stage in a process", "The next phase."),
    ("phenomenon", "noun", "A remarkable occurrence", "A natural phenomenon."),
    ("philosophy", "noun", "The study of fundamental questions", "Study philosophy."),
    ("phone", "noun", "A telephone", "Answer the phone."),
    ("photo", "noun", "A photograph", "Take a photo."),
    ("photograph", "noun", "A picture taken by a camera", "Frame the photograph."),
    ("photographer", "noun", "A person who takes photographs", "The photographer captured the moment."),
    ("phrase", "noun", "A small group of words", "A common phrase."),
    ("physical", "adjective", "Relating to the body", "Physical exercise is important."),
    ("physically", "adverb", "In a physical manner", "Physically fit."),
    ("physician", "noun", "A medical doctor", "Consult a physician."),
    ("physics", "noun", "The study of matter and energy", "Study physics."),
    ("piano", "noun", "A musical instrument with keys", "Play the piano."),
    ("pick", "verb", "To choose", "Pick a card."),
    ("picture", "noun", "A visual representation", "A beautiful picture."),
    ("pie", "noun", "A baked dish", "Apple pie."),
    ("piece", "noun", "A portion of something", "A piece of cake."),
    ("pig", "noun", "A farm animal", "The pig is pink."),
    ("pile", "noun", "A heap of things", "A pile of books."),
    ("pilot", "noun", "A person who flies an aircraft", "The pilot landed safely."),
    ("pine", "noun", "An evergreen tree", "Pine trees are tall."),
    ("pink", "adjective", "A pale red color", "A pink dress."),
    ("pipe", "noun", "A tube for conveying liquids", "Fix the pipe."),
    ("pitch", "noun", "The quality of a sound", "A high pitch."),
    ("place", "noun", "A particular position", "This is the place."),
    ("plain", "adjective", "Not decorated", "Plain clothes."),
    ("plan", "noun", "A detailed proposal", "Make a plan."),
    ("plane", "noun", "An aircraft", "Catch a plane."),
    ("planet", "noun", "A celestial body", "Earth is a planet."),
    ("planning", "noun", "The process of making plans", "Urban planning."),
    ("plant", "noun", "A living organism", "Water the plant."),
    ("plastic", "noun", "A synthetic material", "Reduce plastic use."),
    ("plate", "noun", "A flat dish for food", "Put it on a plate."),
    ("platform", "noun", "A raised structure", "The train platform."),
    ("play", "verb", "To engage in activity for enjoyment", "Play outside."),
    ("player", "noun", "A person who plays a game", "A talented player."),
    ("please", "adverb", "Used to add politeness", "Please help me."),
    ("pleasure", "noun", "A feeling of enjoyment", "My pleasure."),
    ("plenty", "pronoun", "A large amount", "Plenty of time."),
    ("plot", "noun", "A plan or main story", "The plot thickens."),
    ("plus", "preposition", "With the addition of", "Two plus two."),
    ("pocket", "noun", "A small bag sewn into clothing", "Put it in your pocket."),
    ("poem", "noun", "A piece of writing", "Write a poem."),
    ("poet", "noun", "A person who writes poems", "A famous poet."),
    ("poetry", "noun", "Literary work in verse", "Read poetry."),
    ("point", "noun", "A particular spot", "The point is clear."),
    ("police", "noun", "The civil force maintaining order", "Call the police."),
    ("policy", "noun", "A course of action", "Company policy."),
    ("political", "adjective", "Relating to politics", "Political decisions."),
    ("politically", "adverb", "In a political manner", "Politically correct."),
    ("politician", "noun", "A person in politics", "The politician spoke."),
    ("politics", "noun", "The activities of government", "Discuss politics."),
    ("poll", "noun", "A survey of opinions", "Take a poll."),
    ("pollution", "noun", "The presence of harmful substances", "Reduce pollution."),
    ("pool", "noun", "A body of water for swimming", "Swim in the pool."),
    ("poor", "adjective", "Lacking money", "Help the poor."),
    ("pop", "noun", "Popular music", "Pop music is catchy."),
    ("popular", "adjective", "Liked by many people", "A popular song."),
    ("popularity", "noun", "The state of being popular", "Gained popularity."),
    ("population", "noun", "All the inhabitants of a place", "Population growth."),
    ("porch", "noun", "A covered structure at an entrance", "Sit on the porch."),
    ("port", "noun", "A harbor", "The ship docked at the port."),
    ("portion", "noun", "A part of a whole", "A small portion."),
    ("portrait", "noun", "A painting or photograph of a person", "A family portrait."),
    ("portray", "verb", "To depict in a work of art", "Portray the character."),
    ("pose", "verb", "To present a question", "Pose a question."),
    ("position", "noun", "A place where someone is", "Apply for the position."),
    ("positive", "adjective", "Expressing agreement", "A positive attitude."),
    ("possess", "verb", "To have or own", "Possess great skills."),
    ("possession", "noun", "The state of having", "Personal possessions."),
    ("possibility", "noun", "A thing that may happen", "Consider all possibilities."),
    ("possible", "adjective", "Able to be done", "Anything is possible."),
    ("possibly", "adverb", "Perhaps", "Possibly true."),
    ("post", "noun", "A piece of mail", "Send a post."),
    ("pot", "noun", "A container for cooking", "A cooking pot."),
    ("potato", "noun", "a starchy tuber", "Bake a potato."),
    ("potential", "adjective", "Having the capacity to develop", "Potential for growth."),
    ("potentially", "adverb", "With potential", "Potentially dangerous."),
    ("pound", "noun", "A unit of weight or currency", "A pound of sugar."),
    ("pour", "verb", "To cause to flow", "Pour the water."),
    ("poverty", "noun", "The state of being poor", "Fight poverty."),
    ("powder", "noun", "Fine dry particles", "Baby powder."),
    ("power", "noun", "The ability to do something", "Power of knowledge."),
    ("powerful", "adjective", "Having great power", "A powerful engine."),
    ("practical", "adjective", "Relating to practice", "Practical advice."),
    ("practice", "noun", "The actual application", "Practice makes perfect."),
    ("pray", "verb", "To address a prayer to God", "Pray for peace."),
    ("prayer", "noun", "A solemn request", "Say a prayer."),
    ("precisely", "adverb", "Exactly", "Precisely at noon."),
    ("predict", "verb", "To forecast", "Predict the weather."),
    ("prediction", "noun", "A forecast", "The prediction was accurate."),
    ("prefer", "verb", "To like better", "I prefer tea."),
    ("preference", "noun", "A greater liking", "Personal preference."),
    ("pregnancy", "noun", "The condition of being pregnant", "A healthy pregnancy."),
    ("pregnant", "adjective", "Carrying a developing embryo", "She is pregnant."),
    ("premise", "noun", "A statement assumed to be true", "Based on the premise."),
    ("premium", "noun", "An amount paid for insurance", "Pay the premium."),
    ("preparation", "noun", "The action of preparing", "Thorough preparation."),
    ("prepare", "verb", "To make ready", "Prepare for the exam."),
    ("prepared", "adjective", "Ready for something", "Be prepared."),
    ("prescription", "noun", "A doctor's written instruction", "Fill the prescription."),
    ("presence", "noun", "The state of being present", "Your presence is requested."),
    ("present", "adjective", "Being in a place", "Present at the meeting."),
    ("presentation", "noun", "The act of presenting", "Give a presentation."),
    ("preserve", "verb", "To maintain in its original state", "Preserve the forest."),
    ("president", "noun", "The head of a republic", "The president spoke."),
    ("presidential", "adjective", "Relating to a president", "Presidential election."),
    ("press", "noun", "Newspapers and journalists collectively", "The press reported."),
    ("pressure", "noun", "Continuous physical force", "Under pressure."),
    ("presumably", "adverb", "Probably", "Presumably correct."),
    ("pretty", "adjective", "Attractive", "A pretty flower."),
    ("prevent", "verb", "To stop from happening", "Prevent accidents."),
    ("previous", "adjective", "Existing before in time", "The previous owner."),
    ("previously", "adverb", "At a time before", "Previously mentioned."),
    ("price", "noun", "The amount of money required", "A fair price."),
    ("pride", "noun", "A feeling of deep pleasure", "National pride."),
    ("primarily", "adverb", "For the most part", "Primarily focused."),
    ("primary", "adjective", "Of chief importance", "The primary goal."),
    ("prime", "adjective", "Of first importance", "Prime minister."),
    ("prince", "noun", "A male royal", "The prince arrived."),
    ("princess", "noun", "A female royal", "The princess smiled."),
    ("principal", "adjective", "First in order of importance", "The principal reason."),
    ("principle", "noun", "A fundamental truth", "Principles of science."),
    ("print", "verb", "To produce by pressing", "Print the document."),
    ("printer", "noun", "A machine for printing", "The printer is jammed."),
    ("prior", "adjective", "Existing before", "Prior experience."),
    ("priority", "noun", "The state of being more important", "Top priority."),
    ("prison", "noun", "A place of confinement", "Sent to prison."),
    ("prisoner", "noun", "A person confined in prison", "The prisoner escaped."),
    ("privacy", "noun", "The state of being private", "Respect privacy."),
    ("private", "adjective", "Not public", "Private property."),
    ("prize", "noun", "A reward for achievement", "Win a prize."),
    ("probably", "adverb", "Almost certainly", "Probably true."),
    ("problem", "noun", "A matter that needs to be dealt with", "Solve the problem."),
    ("procedure", "noun", "A series of actions", "Follow the procedure."),
    ("proceed", "verb", "To continue", "Proceed with caution."),
    ("process", "noun", "A series of steps", "The process takes time."),
    ("produce", "verb", "To make or manufacture", "Produce quality goods."),
    ("producer", "noun", "A person who produces", "The movie producer."),
    ("product", "noun", "An article manufactured for sale", "A new product."),
    ("production", "noun", "The action of producing", "Increase production."),
    ("profession", "noun", "A paid occupation", "The medical profession."),
    ("professional", "adjective", "Relating to a profession", "Professional advice."),
    ("professor", "noun", "A university teacher", "The professor lectured."),
    ("profile", "noun", "An outline of something", "Update your profile."),
    ("profit", "noun", "Financial gain", "Make a profit."),
    ("program", "noun", "A set of instructions", "A computer program."),
    ("progress", "noun", "Forward movement", "Make progress."),
    ("progressive", "adjective", "Happening gradually", "Progressive change."),
    ("project", "noun", "An enterprise planned", "A school project."),
    ("prominent", "adjective", "Important or famous", "A prominent figure."),
    ("promise", "noun", "An assurance", "Keep your promise."),
    ("promote", "verb", "To support or actively encourage", "Promote the event."),
    ("promotion", "noun", "The publicizing of a product", "Sales promotion."),
]
