# 0-60 Level Words Part 3 (401-600)
WORDS_0_60_PART3 = [
    ("complex", "adjective", "Consisting of many parts", "The problem is very complex."),
    ("complicated", "adjective", "Difficult to understand", "The instructions are complicated."),
    ("component", "noun", "A part of something larger", "Each component is essential."),
    ("computer", "noun", "An electronic device for processing data", "The computer crashed."),
    ("concentrate", "verb", "To focus attention", "Concentrate on your studies."),
    ("concentration", "noun", "The act of concentrating", "Her concentration is remarkable."),
    ("concept", "noun", "An abstract idea", "The concept is difficult to grasp."),
    ("concern", "noun", "A matter of interest or importance", "Safety is our main concern."),
    ("concerned", "adjective", "Worried or anxious", "Parents were concerned about safety."),
    ("conclude", "verb", "To bring to an end", "We conclude that the theory is correct."),
    ("conclusion", "noun", "The end or final part", "In conclusion, we succeeded."),
    ("condition", "noun", "The state of something", "The car is in good condition."),
    ("conduct", "verb", "To carry out", "Scientists conduct experiments."),
    ("conference", "noun", "A formal meeting", "The conference attracted many experts."),
    ("confidence", "noun", "Trust in oneself or others", "She has great confidence."),
    ("confident", "adjective", "Feeling sure of oneself", "He is confident about the results."),
    ("confirm", "verb", "To verify or establish", "Please confirm your reservation."),
    ("conflict", "noun", "A serious disagreement", "The conflict lasted for years."),
    ("confront", "verb", "To face or meet", "She confronted her fears."),
    ("confuse", "verb", "To make unclear", "The instructions confuse me."),
    ("confusion", "noun", "A state of disorder", "There was confusion at the scene."),
    ("congress", "noun", "A national legislative body", "Congress passed the bill."),
    ("connect", "verb", "To join together", "Connect the cables properly."),
    ("connection", "noun", "A relationship or link", "There is a connection between them."),
    ("conscious", "adjective", "Aware of one's surroundings", "He became conscious after surgery."),
    ("consequence", "noun", "A result or effect", "Every action has consequences."),
    ("conservative", "adjective", "Favoring traditional values", "He has conservative views."),
    ("consider", "verb", "To think carefully about", "Consider all your options."),
    ("considerable", "adjective", "Large in size or amount", "She has considerable experience."),
    ("consideration", "noun", "Careful thought", "Give the matter some consideration."),
    ("consist", "verb", "To be composed of", "The team consists of five members."),
    ("consistent", "adjective", "Unchanging in achievement", "She delivers consistent results."),
    ("constant", "adjective", "Occurring continuously", "The noise was constant."),
    ("constantly", "adverb", "All the time", "Technology is constantly evolving."),
    ("constitute", "verb", "To form or compose", "Women constitute half the population."),
    ("constitution", "noun", "A body of fundamental principles", "The constitution protects rights."),
    ("construct", "verb", "To build or form", "Workers construct buildings."),
    ("construction", "noun", "The process of building", "Construction is underway."),
    ("consumer", "noun", "A person who buys goods", "Consumers demand quality products."),
    ("contact", "noun", "Communication or touch", "Keep in contact with me."),
    ("contain", "verb", "To hold within", "The box contains books."),
    ("container", "noun", "An object for holding things", "Use a container for storage."),
    ("contemporary", "adjective", "Belonging to the present time", "Contemporary art is diverse."),
    ("content", "noun", "What is contained", "The content of the book is interesting."),
    ("contest", "noun", "A competition", "She won the singing contest."),
    ("context", "noun", "The circumstances of an event", "Understand the context first."),
    ("continue", "verb", "To keep doing", "Please continue your work."),
    ("contract", "noun", "A written agreement", "Sign the contract carefully."),
    ("contrast", "noun", "A difference between things", "The contrast is striking."),
    ("contribute", "verb", "To give for a common purpose", "Everyone should contribute."),
    ("contribution", "noun", "Something given", "Your contribution is appreciated."),
    ("control", "verb", "To direct or command", "Control your emotions."),
    ("controversial", "adjective", "Causing disagreement", "The topic is controversial."),
    ("controversy", "noun", "A prolonged public dispute", "The controversy divided the nation."),
    ("convenient", "adjective", "Suitable for one's needs", "The location is convenient."),
    ("convention", "noun", "A large meeting", "The convention attracted thousands."),
    ("conventional", "adjective", "Based on accepted customs", "She prefers conventional methods."),
    ("conversation", "noun", "An informal talk", "We had a long conversation."),
    ("convert", "verb", "To change in form", "Convert the file to PDF."),
    ("convince", "verb", "To persuade someone", "She convinced me to join."),
    ("cook", "verb", "To prepare food by heating", "I cook dinner every night."),
    ("cool", "adjective", "Slightly cold", "The evening was cool."),
    ("cooperate", "verb", "To work together", "Countries must cooperate."),
    ("cooperation", "noun", "The act of working together", "International cooperation is vital."),
    ("copy", "noun", "A duplicate", "Make a copy of the document."),
    ("core", "noun", "The central part", "The core of the problem is clear."),
    ("corner", "noun", "A point where two lines meet", "Turn at the corner."),
    ("corporate", "adjective", "Relating to a corporation", "Corporate culture varies."),
    ("corporation", "noun", "A large business", "The corporation expanded globally."),
    ("correct", "adjective", "Free from error", "Your answer is correct."),
    ("cost", "noun", "The price of something", "The cost of living is high."),
    ("cotton", "noun", "A soft white fiber", "The shirt is made of cotton."),
    ("couch", "noun", "A long upholstered seat", "Sit on the couch."),
    ("could", "modal verb", "Past tense of can", "She could speak French fluently."),
    ("council", "noun", "An advisory body", "The city council met today."),
    ("count", "verb", "To determine the total number", "Count the votes carefully."),
    ("counter", "noun", "A long flat surface", "Place the items on the counter."),
    ("country", "noun", "A nation with its own government", "She traveled to another country."),
    ("county", "noun", "A territorial division", "The county has many parks."),
    ("couple", "noun", "Two people together", "The couple got married last week."),
    ("courage", "noun", "The ability to face danger", "He showed great courage."),
    ("course", "noun", "A series of lessons", "I am taking a math course."),
    ("court", "noun", "A place where legal cases are heard", "The case went to court."),
    ("cousin", "noun", "A child of one's aunt or uncle", "My cousin lives in New York."),
    ("cover", "verb", "To place something over", "Cover the pot with a lid."),
    ("coverage", "noun", "The extent of reporting", "News coverage was extensive."),
    ("crack", "verb", "To break without separating", "The glass cracked but did not break."),
    ("craft", "noun", "An activity involving skill", "She learned the craft of pottery."),
    ("crash", "verb", "To collide violently", "The car crashed into the wall."),
    ("crazy", "adjective", "Mentally deranged", "That idea is crazy."),
    ("cream", "noun", "The fatty part of milk", "Add cream to your coffee."),
    ("create", "verb", "To bring into existence", "Artists create beautiful works."),
    ("creation", "noun", "The act of creating", "The creation of the universe is a mystery."),
    ("creative", "adjective", "Relating to creativity", "She has a creative mind."),
    ("creature", "noun", "A living organism", "Every creature has a purpose."),
    ("credit", "noun", "Trust in a person's ability to pay", "She has good credit."),
    ("crew", "noun", "A group of workers", "The crew prepared the ship."),
    ("crime", "noun", "An illegal act", "Crime rates have decreased."),
    ("criminal", "noun", "A person who commits a crime", "The criminal was caught."),
    ("crisis", "noun", "A time of intense difficulty", "The country faced an economic crisis."),
    ("criterion", "noun", "A standard for judging", "What is the main criterion?"),
    ("critic", "noun", "A person who judges", "The critic reviewed the movie."),
    ("critical", "adjective", "Expressing criticism", "Critical thinking is important."),
    ("criticism", "noun", "The expression of disapproval", "She handled the criticism well."),
    ("criticize", "verb", "To express disapproval", "Do not criticize others harshly."),
    ("crop", "noun", "A cultivated plant", "The crop yield was high this year."),
    ("cross", "verb", "To go across", "Cross the street carefully."),
    ("crowd", "noun", "A large group of people", "The crowd cheered loudly."),
    ("crucial", "adjective", "Of great importance", "This is a crucial moment."),
    ("cry", "verb", "To shed tears", "The baby started to cry."),
    ("cultural", "adjective", "Relating to culture", "Cultural differences exist everywhere."),
    ("culture", "noun", "The customs and beliefs of a society", "Japanese culture is unique."),
    ("cup", "noun", "A small container for drinks", "Would you like a cup of tea?"),
    ("curious", "adjective", "Eager to know", "Children are naturally curious."),
    ("current", "adjective", "Belonging to the present time", "Current events affect us all."),
    ("currently", "adverb", "At the present time", "She is currently unavailable."),
    ("curriculum", "noun", "The subjects in a course of study", "The curriculum includes science."),
    ("customer", "noun", "A buyer of goods or services", "The customer is always right."),
    ("cut", "verb", "To divide with a sharp instrument", "Cut the paper in half."),
    ("cycle", "noun", "A series of events that repeat", "The cycle of seasons continues."),
    ("dad", "noun", "Father", "My dad taught me to drive."),
    ("daily", "adjective", "Occurring every day", "Exercise is part of my daily routine."),
    ("damage", "noun", "Physical harm", "The storm caused damage."),
    ("dance", "verb", "To move rhythmically", "She loves to dance."),
    ("danger", "noun", "The possibility of harm", "There is danger ahead."),
    ("dangerous", "adjective", "Able to cause harm", "The road is dangerous at night."),
    ("dare", "verb", "To have the courage to do", "I dare you to try."),
    ("dark", "adjective", "With little or no light", "The room was dark."),
    ("darkness", "noun", "The absence of light", "Darkness fell over the city."),
    ("data", "noun", "Facts and statistics", "Data analysis is important."),
    ("date", "noun", "A particular day", "What is today's date?"),
    ("daughter", "noun", "A female child", "Her daughter is a doctor."),
    ("day", "noun", "A 24-hour period", "Have a nice day."),
    ("dead", "adjective", "No longer alive", "The plant is dead."),
    ("deadline", "noun", "A time limit", "Meet the deadline."),
    ("deal", "verb", "To take action", "How do you deal with stress?"),
    ("dealer", "noun", "A person who sells", "The car dealer offered a discount."),
    ("dear", "adjective", "Regarded with affection", "Dear friend, I miss you."),
    ("death", "noun", "The end of life", "Death is inevitable."),
    ("debate", "noun", "A formal discussion", "The debate was intense."),
    ("debt", "noun", "Money owed", "She paid off her debt."),
    ("decade", "noun", "A period of ten years", "Technology changed in the last decade."),
    ("decide", "verb", "To make a choice", "Decide what you want to do."),
    ("decision", "noun", "A conclusion reached after consideration", "Make a wise decision."),
    ("declare", "verb", "To announce officially", "The president declared a holiday."),
    ("decline", "verb", "To refuse politely", "She declined the invitation."),
    ("decrease", "verb", "To make smaller in size", "Prices decreased this month."),
    ("deep", "adjective", "Extending far down", "The lake is deep."),
    ("deeply", "adverb", "To a great extent", "She was deeply moved."),
    ("defeat", "verb", "To win victory over", "The team defeated their rivals."),
    ("defend", "verb", "To protect from harm", "Lawyers defend their clients."),
    ("defense", "noun", "The action of protecting", "National defense is important."),
    ("define", "verb", "To state the meaning of", "Define the term clearly."),
    ("definitely", "adverb", "Without doubt", "I will definitely come."),
    ("definition", "noun", "A statement of meaning", "What is the definition of this word?"),
    ("degree", "noun", "A unit of measurement", "The temperature is 30 degrees."),
    ("delay", "noun", "A period of waiting", "There was a delay in the flight."),
    ("deliver", "verb", "To bring to a destination", "The courier will deliver the package."),
    ("delivery", "noun", "The action of delivering", "Delivery takes two days."),
    ("demand", "noun", "An insistent request", "There is high demand for the product."),
    ("democracy", "noun", "A system of government by the people", "Democracy requires participation."),
    ("democratic", "adjective", "Relating to democracy", "Democratic elections are held regularly."),
    ("demonstrate", "verb", "To show clearly", "She demonstrated how to use the tool."),
    ("demonstration", "noun", "An act of showing", "The demonstration was peaceful."),
    ("deny", "verb", "To refuse to admit", "He denied the accusations."),
    ("department", "noun", "A division of an organization", "The marketing department is busy."),
    ("depend", "verb", "To rely on", "Children depend on their parents."),
    ("dependent", "adjective", "Relying on", "Success is dependent on effort."),
    ("depression", "noun", "A state of low mood", "Depression affects many people."),
    ("depth", "noun", "The distance from top to bottom", "Measure the depth of the pool."),
    ("derive", "verb", "To obtain from a source", "The word derives from Latin."),
    ("describe", "verb", "To give an account of", "Describe what you saw."),
    ("description", "noun", "A spoken or written account", "Give a detailed description."),
    ("desert", "noun", "A dry barren area", "The Sahara is a vast desert."),
    ("deserve", "verb", "To be worthy of", "You deserve a reward."),
    ("design", "noun", "A plan or drawing", "The design is innovative."),
    ("designer", "noun", "A person who designs", "The fashion designer is famous."),
    ("desire", "noun", "A strong wish", "Her desire to succeed is strong."),
    ("desk", "noun", "A table for writing", "Clean your desk."),
    ("desperate", "adjective", "Having a great need", "He was desperate for help."),
    ("despite", "preposition", "In spite of", "Despite the rain, they went out."),
    ("destroy", "verb", "To damage beyond repair", "The fire destroyed the building."),
    ("destruction", "noun", "The action of destroying", "War brings destruction."),
    ("detail", "noun", "A small individual feature", "Pay attention to detail."),
    ("detailed", "adjective", "Having many details", "Give a detailed report."),
    ("detect", "verb", "To discover or identify", "The sensor detects motion."),
    ("determine", "verb", "To find out", "Determine the cause of the problem."),
    ("develop", "verb", "To grow or cause to grow", "Children develop quickly."),
    ("development", "noun", "The process of developing", "Economic development is important."),
    ("device", "noun", "A tool or machine", "This device is very useful."),
    ("devote", "verb", "To give time or attention to", "She devoted her life to science."),
    ("dialogue", "noun", "A conversation", "The dialogue between the characters is interesting."),
    ("die", "verb", "To cease living", "All living things eventually die."),
    ("diet", "noun", "The kinds of food a person eats", "A healthy diet is important."),
]
