# 0-60 Level Words Part 4 (601-800)
WORDS_0_60_PART4 = [
    ("differ", "verb", "To be unlike", "Our opinions differ on this matter."),
    ("difference", "noun", "A way in which things are not the same", "There is a difference between them."),
    ("different", "adjective", "Not the same", "They have different opinions."),
    ("differently", "adverb", "In a different manner", "People think differently."),
    ("difficult", "adjective", "Needing effort to accomplish", "The exam was difficult."),
    ("difficulty", "noun", "A state of hardship", "He had difficulty understanding."),
    ("digital", "adjective", "Relating to electronic technology", "Digital cameras are popular."),
    ("dimension", "noun", "A measurable extent", "Consider all dimensions of the problem."),
    ("dinner", "noun", "The main meal of the day", "Dinner is ready."),
    ("direct", "adjective", "Going straight to the point", "Give a direct answer."),
    ("direction", "noun", "A course along which someone moves", "What direction should we go?"),
    ("directly", "adverb", "Without anyone or anything in between", "Contact me directly."),
    ("director", "noun", "A person in charge", "The director made a great film."),
    ("dirt", "noun", "Loose soil or earth", "Clean the dirt off your shoes."),
    ("dirty", "adjective", "Covered with dirt", "The floor is dirty."),
    ("disability", "noun", "A physical or mental condition", "He has a learning disability."),
    ("disagree", "verb", "To have a different opinion", "I disagree with you."),
    ("disappear", "verb", "To cease to be visible", "The sun disappeared behind the clouds."),
    ("disaster", "noun", "A sudden catastrophic event", "The earthquake was a disaster."),
    ("discipline", "noun", "The practice of training", "Self-discipline is important."),
    ("discover", "verb", "To find or learn something new", "Scientists discover new species."),
    ("discovery", "noun", "The act of discovering", "The discovery changed medicine."),
    ("discrimination", "noun", "Unfair treatment of people", "Fight against discrimination."),
    ("discuss", "verb", "To talk about", "Let's discuss the plan."),
    ("discussion", "noun", "The action of talking about something", "The discussion was productive."),
    ("disease", "noun", "A disorder affecting health", "The disease spread quickly."),
    ("dish", "noun", "A container for serving food", "Wash the dishes."),
    ("dismiss", "verb", "To order to leave", "The teacher dismissed the class."),
    ("disorder", "noun", "A state of confusion", "The room was in disorder."),
    ("display", "verb", "To show or exhibit", "The museum displays art."),
    ("dispute", "noun", "A disagreement or argument", "The dispute was settled."),
    ("distance", "noun", "The amount of space between things", "What is the distance to the city?"),
    ("distant", "adjective", "Far away in space or time", "We visited a distant country."),
    ("distinct", "adjective", "Recognizably different", "Each flavor is distinct."),
    ("distinction", "noun", "A difference or contrast", "There is a clear distinction."),
    ("distinguish", "verb", "To recognize as different", "Distinguish between fact and opinion."),
    ("distribute", "verb", "To give out shares", "Distribute the papers to everyone."),
    ("distribution", "noun", "The action of distributing", "Food distribution is organized."),
    ("district", "noun", "An area of a country or city", "The shopping district is busy."),
    ("diverse", "adjective", "Showing variety", "The city has a diverse population."),
    ("diversity", "noun", "The state of being diverse", "Diversity enriches our culture."),
    ("divide", "verb", "To separate into parts", "Divide the cake equally."),
    ("division", "noun", "The action of separating", "The division of labor is fair."),
    ("divorce", "noun", "The legal ending of a marriage", "The divorce was finalized."),
    ("doctor", "noun", "A medical professional", "The doctor examined the patient."),
    ("document", "noun", "A written or printed paper", "Sign the document."),
    ("dog", "noun", "A domesticated animal", "The dog barked loudly."),
    ("dollar", "noun", "The basic unit of US currency", "It costs ten dollars."),
    ("domestic", "adjective", "Relating to the home", "Domestic chores take time."),
    ("dominant", "adjective", "Having power or influence", "The dominant team won."),
    ("dominate", "verb", "To have control over", "One company dominates the market."),
    ("door", "noun", "A hinged barrier at an entrance", "Open the door."),
    ("double", "adjective", "Twice as much", "I ordered a double portion."),
    ("doubt", "noun", "A feeling of uncertainty", "I have no doubt about it."),
    ("down", "adverb", "Toward a lower position", "Sit down please."),
    ("downtown", "noun", "The central area of a city", "Let's go downtown."),
    ("dozen", "noun", "A group of twelve", "Buy a dozen eggs."),
    ("draft", "noun", "A preliminary version", "Review the draft carefully."),
    ("drag", "verb", "To pull with force", "Drag the box across the floor."),
    ("drama", "noun", "A play for theater", "The drama was captivating."),
    ("dramatic", "adjective", "Relating to drama", "There was a dramatic change."),
    ("dramatically", "adverb", "In a dramatic manner", "Sales increased dramatically."),
    ("draw", "verb", "To produce a picture", "Draw a picture of a tree."),
    ("drawing", "noun", "A picture made with a pencil", "Her drawing is beautiful."),
    ("dream", "noun", "Images during sleep", "I had a strange dream."),
    ("dress", "noun", "A garment for women", "She wore a red dress."),
    ("drink", "verb", "To take liquid into the mouth", "Drink plenty of water."),
    ("drive", "verb", "To operate a vehicle", "I drive to work daily."),
    ("driver", "noun", "A person who drives", "The driver was careful."),
    ("drop", "verb", "To let fall", "Don't drop the glass."),
    ("drug", "noun", "A medicine or substance", "The drug helped her recover."),
    ("dry", "adjective", "Free from moisture", "The clothes are dry."),
    ("due", "adjective", "Expected at a certain time", "The report is due tomorrow."),
    ("during", "preposition", "Throughout the course of", "I work during the day."),
    ("dust", "noun", "Fine particles of matter", "Wipe the dust off the table."),
    ("duty", "noun", "A moral or legal obligation", "It is your duty to vote."),
    ("each", "determiner", "Every one of two or more", "Each student received a book."),
    ("eager", "adjective", "Strongly wanting to do something", "She is eager to learn."),
    ("ear", "noun", "The organ of hearing", "Speak into my ear."),
    ("early", "adjective", "Before the expected time", "She arrived early."),
    ("earn", "verb", "To receive money for work", "He earns a good salary."),
    ("earnings", "noun", "Money earned", "Her earnings increased this year."),
    ("earth", "noun", "The planet we live on", "Earth is our home."),
    ("ease", "noun", "The absence of difficulty", "She completed the task with ease."),
    ("easily", "adverb", "Without difficulty", "He solved the problem easily."),
    ("east", "noun", "The direction of sunrise", "The sun rises in the east."),
    ("eastern", "adjective", "Situated in the east", "Eastern culture is fascinating."),
    ("easy", "adjective", "Not difficult", "The test was easy."),
    ("eat", "verb", "To consume food", "Let's eat lunch together."),
    ("economic", "adjective", "Relating to the economy", "Economic growth is steady."),
    ("economics", "noun", "The study of the economy", "She studies economics at university."),
    ("economist", "noun", "An expert in economics", "The economist predicted growth."),
    ("economy", "noun", "The system of production and trade", "The economy is improving."),
    ("edge", "noun", "The outer boundary", "Stand at the edge of the cliff."),
    ("editor", "noun", "A person who edits", "The editor revised the article."),
    ("educate", "verb", "To teach or train", "Schools educate children."),
    ("education", "noun", "The process of receiving instruction", "Education is important."),
    ("educational", "adjective", "Relating to education", "Educational programs are helpful."),
    ("educator", "noun", "A person who educates", "The educator inspired students."),
    ("effect", "noun", "A result or consequence", "The effect was immediate."),
    ("effective", "adjective", "Successful in producing a result", "The medicine is effective."),
    ("effectively", "adverb", "In an effective manner", "She communicates effectively."),
    ("efficiency", "noun", "The quality of being efficient", "Improve efficiency at work."),
    ("efficient", "adjective", "Achieving maximum productivity", "The new system is efficient."),
    ("effort", "noun", "A vigorous attempt", "It took great effort to finish."),
    ("egg", "noun", "An oval object laid by a bird", "Boil an egg for breakfast."),
    ("eight", "number", "The number 8", "She has eight books."),
    ("either", "determiner", "One or the other of two", "Either option works."),
    ("elderly", "adjective", "Old or aging", "Help the elderly cross the street."),
    ("elect", "verb", "To choose by voting", "Citizens elect their leaders."),
    ("election", "noun", "A formal vote", "The election results are in."),
    ("electric", "adjective", "Relating to electricity", "The car is electric."),
    ("electricity", "noun", "A form of energy", "Electricity powers our homes."),
    ("electronic", "adjective", "Relating to electronics", "Electronic devices are everywhere."),
    ("element", "noun", "A component or part", "Water is an element of life."),
    ("elementary", "adjective", "Relating to basic principles", "She teaches elementary school."),
    ("eliminate", "verb", "To remove or get rid of", "Eliminate unnecessary expenses."),
    ("else", "adverb", "In addition; besides", "What else do you need?"),
    ("elsewhere", "adverb", "In or to another place", "Look elsewhere for the answer."),
    ("email", "noun", "Electronic mail", "Send me an email."),
    ("embrace", "verb", "To accept willingly", "Embrace change positively."),
    ("emerge", "verb", "To come into view", "A new leader will emerge."),
    ("emergency", "noun", "A serious unexpected situation", "Call 911 in an emergency."),
    ("emission", "noun", "The production of gas or radiation", "Reduce carbon emissions."),
    ("emotion", "noun", "A strong feeling", "Joy is a positive emotion."),
    ("emotional", "adjective", "Relating to emotions", "It was an emotional moment."),
    ("emphasis", "noun", "Special importance given to something", "Place emphasis on quality."),
    ("emphasize", "verb", "To give special importance to", "Emphasize the main points."),
    ("empire", "noun", "A group of nations ruled by one authority", "The Roman Empire was vast."),
    ("employ", "verb", "To give work to", "The company employs 500 people."),
    ("employee", "noun", "A person employed for wages", "Each employee has benefits."),
    ("employer", "noun", "A person or company that employs", "The employer offers training."),
    ("employment", "noun", "The condition of having paid work", "Employment rates improved."),
    ("empty", "adjective", "Containing nothing", "The box is empty."),
    ("enable", "verb", "To make possible", "Technology enables communication."),
    ("encounter", "verb", "To meet unexpectedly", "I encountered an old friend."),
    ("encourage", "verb", "To give support or confidence", "Teachers encourage students."),
    ("end", "noun", "The final part", "The end of the movie was sad."),
    ("enemy", "noun", "A person hostile to another", "Know your enemy."),
    ("energy", "noun", "The capacity for work", "Renewable energy is important."),
    ("enforce", "verb", "To compel observance of a law", "Police enforce the rules."),
    ("engage", "verb", "To participate or become involved", "Engage in meaningful activities."),
    ("engagement", "noun", "A formal agreement to marry", "They announced their engagement."),
    ("engine", "noun", "A machine with moving parts", "The car engine is powerful."),
    ("engineer", "noun", "A person who designs machines", "The engineer designed the bridge."),
    ("engineering", "noun", "The branch of science and technology", "She studies engineering."),
    ("English", "noun", "The language of England", "English is widely spoken."),
    ("enhance", "verb", "To improve quality", "Enhance your skills daily."),
    ("enjoy", "verb", "To take pleasure in", "I enjoy reading books."),
    ("enormous", "adjective", "Very large in size", "The building is enormous."),
    ("enough", "determiner", "As much as required", "I have enough money."),
    ("ensure", "verb", "To make certain", "Ensure all doors are locked."),
    ("enter", "verb", "To come or go into", "Please enter the room."),
    ("enterprise", "noun", "A business or company", "Start a new enterprise."),
    ("entertainment", "noun", "Activities that provide amusement", "The entertainment was excellent."),
    ("entire", "adjective", "Whole; complete", "The entire class passed."),
    ("entirely", "adverb", "Completely", "I entirely agree with you."),
    ("entrance", "noun", "A point of entry", "The entrance is on the left."),
    ("entry", "noun", "An act of entering", "Entry is free today."),
    ("environment", "noun", "The natural world", "Protect the environment."),
    ("environmental", "adjective", "Relating to the environment", "Environmental issues are critical."),
    ("episode", "noun", "An event or incident", "Watch the latest episode."),
    ("equal", "adjective", "The same in quantity or value", "All people are equal."),
    ("equally", "adverb", "To the same extent", "Divide it equally."),
    ("equipment", "noun", "The items needed for a purpose", "Sports equipment is expensive."),
    ("equivalent", "adjective", "Equal in value or function", "Find an equivalent term."),
    ("era", "noun", "A period of history", "The digital era has begun."),
    ("error", "noun", "A mistake", "Correct the error in the report."),
    ("escape", "verb", "To get away from", "The prisoner escaped."),
    ("especially", "adverb", "In particular", "I especially like the dessert."),
    ("essay", "noun", "A short piece of writing", "Write an essay on the topic."),
    ("essential", "adjective", "Absolutely necessary", "Water is essential for life."),
    ("essentially", "adverb", "In essence", "The plan is essentially sound."),
    ("establish", "verb", "To set up on a permanent basis", "Establish a new company."),
    ("establishment", "noun", "A business or organization", "The establishment opened in 1990."),
    ("estate", "noun", "Property consisting of land", "The estate has many acres."),
    ("estimate", "verb", "To roughly calculate", "Estimate the cost first."),
    ("ethnic", "adjective", "Relating to a population group", "Ethnic diversity is celebrated."),
    ("European", "adjective", "Relating to Europe", "European culture is rich."),
    ("evaluate", "verb", "To assess the value of", "Evaluate the results carefully."),
    ("evaluation", "noun", "The making of a judgment", "Annual evaluation is required."),
    ("even", "adverb", "Used to emphasize something surprising", "Even he agreed."),
    ("evening", "noun", "The end of the day", "Good evening everyone."),
    ("event", "noun", "Something that happens", "The event was successful."),
    ("eventually", "adverb", "In the end", "She eventually succeeded."),
    ("ever", "adverb", "At any time", "Have you ever been to Paris?"),
    ("every", "determiner", "All possible", "Every student must participate."),
    ("everybody", "pronoun", "Every person", "Everybody likes music."),
    ("everyday", "adjective", "Occurring daily", "This is an everyday task."),
    ("everyone", "pronoun", "Every person", "Everyone is welcome."),
    ("everything", "pronoun", "All things", "Everything is ready."),
    ("everywhere", "adverb", "In or to all places", "Music is everywhere."),
    ("evidence", "noun", "Available facts", "There is evidence of change."),
    ("evil", "adjective", "Profoundly immoral", "Fight against evil."),
    ("evolution", "noun", "The gradual development", "Evolution takes millions of years."),
    ("evolve", "verb", "To develop gradually", "Species evolve over time."),
    ("exact", "adjective", "Precisely accurate", "Give me the exact number."),
    ("exactly", "adverb", "In an exact manner", "Do exactly as I say."),
    ("exam", "noun", "A test of knowledge", "Study for the exam."),
    ("examination", "noun", "A detailed inspection", "The medical examination was thorough."),
    ("examine", "verb", "To inspect in detail", "The doctor examined the patient."),
    ("example", "noun", "Something serving as a model", "Give me an example."),
]
